Repository ita-social-projects/horondi_client_fe, pull requests merged in 2020-11, with the labels that each got.

#295 Homepage slider
  package.json
  src/containers/cabinet/cabinet.styles.js
  src/pages/home/home.js
  src/pages/home/home.styles.js
  src/pages/home/slider-home-page/fot-home/photo_2020-07-09_15-48-27 (2).jpg
  src/pages/home/slider-home-page/fot-home/photo_2020-07-09_15-48-27.jpg
  src/pages/home/slider-home-page/fot-home/photo_2020-07-09_15-48-28.jpg
  src/pages/home/slider-home-page/slider-home-page.js
  src/pages/home/slider-home-page/slider-home-page.style.js
  src/pages/slider-home-page/index.js
  src/pages/slider-home-page/slider-home-page.js
  src/pages/slider-home-page/slider-home-page.style.js
  src/redux/homepage-slider/homepage-slider.actions.js
  src/redux/homepage-slider/homepage-slider.reducer.js
  src/redux/homepage-slider/homepage-slider.sagas.js
  src/redux/homepage-slider/homepage-slider.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/translations/homepage.translations.js
Labels: Task, front-end

#292 Product img plug
  src/images/product-plug-dark-theme-img.png
  src/images/product-plug-light-theme-img.png
  src/pages/home/categories-list/category-item/category-item.js
  src/pages/product-details/product-images/product-images.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.styles.js
  src/pages/product-details/similar-products/similar-products.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/product-list-page/product-list-item/product-list-item.style.js
Labels: UI, special task

#290 Error boundary
  src/components/error-boundary/error-boundary.js
  src/components/error-boundary/index.js
  src/pages/error-page/error-page.js
  src/routes/routes.js
Labels: Task

#257 Burger menu implementing
  src/components/app/app.js
  src/containers/sidebar/sidebar-item/index.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/containers/sidebar/sidebar-item/sidebar-items.style.js
  src/containers/sidebar/sidebar.js
  src/containers/sidebar/sidebar.styles.js
  src/pages/home/home.js
  src/redux/burger-menu/burger-menu.actions.js
  src/redux/burger-menu/burger-menu.oparations.js
  src/redux/burger-menu/burger-menu.reducer.js
  src/redux/burger-menu/burger-menu.sagas.js
  src/redux/burger-menu/burger-menu.types.js
  src/redux/products/products.reducer.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
Labels: Task

#275 Fix horizontal scroll(responsive design)
  src/components/app-header/app-header.js
  src/components/app-header/app-header.styles.js
  src/containers/cabinet/cabinet.js
  src/containers/currency/currency.js
  src/containers/navbar-left/navbar-left.styles.js
Labels: bug, front-end

#272 Header profile
  cypress/integration/header-profile.test.js
  src/components/app-header/app-header.js
  src/components/logged-cabinet/index.js
  src/components/logged-cabinet/logged-cabinet.js
  src/components/logged-cabinet/logged-cabinet.styles.js
  src/components/not-logged-cabinet/index.js
  src/components/not-logged-cabinet/not-logged-cabinet.js
  src/containers/cabinet/cabinet.js
  src/containers/cabinet/index.js
  src/containers/header-profile/header-profile.js
  src/containers/header-profile/header-profile.styles.js
  src/containers/header-profile/index.js
  src/containers/index.js
  src/translations/header-profile.translations.js
Labels: special task

#306 Plp hot fix
  src/pages/product-list-page/product-list-filter/category-filter/category-filter.js
  src/redux/products/products.operations.js
  src/redux/products/products.reducer.js
  src/redux/products/products.sagas.js
Labels: bug

#273 Cart & wishlist for logged user
  azure-pipelines.yml
  sonar-project.properties
  src/configs/index.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/pages/product-details/comments/comments.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-features/product-features.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-list-page/product-list-filter/product-list-filter.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/redux/cart/cart.sagas.js
  src/redux/home-page-looks/home-page-looks.reducer.js
  src/redux/products/products.operations.js
  src/redux/products/products.reducer.js
  src/redux/products/products.sagas.js
  src/redux/user/user.actions.js
  src/redux/user/user.operations.js
  src/redux/user/user.sagas.js
  src/redux/user/user.types.js
  src/redux/wishlist/wishlist.sagas.js
Labels: Task

#323 fixed contacts info in footer and contacts page
  src/containers/footer-lists/footer-lists.js
  src/pages/contacts/contacts.styles.js
  src/translations/footer.translations.js
Labels: Task, bug

#332 Added refresh token management
  src/configs/index.js
  src/containers/header-profile/header-profile.js
  src/fragmentTypes.json
  src/pages/login/login.js
  src/pages/login/login.styles.js
  src/redux/user/user.operations.js
  src/redux/user/user.sagas.js
  src/translations/user.translations.js
Labels: Task

#327 Wish list(add style to buttons and for deletecontainer)
  src/components/modal/modal.js
  src/components/modal/modal.styles.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.styles.js
  src/pages/wishlist/wishlist-item/wishlist-item.styles.js
Labels: refactoring
