Repository ita-social-projects/horondi_client_fe, pull requests merged in 2020-09, with the labels that each got.

#177 PDP comments
  cypress/integration/product-details.test.js
  package.json
  src/configs/index.js
  src/containers/snackbar/index.js
  src/containers/snackbar/snackbar.js
  src/images/pdp_main.jpg
  src/pages/product-details/comments/comments-item/comment-dialog/comment-dialog.js
  src/pages/product-details/comments/comments-item/comment-dialog/comment-dialog.styles.js
  src/pages/product-details/comments/comments-item/comment-dialog/index.js
  src/pages/product-details/comments/comments-item/comments-item.js
  src/pages/product-details/comments/comments-item/comments-item.styles.js
  src/pages/product-details/comments/comments-item/editable-field/editable-field.js
  src/pages/product-details/comments/comments-item/editable-field/editable-field.styles.js
  src/pages/product-details/comments/comments-item/editable-field/index.js
  src/pages/product-details/comments/comments.js
  src/pages/product-details/comments/comments.styles.js
  src/pages/product-details/product-features/product-features.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-details/product-sizes/product-sizes.styles.js
  src/pages/product-details/similar-products/similar-products.js
  src/pages/product-details/similar-products/similar-products.styles.js
  src/pages/product-list-page/product-list-page.js
  src/redux/comments/comments.actions.js
  src/redux/comments/comments.operations.js
  src/redux/comments/comments.reducer.js
  src/redux/comments/comments.sagas.js
  src/redux/comments/comments.types.js
  src/redux/comments/tests/comments.actions.test.js
  src/redux/comments/tests/comments.reducer.test.js
  src/redux/comments/tests/comments.sagas.test.js
  src/redux/products/products.actions.js
  src/redux/products/products.operations.js
  src/redux/products/products.reducer.js
  src/redux/products/products.sagas.js
  src/redux/products/products.types.js
  src/redux/products/tests/products.actions.test.js
  src/redux/products/tests/products.reducer.test.js
  src/redux/products/tests/products.saga.test.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/snackbar/snackbar.actions.js
  src/redux/snackbar/snackbar.reducer.js
  src/redux/snackbar/snackbar.types.js
  src/redux/user/user.actions.js
  src/redux/user/user.reducer.js
  src/redux/user/user.sagas.js
  src/redux/user/user.types.js
  src/services/local-storage.service.js
  src/translations/product-details.translations.js
  src/utils/client.js
  src/utils/use-validation.js
Labels: Task

#189 Home redesign
  src/configs/index.js
  src/pages/home/home.styles.js
  src/pages/home/our-looks/our-looks.js
  src/pages/home/our-looks/our-looks.style.js
Labels: special task

#191 Chat email fe
  src/configs/index.js
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/chat/chat.style.js
  src/redux/chat/chat.actions.js
  src/redux/chat/chat.operations.js
  src/redux/chat/chat.reducer.js
  src/redux/chat/chat.sagas.js
  src/redux/chat/chat.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/translations/chat.translation.js
  src/utils/client.js
Labels: front-end

#183 Business pages
  package-lock.json
  src/components/app-footer/app-footer.styles.js
  src/components/loader/loader.styles.js
  src/index.css
  src/pages/about-us/about-us.js
  src/pages/about-us/about-us.style.js
  src/pages/cart/cart.js
  src/pages/home/categories-list/categories-list.js
  src/pages/payment-shipping/index.js
  src/pages/payment-shipping/payment-shipping.js
  src/pages/payment-shipping/payment-shipping.style.js
  src/pages/privacy-policy/index.js
  src/pages/privacy-policy/privacy-policy.js
  src/pages/privacy-policy/privacy-policy.style.js
  src/pages/product-details/comments/comments-item/comments-item.js
  src/pages/products-carousel/products-carousel.js
  src/pages/profile-page/profile-page.js
  src/pages/profile-page/profile-page.styles.js
  src/pages/recovery/recovery.js
  src/pages/register/register.js
  src/redux/business-pages/business-pages.actions.js
  src/redux/business-pages/business-pages.reducer.js
  src/redux/business-pages/business-pages.sagas.js
  src/redux/business-pages/business-pages.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/user/user.actions.js
  src/redux/user/user.reducer.js
  src/redux/user/user.sagas.js
  src/routes/routes.js
  src/translations/footer.translations.js
  src/utils/imageLoad.js
Labels: Task
