Repository ita-social-projects/horondi_client_fe, pull requests merged in 2020-08, with the labels that each got.

#112 Thanks page
  src/images/rectangle.png
  src/pages/thanks-page/index.js
  src/pages/thanks-page/thanks-page.js
  src/pages/thanks-page/thanks-page.styles.js
  src/routes/routes.js
  src/translations/thanks-page.translations.js
Labels: Task

#109 Error page
  public/images/error-page/error-dark.png
  public/images/error-page/error-light.png
  src/configs/index.js
  src/images/map-placeholder.png
  src/pages/error-page/error-page.js
  src/pages/error-page/error-page.styles.js
  src/pages/error-page/index.js
  src/redux/news/news.sagas.js
  src/routes/routes.js
  src/translations/errorpage.translations.js
Labels: Task

#157 Product details page
  cypress/integration/navbar.test.js
  cypress/integration/product-details.test.js
  package.json
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/components/app/app.js
  src/components/app/app.styles.js
  src/configs/index.js
  src/index.css
  src/pages/product-details/comments/comments-item/comments-item.js
  src/pages/product-details/comments/comments-item/comments-item.styles.js
  src/pages/product-details/comments/comments-item/index.js
  src/pages/product-details/comments/comments.js
  src/pages/product-details/comments/comments.styles.js
  src/pages/product-details/comments/index.js
  src/pages/product-details/detail/detail.js
  src/pages/product-details/detail/detail.styles.js
  src/pages/product-details/detail/index.js
  src/pages/product-details/index.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-details.styles.js
  src/pages/product-details/product-features/index.js
  src/pages/product-details/product-features/product-features.js
  src/pages/product-details/product-features/product-features.styles.js
  src/pages/product-details/product-images/index.js
  src/pages/product-details/product-images/product-images.js
  src/pages/product-details/product-images/product-images.styles.js
  src/pages/product-details/product-info/index.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-info/product-info.styles.js
  src/pages/product-details/product-sizes/index.js
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-details/product-sizes/product-sizes.styles.js
  src/pages/product-details/product-submit/index.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/product-submit/product-submit.styles.js
  src/pages/product-details/similar-products/index.js
  src/pages/product-details/similar-products/similar-products-item/index.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.styles.js
  src/pages/product-details/similar-products/similar-products.css
  src/pages/product-details/similar-products/similar-products.js
  src/pages/product-details/similar-products/similar-products.styles.js
  src/redux/products/products.actions.js
  src/redux/products/products.reducer.js
  src/redux/products/products.sagas.js
  src/redux/products/products.types.js
  src/redux/products/tests/products.actions.test.js
  src/redux/products/tests/products.reducer.test.js
  src/redux/products/tests/products.saga.test.js
  src/routes/routes.js
  src/translations/product-details.translations.js
Labels: User Story

#152 Chat fe
  cypress/plugins/index.js
  cypress/support/index.js
  nginx.conf
  package.json
  src/components/app/app.js
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/chat/active-messenger/index.js
  src/containers/chat/chat.js
  src/containers/chat/chat.style.js
  src/containers/chat/index.js
  src/images/gmail.png
  src/serviceWorker.js
  src/translations/chat.translation.js
Labels: Task

#153 Contacts page
  src/containers/footer-lists/footer-lists.js
  src/images/map-medium.png
  src/images/map-placeholder.png
  src/index.js
  src/pages/contacts/contacts.js
  src/pages/contacts/contacts.styles.js
  src/pages/contacts/index.js
  src/pages/error-page/error-page.styles.js
  src/redux/contacts/contacts.actions.js
  src/redux/contacts/contacts.reducer.js
  src/redux/contacts/contacts.sagas.js
  src/redux/contacts/contacts.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/routes/routes.js
  src/translations/contacts.translations.js
Labels: Task

#162 Cart & wishlist tests
  cypress/integration/cabinet.test.js
  cypress/integration/cart.test.js
  cypress/integration/categories-list.test.js
  cypress/integration/home.test.js
  cypress/integration/wishlist.test.js
  package-lock.json
  src/components/logged-cabinet/logged-cabinet.js
  src/components/modal/modal.js
  src/components/not-logged-cabinet/not-logged-cabinet.js
  src/components/number-input/number-input.js
  src/configs/index.js
  src/containers/cabinet/cabinet.js
  src/pages/cart/cart-item/cart-item.js
  src/pages/cart/empty-cart/empty-cart.js
  src/pages/cart/filled-cart/filled-cart.js
  src/pages/home/categories-list/category-item/category-item.js
  src/pages/home/home.js
  src/pages/wishlist/empty-wishlist/empty-wishlist.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.styles.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/redux/cart/cart.sagas.js
  src/redux/cart/tests/cart.actions.test.js
  src/redux/cart/tests/cart.reducer.test.js
  src/redux/cart/tests/cart.sagas.test.js
  src/redux/wishlist/tests/wishlist.actions.test.js
  src/redux/wishlist/tests/wishlist.reducer.test.js
  src/redux/wishlist/tests/wishlist.sagas.test.js
  src/redux/wishlist/wishlist.sagas.js
  src/translations/wishlist.translations.js
Labels: Task, test
