Repository ita-social-projects/horondi_client_fe, pull requests merged in 2020-10, with the labels that each got.

#220 Fix error page messages
  src/pages/error-page/error-page.js
  src/translations/errorpage.translations.js
Labels: Task, refactoring

#202 Home carousel
  src/configs/index.js
  src/pages/home/categories-list/categories-carousel.css
  src/pages/home/categories-list/categories-list.js
  src/pages/home/categories-list/categories-list.style.js
  src/pages/home/categories-list/category-item/category-item.style.js
  src/pages/product-details/similar-products/similar-products.css
  src/pages/product-details/similar-products/similar-products.js
  src/redux/business-pages/business-pages.actions.js
  src/redux/business-pages/business-pages.sagas.js
Labels: Task

#218 Business pages redux tests
  src/redux/business-pages/business-pages.reducer.js
  src/redux/business-pages/tests/business-page.variables.js
  src/redux/business-pages/tests/business-pages.actions.test.js
  src/redux/business-pages/tests/business-pages.reducer.test.js
  src/redux/business-pages/tests/business-pages.sagas.test.js
Labels: special task, test

#224 Chat fe
  src/containers/chat/chat.js
Labels: refactoring

#204 Slider on home page
  src/pages/home/home.js
  src/pages/home/slider-home-page/fot-home/photo_2020-07-09_15-48-27 (2).jpg
  src/pages/home/slider-home-page/fot-home/photo_2020-07-09_15-48-27.jpg
  src/pages/home/slider-home-page/fot-home/photo_2020-07-09_15-48-28.jpg
  src/pages/home/slider-home-page/index.js
  src/pages/home/slider-home-page/slider-home-page.js
  src/pages/home/slider-home-page/slider-home-page.style.js
Labels: front-end

#195 Checkout fe
  fragmentTypes.json
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/checkout/checkout.js
  src/containers/checkout/checkout.styles.js
  src/containers/checkout/delivery/checkout-contacts/checkout-contacts.js
  src/containers/checkout/delivery/delivery-type/delivery-info/delivery-info.js
  src/containers/checkout/delivery/delivery-type/delivery-type.js
  src/containers/checkout/delivery/delivery-type/mail-services/currier/currier-bottom.js
  src/containers/checkout/delivery/delivery-type/mail-services/nova-poshta/index.js
  src/containers/checkout/delivery/delivery-type/mail-services/nova-poshta/nova-poshta-bottom.js
  src/containers/checkout/delivery/delivery-type/mail-services/nova-poshta/nova-poshta-top.js
  src/containers/checkout/delivery/delivery-type/mail-services/self-pickup/index.js
  src/containers/checkout/delivery/delivery-type/mail-services/self-pickup/self-pickup-bottom.js
  src/containers/checkout/delivery/delivery-type/mail-services/self-pickup/self-pickup-top.js
  src/containers/checkout/delivery/delivery-type/mail-services/ukrposhta/index.js
  src/containers/checkout/delivery/delivery-type/mail-services/ukrposhta/ukrposhta-bottom.js
  src/containers/checkout/delivery/delivery-type/mail-services/ukrposhta/ukrposhta-top.js
  src/containers/checkout/delivery/delivery.js
  src/containers/checkout/delivery/index.js
  src/containers/checkout/index.js
  src/containers/checkout/order-form/index.js
  src/containers/checkout/order-form/order-form.js
  src/index.css
  src/pages/contacts/contacts.js
  src/pages/contacts/contacts.styles.js
  src/pages/news/news-detail/news-detail.style.css
  src/redux/checkout/checkout.actions.js
  src/redux/checkout/checkout.reducer.js
  src/redux/checkout/checkout.sagas.js
  src/redux/checkout/checkout.types.js
  src/redux/checkout/tests/checkout.actions.test.js
  src/redux/checkout/tests/checkout.reducer.test.js
  src/redux/checkout/tests/checkout.sagas.test.js
  src/redux/checkout/tests/checkout.variables.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/routes/routes.js
  src/translations/checkout.translations.js
Labels: front-end

#244 cart hot fixes for QC
  src/containers/cart-header/cart-header.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/redux/cart/cart.sagas.js
Labels: bug, special task

#243 Plug images
  src/containers/navbar-left/navbar-left.js
  src/pages/home/categories-list/categories-list.js
  src/pages/home/categories-list/category-item/category-item.js
  src/pages/home/home.styles.js
  src/pages/home/slider-home-page/slider-home-page.js
  src/pages/products-carousel/products-carousel.js
  src/redux/model/model.sagas.js
  src/utils/imageLoad.js
Labels: Task

#241 Home page edit
  src/configs/index.js
  src/pages/home/our-looks/our-looks.js
  src/pages/home/our-looks/our-looks.style.js
  src/redux/home-page-looks/home-page-looks.actions.js
  src/redux/home-page-looks/home-page-looks.reducer.js
  src/redux/home-page-looks/home-page-looks.sagas.js
  src/redux/home-page-looks/home-page-looks.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
Labels: Task

#256 Qc bug fixes 1
  .eslintrc
  src/components/app-footer/app-footer.styles.js
  src/components/app/app.js
  src/components/logged-cabinet/logged-cabinet.js
  src/components/not-logged-cabinet/not-logged-cabinet.js
  src/configs/index.js
  src/containers/cabinet/cabinet.js
  src/containers/cart-header/cart-header.js
  src/containers/footer-links/footer-links.styles.js
  src/containers/footer-lists/footer-lists.js
  src/containers/footer-lists/footer-lists.styles.js
  src/containers/navbar-left/navbar-left.js
  src/containers/navbar-left/navbar-left.styles.js
  src/pages/home/home.js
  src/pages/home/home.styles.js
  src/pages/materials/index.js
  src/pages/materials/materials.js
  src/pages/materials/materials.style.js
  src/pages/news/news-item/news-item.js
  src/pages/news/news-item/news-item.style.js
  src/pages/news/news-page/news-page.js
  src/pages/privacy-policy/privacy-policy.style.js
  src/pages/products-carousel/products-carousel.js
  src/pages/products-carousel/products-carousel.style.js
  src/routes/routes.js
  src/translations/footer.translations.js
Labels: UI, special task
