Repository ita-social-projects/horondi_client_fe, pull requests merged in 2020-12, with the labels that each got.

#341 Fix login form style and product list styles and fisters
  src/configs/routes.js
  src/containers/products-filters-container/index.js
  src/containers/products-filters-container/products-filters-container.js
  src/containers/products-filters-container/products-filters-container.styles.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/hooks/use-product-species.js
  src/images/8.jpg
  src/pages/login/login.js
  src/pages/login/login.styles.js
  src/pages/product-list-page/product-list-filter/category-filter/category-filter.js
  src/pages/product-list-page/product-list-filter/category-filter/index.js
  src/pages/product-list-page/product-list-filter/colors-filter/colors-filter.js
  src/pages/product-list-page/product-list-filter/colors-filter/index.js
  src/pages/product-list-page/product-list-filter/hot-item-filter/hot-item-filter.js
  src/pages/product-list-page/product-list-filter/models-filter/index.js
  src/pages/product-list-page/product-list-filter/models-filter/models-filter.js
  src/pages/product-list-page/product-list-filter/patterns-filter/index.js
  src/pages/product-list-page/product-list-filter/patterns-filter/patterns-filter.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-filter/product-list-filter.js
  src/pages/product-list-page/product-list-filter/product-list-filter.styles.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/product-list-page/product-list-item/product-list-item.style.js
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-list-page.styles.js
  src/pages/register/register.js
  src/pages/register/register.styles.js
  src/redux/products/products.actions.js
  src/redux/products/products.reducer.js
  src/redux/products/products.sagas.js
  src/redux/products/products.types.js
  src/redux/products/tests/products.actions.test.js
  src/redux/products/tests/products.reducer.test.js
  src/redux/theme/test/theme.actions.test.js
  src/redux/theme/test/theme.reducer.test.js
  src/redux/theme/theme.actions.js
  src/redux/theme/theme.reducer.js
  src/redux/theme/theme.types.js
  src/translations/product-list.translations.js
Labels: refactoring

#344 Fixed favourite icon button
  debug.log
  src/pages/product-details/product-features/product-features.js
  src/pages/product-details/product-features/product-features.styles.js
  src/pages/product-details/product-info/product-info.styles.js
  src/pages/product-details/product-sizes/product-sizes.styles.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/product-submit/product-submit.styles.js
Labels: Task

#387 Added click handlers on frontend page
  package-lock.json
  src/components/model-item/model-item.js
  src/components/model-item/model-item.style.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/pages/home/categories-list/category-item/category-item.js
Labels: UI, front-end

#441 fix base change
  src/pages/news/news-detail/news-detail.js
  src/pages/news/news-item/news-item.js
  src/pages/news/news-page/news-page.js
  src/redux/news/news.sagas.js
Labels: refactoring
