Repository ita-social-projects/horondi_client_fe, pull requests merged in 2021-08, with the labels that each got.

#847 Map is not displayed on the "Contacts"page #836
  src/pages/contacts/contacts.js
  src/pages/contacts/contacts.styles.js
Labels: bug, FrontEnd

#845 No 404 page Feature/660
  cypress/integration/not-found.test.js
  package-lock.json
  public/images/not-found-page/bag.png
  src/components/model-item/model-item.js
  src/configs/index.js
  src/const/routes.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/pages/home/categories-list/categories-list.js
  src/pages/not-found-page/index.js
  src/pages/not-found-page/not-found-page.js
  src/pages/not-found-page/not-found-page.styles.js
  src/pages/not-found-page/tests/__snapshots__/not-found-page.test.js.snap
  src/pages/not-found-page/tests/not-found-page.test.js
  src/routes/routes.js
  src/translations/not-found-page.translations.js
Labels: FrontEnd, test

#860 generated and added integrity
  public/index.html
Labels: FrontEnd

#881 added modal to cart
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/order/order-table/order-table.js
Labels: FrontEnd

#884 Update orders method after order migration in frontend
  src/utils/checkout.js
Labels: FrontEnd

#891 fixed urls on homepage
  src/pages/home/categories-list/categories-list.js
Labels: bug, FrontEnd

#897 removed *100 from orders amount
  src/redux/order/order.sagas.js
Labels: bug, FrontEnd

#896 Fix scrollbar displaying when menu open
  src/index.css
Labels: bug, FrontEnd

#903 fixed checkbox colors and renamed it from StaySignedIn to RememberMe
  src/configs/index.js
  src/pages/login/login.js
  src/redux/user/tests/user.mocks.js
  src/redux/user/tests/user.sagas.test.js
  src/translations/user.translations.js
  src/validators/login.js
Labels: bug, FrontEnd

#908 Fix label in Register form in English
  src/pages/register/register-from/register-form.js
  src/pages/register/register-from/register-form.styles.js
  src/translations/user.translations.js
Labels: bug, FrontEnd

#890 fixed wishlist for google users
  src/redux/user/tests/user.sagas.test.js
  src/redux/user/user.operations.js
  src/redux/user/user.sagas.js
Labels: bug, FrontEnd
