Repository ita-social-projects/horondi_client_fe, pull requests merged in 2021-09, with the labels that each got.

#904 Changed 'forgot password?' position #868
  src/pages/login/login.js
  src/pages/login/login.styles.js
Labels: bug, FrontEnd

#905 fixed bug when Error message below 'Email' field does not appear
  src/pages/login/login.js
  src/pages/login/login.styles.js
  src/translations/user.translations.js
  src/validators/login.js
Labels: bug, FrontEnd

#913 Fixing increase count products in cart, if it is already in it.
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/product-submit/product-submit.styles.js
  src/pages/product-details/product-submit/tests/product-details.variables.js
  src/pages/product-details/product-submit/tests/product-submit.test.js
  src/translations/product-details.translations.js
Labels: bug, FrontEnd

#918 [Your Cart-Checkout page] translation in English 'Nova post' delivery is not correct
  src/translations/cart.translations.js
Labels: bug, FrontEnd

#917 create tests for login page
  src/pages/login/tests/login-page.test.js
Labels: FrontEnd, test

#921 fixed bug with Delivery type names translation
  src/translations/cart.translations.js
Labels: bug, FrontEnd

#920 fixed price displaying in cart, wishlist, orders and catalog
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/order-history/order-history-order-item/order-history-order-item.js
  src/containers/orders/order-history/order-history-order/order-history-order.js
  src/containers/orders/order/delivery-type/delivery-type.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
  src/pages/product-details/similar-products/similar-products.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/redux/cart/cart.operations.js
  src/redux/cart/cart.sagas.js
  src/redux/order/order.sagas.js
  src/redux/products/products.operations.js
  src/redux/user/user.operations.js
  src/translations/order.translations.js
  src/translations/product-list.translations.js
  src/utils/checkout.js
  src/utils/price.js
  src/utils/priceCalculating.js
Labels: bug, FrontEnd

#928 fix buttons styles
  src/containers/cart-header/cart-header.js
  src/containers/cart-header/cart-header.styles.js
  src/containers/currency/currency.styles.js
  src/containers/header-profile/header-profile.styles.js
  src/containers/header-right-bar/header-right-bar.js
  src/containers/header-right-bar/header-right-bar.styles.js
  src/containers/language/language.styles.js
Labels: bug, FrontEnd

#926 add hook for currency
  src/containers/currency/currency-component.js
  src/containers/currency/index.js
  src/containers/header-right-bar/header-right-bar.js
Labels: bug, FrontEnd

#931 fixed codesmells
  src/configs/index.js
Labels: bug, FrontEnd

#902 Bugs/responsive design #826
  src/containers/footer-lists/footer-lists.js
  src/containers/footer-lists/tests/footer-lists.test.js
  src/pages/home/categories-list/categories-list.js
  src/pages/home/categories-list/tests/categories-list.test.js
  src/pages/home/models-list/models-list.style.js
  src/pages/product-details/product-details.styles.js
  src/pages/product-details/product-submit/product-submit.styles.js
Labels: bug, FrontEnd

#938 922/bugfix/links should work like links
  src/components/model-item/model-item.js
  src/components/model-item/model-item.style.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/containers/sidebar/sidebar-item/sidebar-items.style.js
  src/pages/home/categories-list/category-item/category-item.js
  src/pages/home/categories-list/category-item/category-item.style.js
  src/pages/wishlist/empty-wishlist/empty-wishlist.js
Labels: bug, FrontEnd

#901 Task-842 "fix the size of the image"
  package-lock.json
  package.json
  src/pages/product-details/product-images/product-images.js
  src/pages/product-details/product-images/product-images.styles.js
Labels: FrontEnd, design

#942 Register page validation for firstname and lastname
  src/validators/register.js
Labels: bug, FrontEnd
