Repository ita-social-projects/horondi_client_fe, pull requests merged in 2021-06, with the labels that each got.

#686 Default size(small PR)
  src/pages/product-details/product-details.js
Labels: FrontEnd, bug

#739 Fixed page create yourself after DB refactoring
  src/pages/images-constructor/hooks.js
  src/redux/images-constructor/constructor-model/constructor-model.operations.js
Labels: FrontEnd, bug

#735 Fixed magic strings/Fix/732
  src/const/routes.js
  src/containers/cart-header/cart-header.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout.js
  src/containers/footer-lists/footer-lists.js
  src/containers/header-profile/header-profile.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/order/delivery-type/delivery-type.js
  src/containers/orders/order/empty-order/empty-order.js
  src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.js
  src/containers/sidebar/sidebar.js
  src/pages/confirmation/confirmation.js
  src/pages/home/contructor-preview/constructor-preview.js
  src/pages/home/slider/slider-home-page.js
  src/pages/login/login.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
  src/pages/product-list-page/product-list-filter/product-list-filter.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/register/register-from/register-form.js
  src/pages/thanks-page/thanks-page.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/redux/burger-menu/burger-menu.sagas.js
  src/redux/business-pages/business-pages.sagas.js
  src/redux/categories/categories.sagas.js
  src/redux/checkout/checkout.sagas.js
  src/redux/contacts/contacts.sagas.js
  src/redux/header-links/header-links.sagas.js
  src/redux/home-page-looks/home-page-looks.sagas.js
  src/redux/homepage-slider/homepage-slider.sagas.js
  src/redux/images-constructor/constructor-basic/tests/constructor-basic.sagas.test.js
  src/redux/images-constructor/constructor-bottom/tests/constructor-bottom.sagas.test.js
  src/redux/images-constructor/constructor-front-pocket/tests/constructor-front-pocket.sagas.test.js
  src/redux/images-constructor/constructor-model/tests/constructor-model.sagas.test.js
  src/redux/images-constructor/constructor-pattern/tests/constructor-pattern.sagas.test.js
  src/redux/images-constructor/constructor.sagas.js
  src/redux/model/model.sagas.js
  src/redux/news/news.sagas.js
  src/redux/order/order.sagas.js
  src/redux/order/tests/order.sagas.test.js
  src/redux/pattern/pattern.sagas.js
  src/redux/products/products.sagas.js
  src/redux/user/user.sagas.js
  src/redux/wishlist/wishlist.sagas.js
  src/routes/routes.js
Labels: FrontEnd

#742 OrderHistory Component
  .eslintrc
  .prettierrc
  cypress/integration/product-list.test.js
  cypress/plugins/index.js
  package.json
  src/configs/index.js
  src/const/material-ui.js
  src/const/style-consts.js
  src/const/user-order-history.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/orders/order-history/order-history-order-item/order-history-order-item.js
  src/containers/orders/order-history/order-history-order-item/order-history-order-item.styles.js
  src/containers/orders/order-history/order-history-order/order-history-order.js
  src/containers/orders/order-history/order-history-order/order-history-order.styles.js
  src/containers/orders/order-history/order-history-pagination/index.js
  src/containers/orders/order-history/order-history-pagination/order-history-pagination.js
  src/containers/orders/order-history/order-history-pagination/order-history-pagination.style.js
  src/containers/orders/order-history/order-history-table/index.js
  src/containers/orders/order-history/order-history-table/order-history-table.js
  src/containers/orders/order-history/order-history-table/order-history-table.style.js
  src/hooks/use-comment-validation.js
  src/pages/images-constructor/hooks.js
  src/pages/order-history/order-history.js
  src/pages/order-history/order-history.styles.js
  src/pages/product-details/comments/comments-item/editable-field/editable-field.js
  src/pages/product-list-page/product-list-page.js
  src/redux/user/tests/user.actions.test.js
  src/redux/user/tests/user.mocks.js
  src/redux/user/tests/user.reducer.test.js
  src/redux/user/user.actions.js
  src/redux/user/user.operations.js
  src/redux/user/user.reducer.js
  src/redux/user/user.sagas.js
  src/redux/user/user.types.js
  src/translations/order.translations.js
  src/translations/user.translations.js
  src/utils/date.js
  src/utils/price.js
Labels: FrontEnd, refactoring

#746 Fixed Filters, products pagination and sort Fix/608
  package-lock.json
  src/pages/product-list-page/count-per-page/count-per-page.js
  src/pages/product-list-page/count-per-page/count-per-page.styles.js
  src/pages/product-list-page/product-list-filter/hot-item-filter/hot-item-filter.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-list-page.styles.js
  src/pages/product-list-page/product-sort/product-sort.js
  src/redux/products/products.operations.js
  src/redux/products/products.reducer.js
  src/translations/product-list.translations.js
  src/utils/priceCalculating.js
Labels: FrontEnd, bug, priority: high
