Repository ita-social-projects/horondi_client_fe, pull requests merged in 2021-02, with the labels that each got.

#515 refactored google authentication by adding react-google-login library
  package-lock.json
  package.json
  src/configs/index.js
  src/pages/login/login.js
  src/pages/login/login.styles.js
  src/redux/user/user.sagas.js
  test-report.xml
Labels: FrontEnd, bug, refactoring

#516 Bug_fix#498
  src/containers/products-filters-container/products-filters-container.js
  src/hooks/use-product-species.js
  src/pages/product-list-page/product-list-filter/product-list-filter.js
  src/pages/product-list-page/product-list-page.js
  src/pages/products-table/products-table.js
  src/redux/products/products.operations.js
  src/routes/routes.js
Labels: FrontEnd, bug, change request

#535 cart page refactoring
  cypress/integration/product-details.test.js
  src/components/modal/modal.js
  src/components/number-input/number-input.js
  src/components/number-input/number-input.styles.js
  src/configs/index.js
  src/configs/routes.js
  src/containers/cart-header/cart-header.js
  src/containers/checkout/checkout.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/cart-item/cart-item.styles.js
  src/containers/orders/cart/empty-cart/empty-cart.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/containers/orders/order/delivery-type/delivery-type.js
  src/containers/orders/order/delivery-type/delivery-type.styles.js
  src/containers/orders/order/delivery-type/index.js
  src/containers/orders/order/order-table/order-table.js
  src/containers/orders/order/order-table/order-table.styles.js
  src/pages/cart/cart.js
  src/pages/home/categories-list/categories-list.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/similar-products/similar-products.js
  src/redux/cart/cart.actions.js
  src/redux/cart/cart.sagas.js
  src/redux/cart/cart.types.js
  src/redux/categories/categories.operations.js
  src/redux/products/products.operations.js
  src/redux/products/products.sagas.js
  src/redux/root.saga.js
  src/redux/wishlist/wishlist.actions.js
  src/redux/wishlist/wishlist.sagas.js
  src/redux/wishlist/wishlist.types.js
  src/routes/routes.js
  src/translations/cart.translations.js
  src/translations/order.translations.js
  src/utils/priceCalculating.js
Labels: FrontEnd, Task, UI, refactoring

#534 implement contact info form(UI) on checkout page
  src/configs/routes.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/checkout/checkout-form/index.js
  src/containers/checkout/checkout.js
  src/containers/checkout/checkout.styles.js
  src/containers/checkout/index.js
  src/redux/checkout/checkout.operations.js
  src/redux/checkout/checkout.sagas.js
  src/translations/checkout.translations.js
Labels: FrontEnd, Task, WIP

#542 rewrite upload images from base64 in database to link on blobStorage
  package-lock.json
  package.json
  src/pages/constructor/index.js
  src/pages/images-constructor/hooks.js
  src/pages/images-constructor/images-constructor.js
  src/pages/images-constructor/images-constructor.style.js
  src/pages/images-constructor/index.js
  src/redux/images-constructor/constructor-basic/constructor-basic.actions.js
  src/redux/images-constructor/constructor-basic/constructor-basic.operations.js
  src/redux/images-constructor/constructor-basic/constructor-basic.reducer.js
  src/redux/images-constructor/constructor-basic/constructor-basic.sagas.js
  src/redux/images-constructor/constructor-basic/constructor-basic.types.js
  src/redux/images-constructor/constructor-bottom/constructor-bottom.actions.js
  src/redux/images-constructor/constructor-bottom/constructor-bottom.operations.js
  src/redux/images-constructor/constructor-bottom/constructor-bottom.reducer.js
  src/redux/images-constructor/constructor-bottom/constructor-bottom.sagas.js
  src/redux/images-constructor/constructor-bottom/constructor-bottom.types.js
  src/redux/images-constructor/constructor-front-pocket/constructor-front-pocket.actions.js
  src/redux/images-constructor/constructor-front-pocket/constructor-front-pocket.operations.js
  src/redux/images-constructor/constructor-front-pocket/constructor-front-pocket.reducer.js
  src/redux/images-constructor/constructor-front-pocket/constructor-front-pocket.sagas.js
  src/redux/images-constructor/constructor-front-pocket/constructor-front-pocket.types.js
  src/redux/images-constructor/constructor-model/constructor-model.actions.js
  src/redux/images-constructor/constructor-model/constructor-model.operations.js
  src/redux/images-constructor/constructor-model/constructor-model.reducer.js
  src/redux/images-constructor/constructor-model/constructor-model.sagas.js
  src/redux/images-constructor/constructor-model/constructor-model.types.js
  src/redux/images-constructor/constructor-pattern/constructor-pattern.actions.js
  src/redux/images-constructor/constructor-pattern/constructor-pattern.operations.js
  src/redux/images-constructor/constructor-pattern/constructor-pattern.reducer.js
  src/redux/images-constructor/constructor-pattern/constructor-pattern.sagas.js
  src/redux/images-constructor/constructor-pattern/constructor-pattern.types.js
  src/redux/images-constructor/constructor.reducer.js
  src/redux/images-constructor/constructor.sagas.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/routes/routes.js
Labels: FrontEnd, refactoring

#554 add order with self-pickup delivery type
  src/configs/index.js
  src/configs/routes.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/checkout/checkout-form/delivery/delivery.js
  src/containers/checkout/checkout-form/delivery/index.js
  src/containers/checkout/checkout-form/delivery/self-pickup/index.js
  src/containers/checkout/checkout-form/delivery/self-pickup/self-pickup.js
  src/containers/checkout/checkout-form/delivery/self-pickup/self-pickup.styles.js
  src/containers/checkout/checkout.js
  src/containers/checkout/checkout.styles.js
  src/containers/orders/order/delivery-type/delivery-type.js
  src/redux/cart/cart.actions.js
  src/redux/cart/cart.reducer.js
  src/redux/cart/cart.sagas.js
  src/redux/cart/cart.types.js
  src/redux/checkout/checkout.operations.js
  src/redux/order/order.actions.js
  src/redux/order/order.operations.js
  src/redux/order/order.reducer.js
  src/redux/order/order.sagas.js
  src/redux/order/order.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/services/local-storage.service.js
  src/translations/checkout.translations.js
  src/utils/checkout.js
Labels: FrontEnd, Task

#553 Feature/502
  src/configs/index.js
  src/containers/products-filters-container/products-filters-container.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/containers/sidebar/sidebar.js
  src/fragmentTypes.json
  src/hooks/use-product-filters.js
  src/hooks/use-product-species.js
  src/pages/product-list-page/count-per-page/count-per-page.js
  src/pages/product-list-page/product-list-filter/hot-item-filter/hot-item-filter.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-filter/product-list-filter.js
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-sort/product-sort.js
  src/redux/products/products.operations.js
  src/redux/products/products.reducer.js
  src/redux/products/products.sagas.js
  src/redux/products/products.types.js
  src/redux/selectors/multiple.selectors.js
  src/routes/routes.js
  src/translations/product-list.translations.js
Labels: Functional, bug, refactoring

#561 implement nova post and courier delivery type
  .prettierrc
  src/const/material-ui.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/checkout/checkout-form/delivery/courier/courier.js
  src/containers/checkout/checkout-form/delivery/courier/courier.styles.js
  src/containers/checkout/checkout-form/delivery/courier/index.js
  src/containers/checkout/checkout-form/delivery/delivery.js
  src/containers/checkout/checkout-form/delivery/nova-post/index.js
  src/containers/checkout/checkout-form/delivery/nova-post/nova-post.js
  src/containers/checkout/checkout-form/delivery/nova-post/nova-post.styles.js
  src/containers/checkout/checkout-form/delivery/self-pickup/self-pickup.js
  src/containers/checkout/checkout.js
  src/containers/checkout/delivery/checkout-contacts/checkout-contacts.js
  src/containers/checkout/delivery/delivery-type/delivery-info/delivery-info.js
  src/containers/checkout/delivery/delivery-type/delivery-type.js
  src/containers/checkout/delivery/delivery-type/mail-services/courier/courier-bottom.js
  src/containers/checkout/delivery/delivery-type/mail-services/nova-poshta/index.js
  src/containers/checkout/delivery/delivery-type/mail-services/nova-poshta/nova-poshta-bottom.js
  src/containers/checkout/delivery/delivery-type/mail-services/nova-poshta/nova-poshta-top.js
  src/containers/checkout/delivery/delivery-type/mail-services/self-pickup/index.js
  src/containers/checkout/delivery/delivery-type/mail-services/self-pickup/self-pickup-bottom.js
  src/containers/checkout/delivery/delivery-type/mail-services/self-pickup/self-pickup-top.js
  src/containers/checkout/delivery/delivery-type/mail-services/ukrposhta/index.js
  src/containers/checkout/delivery/delivery-type/mail-services/ukrposhta/ukrposhta-bottom.js
  src/containers/checkout/delivery/delivery-type/mail-services/ukrposhta/ukrposhta-top.js
  src/containers/checkout/delivery/delivery-type/modal/order-form-modal.js
  src/containers/checkout/delivery/delivery.js
  src/containers/checkout/delivery/delivery.styles.js
  src/containers/checkout/delivery/index.js
  src/containers/checkout/order-form/index.js
  src/containers/checkout/order-form/order-form.js
  src/redux/checkout/checkout.actions.js
  src/redux/checkout/checkout.operations.js
  src/redux/checkout/checkout.reducer.js
  src/redux/checkout/checkout.sagas.js
  src/redux/checkout/checkout.types.js
  src/redux/checkout/tests/checkout.actions.test.js
  src/redux/checkout/tests/checkout.reducer.test.js
  src/redux/checkout/tests/checkout.sagas.test.js
  src/redux/checkout/tests/checkout.variables.js
  src/redux/user/user.sagas.js
  src/translations/checkout.translations.js
  src/utils/checkout.js
  src/validators/chekout.js
Labels: FrontEnd, Task

#562 Feature/559
  src/components/app/app.js
  src/configs/index.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/pages/product-list-page/count-per-page/count-per-page.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-filter/product-list-filter.js
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-sort/product-sort.js
  src/redux/products/products.operations.js
Labels: Functional

#570 fix handle filter clear
  src/pages/product-list-page/product-list-filter/product-list-filter.js
Labels: bug

#567 write functionality for displaying constructor prices
  src/pages/images-constructor/hooks.js
  src/pages/images-constructor/images-constructor.js
  src/pages/images-constructor/images-constructor.style.js
  src/redux/images-constructor/constructor-basic/constructor-basic.operations.js
  src/redux/images-constructor/constructor-bottom/constructor-bottom.operations.js
  src/redux/images-constructor/constructor-front-pocket/constructor-front-pocket.operations.js
  src/redux/selectors/multiple.selectors.js
  src/translations/constructor.translations.js
  src/utils/constructor.js
Labels: FrontEnd
