Repository ita-social-projects/horondi_client_fe, pull requests merged in 2021-04, with the labels that each got.

#624 Added fields 'region' and 'district' to add order
  src/containers/checkout/checkout-form/delivery/ukrpost/ukrpost.js
  src/translations/checkout.translations.js
  src/utils/checkout.js
Labels: FrontEnd

#633 Fix Fondy error #632
  src/redux/order/order.sagas.js
Labels: bug

#631 Fix jumping drop down menu
  src/containers/header-profile/header-profile.js
Labels: FrontEnd, bug

#636 writing unit test for redux orders #582
  src/redux/order/order.sagas.js
  src/redux/order/tests/order.actions.test.js
  src/redux/order/tests/order.reducer.test.js
  src/redux/order/tests/order.sagas.test.js
  src/redux/order/tests/order.variables.js
Labels: FrontEnd, test

#630 Fix and refactor "Material page" #610
  src/pages/materials/materials.js
  src/pages/materials/materials.style.js
  src/pages/materials/slider/index.js
  src/pages/materials/slider/slider.js
  src/pages/materials/slider/slider.styles.js
  src/redux/pattern/pattern.operations.js
Labels: FrontEnd, refactoring

#641 added checker for banned users
  src/configs/index.js
  src/configs/routes.js
  src/pages/login/login.js
  src/redux/cart/cart.sagas.js
  src/redux/chat/chat.sagas.js
  src/redux/comments/comments.sagas.js
  src/redux/order/order.sagas.js
  src/redux/user/user.actions.js
  src/redux/user/user.reducer.js
  src/redux/user/user.sagas.js
  src/redux/user/user.types.js
  src/translations/user.translations.js
  src/utils/is-user-blocked-checker.js
Labels: FrontEnd

#637 Hotfix/589
  src/components/modal/modal.js
  src/components/number-input/number-input.js
  src/containers/cart-header/cart-header.js
  src/containers/cart-header/cart-header.styles.js
  src/containers/header-profile/header-profile.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/cart-item/cart-item.styles.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/order/delivery-type/delivery-type.js
  src/containers/orders/order/order-table/order-table.js
  src/pages/thanks-page/thanks-page.js
  src/redux/cart/cart.actions.js
  src/redux/cart/cart.operations.js
  src/redux/cart/cart.reducer.js
  src/redux/cart/cart.sagas.js
  src/redux/cart/cart.types.js
  src/translations/cart.translations.js
  src/translations/modal.translations.js
  src/utils/cart.js
Labels: FrontEnd, refactoring
