Repository ita-social-projects/horondi_client_fe, pull requests merged in 2021-03, with the labels that each got.

#586 implement "thank you for order" page
  src/configs/routes.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/checkout/checkout-form/delivery/self-pickup/self-pickup.styles.js
  src/containers/checkout/checkout.js
  src/pages/thanks-page/order-data/index.js
  src/pages/thanks-page/order-data/order-data.js
  src/pages/thanks-page/order-data/order-data.styles.js
  src/pages/thanks-page/order-data/order-item-card/index.js
  src/pages/thanks-page/order-data/order-item-card/order-item-card.js
  src/pages/thanks-page/order-data/order-item-card/order-item-card.styles.js
  src/pages/thanks-page/thanks-page.js
  src/pages/thanks-page/thanks-page.styles.js
  src/redux/cart/cart.sagas.js
  src/redux/order/order.actions.js
  src/redux/order/order.operations.js
  src/redux/order/order.sagas.js
  src/redux/order/order.types.js
  src/services/local-storage.service.js
  src/translations/thanks-page.translations.js
  src/utils/order.js
  src/utils/thank-you.js
Labels: FrontEnd, Task

#592 Added unit tests for UkrPost requests on checkout, redux Tests/581 #581
  src/redux/checkout/checkout.types.js
  src/redux/checkout/tests/checkout.actions.test.js
  src/redux/checkout/tests/checkout.reducer.test.js
  src/redux/checkout/tests/checkout.sagas.test.js
  src/redux/checkout/tests/checkout.variables.js
Labels: FrontEnd, test

#597 Bugfix/596
  src/pages/home/categories-list/category-item/category-item.style.js
  src/pages/home/our-looks/our-looks.js
Labels: FrontEnd, refactoring

#598 fix image reflection
  src/pages/home/our-looks/our-looks.js
Labels: refactoring

#591 constructor redux tests/583
  src/redux/images-constructor/constructor-basic/tests/constructor-basic.actions.test.js
  src/redux/images-constructor/constructor-basic/tests/constructor-basic.reducer.test.js
  src/redux/images-constructor/constructor-basic/tests/constructor-basic.sagas.test.js
  src/redux/images-constructor/constructor-bottom/tests/constructor-bottom.actions.test.js
  src/redux/images-constructor/constructor-bottom/tests/constructor-bottom.reducer.test.js
  src/redux/images-constructor/constructor-bottom/tests/constructor-bottom.sagas.test.js
  src/redux/images-constructor/constructor-front-pocket/tests/constructor-front-pocket.actions.test.js
  src/redux/images-constructor/constructor-front-pocket/tests/constructor-front-pocket.reducer.test.js
  src/redux/images-constructor/constructor-front-pocket/tests/constructor-front-pocket.sagas.test.js
  src/redux/images-constructor/constructor-model/tests/constructor-model.actions.test.js
  src/redux/images-constructor/constructor-model/tests/constructor-model.reducer.test.js
  src/redux/images-constructor/constructor-model/tests/constructor-model.sagas.test.js
  src/redux/images-constructor/constructor-pattern/tests/constructor-pattern.actions.test.js
  src/redux/images-constructor/constructor-pattern/tests/constructor-pattern.reducer.test.js
  src/redux/images-constructor/constructor-pattern/tests/constructor-pattern.sagas.test.js
  src/redux/images-constructor/constructor.variables.js
Labels: FrontEnd, test

#593 Bugfix/543
  package-lock.json
  src/components/app/app.js
  src/configs/routes.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/pages/product-details/comments/comments.styles.js
  src/pages/product-details/detail/detail.styles.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-details.styles.js
  src/pages/product-details/product-features/index.js
  src/pages/product-details/product-features/product-features.js
  src/pages/product-details/product-features/product-features.styles.js
  src/pages/product-details/product-images/product-images.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/similar-products/selector.js
  src/pages/product-details/similar-products/similar-products.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-page.js
  src/redux/cart/cart.reducer.js
  src/redux/cart/cart.sagas.js
  src/redux/checkout/checkout.reducer.js
  src/redux/comments/comments.operations.js
  src/redux/products/products.operations.js
  src/redux/products/products.reducer.js
  src/redux/products/products.sagas.js
  src/redux/products/tests/products.reducer.test.js
  src/redux/selectors/multiple.selectors.js
  src/routes/routes.js
  src/translations/product-details.translations.js
  src/utils/currency.js
  src/utils/priceCalculating.js
  src/utils/productDetails.js
Labels: FrontEnd, bug, refactoring

#604 fix constructor image jump
  src/pages/images-constructor/hooks.js
  src/pages/images-constructor/images-constructor.js
Labels: bug

#606 Feature/578
  src/components/number-input/number-input.js
  src/components/number-input/number-input.styles.js
  src/const/types-consts.js
  src/containers/cart-header/cart-header.js
  src/containers/header-profile/header-profile.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/order/order-table/order-table.js
  src/pages/cart/cart.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-images/product-images.js
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/similar-products/similar-products.js
  src/pages/thanks-page/order-data/order-item-card/order-item-card.styles.js
  src/redux/cart/cart.actions.js
  src/redux/cart/cart.operations.js
  src/redux/cart/cart.reducer.js
  src/redux/cart/cart.sagas.js
  src/redux/cart/cart.types.js
  src/redux/cart/tests/cart.reducer.test.js
  src/redux/products/products.reducer.js
  src/redux/root.saga.js
  src/redux/selectors/multiple.selectors.js
  src/redux/user/user.operations.js
  src/redux/user/user.sagas.js
  src/services/local-storage.service.js
  src/utils/checkout.js
  src/utils/priceCalculating.js
  src/utils/productDetails.js
Labels: FrontEnd

#601 Implement payment system
  package-lock.json
  package.json
  src/configs/routes.js
  src/const/currency.js
  src/containers/cart-header/cart-header.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout.js
  src/containers/header-profile/header-profile.js
  src/pages/thanks-page/order-data/order-data.js
  src/pages/thanks-page/thanks-page.js
  src/pages/thanks-page/thanks-page.styles.js
  src/redux/checkout/checkout.actions.js
  src/redux/checkout/checkout.operations.js
  src/redux/checkout/checkout.reducer.js
  src/redux/checkout/checkout.sagas.js
  src/redux/checkout/checkout.types.js
  src/redux/order/order.actions.js
  src/redux/order/order.operations.js
  src/redux/order/order.reducer.js
  src/redux/order/order.sagas.js
  src/redux/order/order.types.js
  src/redux/selectors/multiple.selectors.js
  src/routes/routes.js
  src/services/local-storage.service.js
  src/translations/thanks-page.translations.js
  src/utils/checkout.js
  src/utils/order.js
  src/utils/priceCalculating.js
  src/utils/thank-you.js
Labels: FrontEnd, Task

#627 added mergeImages module
  package-lock.json
  package.json
  src/pages/images-constructor/images-constructor.js
Labels: FrontEnd
