Repository ita-social-projects/horondi_client_fe, pull requests merged in 2021-07, with the labels that each got.

#766 Refactoring contacts in footer - Fix/683
  src/configs/index.js
  src/containers/footer-lists/footer-lists.js
  src/pages/register/register-from/register-form.js
  src/translations/footer.translations.js
  src/translations/user.translations.js
Labels: FrontEnd

#787 Tests for user actions/reducer/sagas #744
  src/redux/user/tests/user.actions.test.js
  src/redux/user/tests/user.mocks.js
  src/redux/user/tests/user.reducer.test.js
  src/redux/user/tests/user.sagas.test.js
Labels: FrontEnd, test

#780 Fix formRegExp for password
  src/configs/index.js
Labels: FrontEnd, bug

#805 (SP:2)Fix eslint errors #779
  src/pages/product-list-page/count-per-page/count-per-page.js
  src/pages/product-list-page/product-list-page.js
Labels: FrontEnd, bug, eslint

#798 Modified active-messenger component, fix mutation, added tests
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/chat/active-messenger/tests/active-messenger.test.js
  src/redux/chat/chat.operations.js
  src/translations/chat.translation.js
Labels: FrontEnd, bug

#802 Bugfix/663 Password recovery
  src/configs/index.js
  src/pages/new-password/new-password.js
  src/redux/user/user.operations.js
Labels: FrontEnd, bug

#806 fixed semi rule
  .eslintrc
Labels: FrontEnd, devops

#829 Feature/821 Refactor "Create by yourself" page
  src/components/modal/modal.js
  src/components/modal/modal.styles.js
  src/pages/images-constructor/constructor-sumbit/constructor-submit.js
  src/pages/images-constructor/constructor-sumbit/constructor-submit.styles.js
  src/pages/images-constructor/constructor-sumbit/index.js
  src/pages/images-constructor/hooks.js
  src/pages/images-constructor/images-constructor.js
  src/pages/images-constructor/images-constructor.style.js
  src/redux/images-constructor/constructor-model/constructor-model.operations.js
  src/redux/images-constructor/constructor-size/constructor-size.actions.js
  src/redux/images-constructor/constructor-size/constructor-size.operations.js
  src/redux/images-constructor/constructor-size/constructor-size.reducer.js
  src/redux/images-constructor/constructor-size/constructor-size.sagas.js
  src/redux/images-constructor/constructor-size/constructor-size.types.js
  src/redux/images-constructor/constructor-size/tests/constructor-size.actions.test.js
  src/redux/images-constructor/constructor-size/tests/constructor-size.reducer.test.js
  src/redux/images-constructor/constructor-size/tests/constructor-size.sagas.test.js
  src/redux/images-constructor/constructor.reducer.js
  src/redux/images-constructor/constructor.sagas.js
  src/redux/images-constructor/constructor.variables.js
  src/redux/selectors/multiple.selectors.js
  src/translations/constructor.translations.js
  src/utils/constructor.js
Labels: FrontEnd
