Repository ita-social-projects/horondi_client_fe, pull requests merged in 2021-10, with the labels that each got.

#958 954/Added a few css changes
  src/pages/register/register-from/register-form.styles.js
Labels: bug, UI, FrontEnd

#967 1082/Comment text color
  src/pages/product-details/comments/comments.styles.js
Labels: bug, UI, FrontEnd

#963 bugfix/726/new fix button style
  src/pages/news/news-item/news-item.style.js
Labels: FrontEnd

#960 Add in password functionality that allow to contain special characters
  src/configs/index.js
Labels: bug, FrontEnd, team1

#957 949/refactoring/refactor cart page
  public/images/cart/cart-dark-theme-img.png
  public/images/cart/cart-light-theme-img.png
  public/images/cart/empty-cart-black-theme-image.png
  public/images/cart/empty-cart-light-theme-image.png
  src/components/number-input/number-input.js
  src/configs/index.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/cart-item/cart-item.styles.js
  src/containers/orders/cart/cart-item/tests/__snapshots__/cart-item.test.js.snap
  src/containers/orders/cart/cart-item/tests/cart-item.test.js
  src/containers/orders/cart/cart-item/tests/cart-item.variables.js
  src/containers/orders/cart/empty-cart/tests/__snapshots__/empty-cart.test.js.snap
  src/containers/orders/cart/empty-cart/tests/empty-cart.test.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/containers/orders/cart/filled-cart/tests/__snapshots__/filled-cart.test.js.snap
  src/containers/orders/cart/filled-cart/tests/filled-cart.test.js
  src/containers/orders/cart/path-back/path-back.js
  src/containers/orders/cart/path-back/path-back.styles.js
  src/containers/orders/cart/path-back/tests/__snapshots__/path-back.test.js.snap
  src/containers/orders/cart/path-back/tests/path-back.test.js
  src/containers/orders/order/empty-order/empty-order.js
  src/containers/orders/order/empty-order/empty-order.styles.js
  src/containers/orders/order/empty-order/tests/__snapshots__/empty-order.test.js.snap
  src/containers/orders/order/empty-order/tests/empty-order.test.js
  src/containers/orders/order/order-table/order-table.js
  src/containers/orders/order/order-table/order-table.styles.js
  src/containers/orders/order/order-table/tests/__snapshots__/order-table.test.js.snap
  src/containers/orders/order/order-table/tests/order-table.test.js
  src/pages/cart/cart.styles.js
  src/pages/cart/tests/__snapshots__/cart-page.test.js.snap
  src/pages/cart/tests/cart-page.test.js
  src/pages/product-details/product-details.js
  src/redux/cart/cart.actions.js
  src/redux/cart/cart.operations.js
  src/redux/cart/cart.sagas.js
  src/redux/cart/cart.types.js
  src/redux/cart/tests/cart.actions.test.js
  src/redux/cart/tests/cart.sagas.test.js
  src/redux/products/products.reducer.js
  src/redux/user/user.operations.js
  src/translations/cart.translations.js
  src/utils/changeCartItemSizeHandler.js
  src/utils/changeCartItemSizeHandler.test.js
Labels: refactoring, FrontEnd, team3

#966 Install React I 18 Next and refactor login page
  package.json
  src/containers/language/language-component.js
  src/i18n.js
  src/index.js
  src/locales/en/index.js
  src/locales/en/login.json
  src/locales/index.js
  src/locales/ua/index.js
  src/locales/ua/login.json
  src/pages/login/login.js
Labels: FrontEnd, team2

#944 changed no-console rule
  .eslintrc
  src/containers/footer-lists/tests/footer-lists.test.js
  src/pages/home/categories-list/tests/categories-list.test.js
  src/serviceWorker.js
Labels: FrontEnd, eslint, team3

#1009 976/refactor/home internalization
  src/components/model-item/model-item.js
  src/components/model-item/tests/model-item.spec.js
  src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.js
  src/containers/search-bar-list/search-bar-list-item/tests/search-bar-list-item.spec.js
  src/containers/sidebar/tests/__snapshots__/sidebar.test.js.snap
  src/locales/en/common.json
  src/locales/en/home.json
  src/locales/en/index.js
  src/locales/ua/common.json
  src/locales/ua/home.json
  src/locales/ua/index.js
  src/pages/home/categories-list/category-item/category-item.js
  src/pages/home/categories-list/category-item/tests/category-item.spec.js
  src/pages/home/contructor-preview/constructor-preview.js
  src/pages/home/contructor-preview/tests/constructor-preview.spec.js
  src/pages/home/models-list/models-list.js
  src/pages/home/models-list/tests/models-list.spec.js
  src/pages/home/slider/slider-home-page.js
  src/pages/home/slider/tests/slider.spec.js
  src/translations/homepage.translations.js
Labels: FrontEnd

#1025 996/refactoring Refactored redux hooks homepage-slider
  src/locales/en/index.js
  src/locales/ua/index.js
  src/pages/home/home.js
  src/pages/home/operations/slider/slider.queries.js
  src/pages/home/slider/slider-home-page.js
  src/pages/home/slider/tests/__snapshots__/slider-home-page.test.js.snap
  src/pages/home/slider/tests/slider-home-page.test.js
  src/pages/home/slider/tests/slider.spec.js
  src/redux/homepage-slider/homepage-slider.actions.js
  src/redux/homepage-slider/homepage-slider.operations.js
  src/redux/homepage-slider/homepage-slider.reducer.js
  src/redux/homepage-slider/homepage-slider.sagas.js
  src/redux/homepage-slider/homepage-slider.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
Labels: refactoring, FrontEnd

#965 1083/comment label visibility
  src/pages/product-details/comments/comments.styles.js
Labels: bug, UI, FrontEnd

#1012 Refactor confirmation, contacts, error page
  src/locales/en/confirmation.json
  src/locales/en/contacts.json
  src/locales/en/errorPage.json
  src/locales/en/index.js
  src/locales/ua/confirmation.json
  src/locales/ua/contacts.json
  src/locales/ua/errorPage.json
  src/locales/ua/index.js
  src/pages/confirmation/confirmation.js
  src/pages/confirmation/tests/confirmation-page.test.js
  src/pages/contacts/contacts.js
  src/pages/contacts/tests/contacts-page.test.js
  src/pages/error-page/error-page.js
  src/pages/error-page/tests/error-page.test.js
Labels: refactoring, FrontEnd

#1034 997/refactoring Refactored home-page-looks redux part
  src/pages/home/contructor-preview/constructor-preview.js
  src/pages/home/home.js
  src/pages/home/operations/our-looks/our-looks.queries.js
  src/pages/home/our-looks/our-looks.js
  src/pages/home/our-looks/tests/__snapshots__/our-looks.spec.js.snap
  src/pages/home/our-looks/tests/our-looks.spec.js
  src/redux/home-page-looks/home-page-looks.actions.js
  src/redux/home-page-looks/home-page-looks.operations.js
  src/redux/home-page-looks/home-page-looks.reducer.js
  src/redux/home-page-looks/home-page-looks.sagas.js
  src/redux/home-page-looks/home-page-looks.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
Labels: refactoring, FrontEnd

#1036 Add 12 team to readme
  README.md
Labels: FrontEnd

#1007 Refactor product list page
  src/configs/index.js
  src/locales/en/common.json
  src/locales/en/index.js
  src/locales/en/product-list-page.json
  src/locales/ua/common.json
  src/locales/ua/index.js
  src/locales/ua/product-list-page.json
  src/pages/product-list-page/count-per-page/count-per-page.js
  src/pages/product-list-page/product-list-filter/hot-item-filter/hot-item-filter.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-filter/product-list-filter.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-sort/product-sort.js
  src/pages/product-list-page/tests/count-per-page.spec.js
  src/pages/product-list-page/tests/hot-items-filter.spec.js
  src/pages/product-list-page/tests/price-filter.spec.js
  src/pages/product-list-page/tests/product-list-filter.spec.js
  src/pages/product-list-page/tests/product-list-item.spec.js
  src/pages/product-list-page/tests/product-list-page.spec.js
  src/pages/product-list-page/tests/product-sort.spec.js
  src/translations/product-list.translations.js
Labels: refactoring, FrontEnd

#1037 1022/refactor/containers internalization
  src/containers/products-filters-container/products-filters-container.js
  src/containers/products-filters-container/tests/product-filter-container.spec.js
  src/containers/search-bar-list/search-bar-list.js
  src/containers/search-bar-list/tests/search-bar-list.spec.js
  src/containers/search-bar/search-bar.js
  src/containers/search-bar/tests/search-bar.spec.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/containers/sidebar/sidebar-item/tests/sidebar-item.spec.js
  src/containers/sidebar/sidebar.js
  src/containers/sidebar/tests/sidebar.test.js
  src/locales/en/index.js
  src/locales/en/searchBar.json
  src/locales/en/sidebar.json
  src/locales/ua/index.js
  src/locales/ua/searchBar.json
  src/locales/ua/sidebar.json
  src/translations/product-list.translations.js
  src/translations/sidebar.translations.js
Labels: refactoring, FrontEnd

#1071 fixed map displaying for new back-end part
  src/configs/index.js
  src/pages/contacts/contacts.js
  src/redux/contacts/contacts.operations.js
Labels: FrontEnd

#1060 refactor/1021/containers-orders-order.history
  src/components/modal/modal.js
  src/configs/index.js
  src/containers/orders/order-history/empty-order-history/empty-order-history.js
  src/containers/orders/order-history/empty-order-history/tests/empty-order-history.spec.js
  src/containers/orders/order-history/order-history-order-item/order-history-order-item.js
  src/containers/orders/order-history/order-history-order-item/tests/order-history-order-item.spec.js
  src/containers/orders/order-history/order-history-order/order-history-order.js
  src/containers/orders/order-history/order-history-order/tests/order-history-order.spec.js
  src/containers/orders/order-history/order-history-pagination/tests/order-history-pagination.spec.js
  src/containers/orders/order-history/order-history-table/order-history-table.js
  src/containers/orders/order-history/order-history-table/tests/order-history-table.spec.js
  src/containers/orders/order/order-table/order-table.js
  src/containers/orders/order/order-table/tests/__snapshots__/order-table.test.js.snap
  src/containers/orders/order/order-table/tests/order-table.test.js
  src/locales/en/cart.json
  src/locales/en/error.json
  src/locales/en/order-history.json
  src/locales/ua/cart.json
  src/locales/ua/error.json
  src/locales/ua/order-history.json
  src/locales/ua/profilePage.json
  src/locales/ua/register.json
  src/pages/login/login.js
  src/pages/new-password/new-password.js
  src/pages/order-history/order-history.js
  src/pages/profile-page/profile-page.js
  src/pages/recovery/recovery.js
  src/pages/register/register-from/register-form.js
  src/translations/cart.translations.js
  src/translations/modal.translations.js
  src/translations/order.translations.js
  src/validators/chekout.js
  src/validators/login.js
  src/validators/register.js
Labels: refactoring, FrontEnd

#1069 1002/refactor/redux-to-hooks_categories
  src/components/app/app.js
  src/containers/footer-lists/footer-lists.js
  src/containers/footer-lists/tests/footer-lists.spec.js
  src/containers/footer-lists/tests/footer-lists.test.js
  src/containers/orders/cart/filled-cart/tests/__snapshots__/filled-cart.spec.js.snap
  src/context/categories/categories-context.js
  src/context/categories/constants.js
  src/pages/home/categories-list/categories-list.js
  src/pages/home/categories-list/tests/categories-list.spec.js
  src/pages/home/categories-list/tests/categories-list.test.js
  src/pages/home/home.js
  src/redux/categories/categories.actions.js
  src/redux/categories/categories.operations.js
  src/redux/categories/categories.reducer.js
  src/redux/categories/categories.sagas.js
  src/redux/categories/categories.types.js
  src/redux/categories/tests/categories.actions.test.js
  src/redux/categories/tests/categories.reducer.test.js
  src/redux/categories/tests/categories.sagas.test.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/routes/routes.js
Labels: refactoring, FrontEnd

#1095 add .env.example to .gitignore
  .gitignore
Labels: refactoring

#1110 refactoring/1109/models-list . refactor test. Delete all trash
  src/pages/home/models-list/tests/models-list.spec.js
Labels: refactoring, FrontEnd
