Repository ita-social-projects/horondi_client_fe, pull requests merged in 2021-12, with the labels that each got.

#1375 test/1351/footer-links-test
  src/containers/footer-lists/tests/footer-lists.spec.js
  src/tests/unit/containers/footer-lists/footer-lists.spec.js
Labels: test

#1445 Rework/1437/rework main slider
  src/pages/home/home.styles.js
  src/pages/home/slider/slider-home-page.js
  src/pages/home/slider/slider-home-page.style.js
Labels: FrontEnd

#1446 [HOTFIX] Rework/1437/rework main slider
  src/pages/home/slider/slider-home-page.js
Labels: bug

#1447 Redesign/1359/newspage
  src/components/app/app.styles.js
  src/locales/en/buttons.json
  src/locales/ua/buttons.json
  src/pages/news/news-item/news-item.js
  src/pages/news/news-item/news-item.style.js
  src/pages/news/news-page/news-page.style.js
Labels: FrontEnd, redesign

#1452 added background-color rule. Changed dark theme color in app.pallete
  src/components/app/app-theme/theme.js
  src/routes/routes.style.js
Labels: FrontEnd, redesign

#1454 Bugfix/1453/change news bg
  src/pages/news/news-item/news-item.style.js
Labels: FrontEnd, redesign

#1455 Fixed product image display when opening it
  src/pages/product-details/product-images/product-images.js
Labels: bug, FrontEnd

#1456 Redesign/1441/redesign comments for product
  src/locales/en/common.json
  src/locales/ua/common.json
  src/pages/product-details/comments/comments-item/comments-item.js
  src/pages/product-details/comments/comments-item/comments-item.styles.js
  src/pages/product-details/comments/comments-item/reply-comments-item/reply-comments-item.js
  src/pages/product-details/comments/comments-item/reply-comments-item/reply-comments-item.styles.js
  src/pages/product-details/comments/comments-item/reply-form/reply-form.js
  src/pages/product-details/comments/comments-item/reply-form/reply-form.styles.js
  src/pages/product-details/comments/comments-item/reply-form/tests/reply-form.test.js
  src/pages/product-details/comments/comments.js
  src/pages/product-details/comments/comments.styles.js
Labels: FrontEnd, redesign

#1459 Bugfix/1125/sort_items_in_productlist
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-sort/product-sort.js
Labels: bug, FrontEnd, Functional

#1462 write tests for register form
  src/tests/unit/pages/register/register-form.spec.js
Labels: FrontEnd, test

#1463 Add translations
  src/components/modal/modal.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/operations/order.queries.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/containers/orders/order/your-order/order-item/order-item.js
  src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.js
  src/pages/order-history/operations/order-history.queries.js
  src/pages/product-details/operations/product-details.queries.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
  src/pages/product-details/similar-products/similar-products-item/tests/__snapshots__/similar-products-item.test.js.snap
  src/pages/product-details/similar-products/similar-products.js
  src/pages/product-list-page/operations/product-list.queries.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
  src/pages/wishlist/operations/wishlist.queries.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js
  src/tests/unit/components/order-history-list-item/order-history-item-product.variables.js
  src/tests/unit/components/your-order/your-order.spec.js
Labels: refactoring, FrontEnd

#1469 Fix background on Login page and Register Page
  src/pages/login/login.styles.js
  src/pages/register/register.styles.js
Labels: bug, FrontEnd

#1458 Console erros/catalog
  src/pages/product-details/product-details.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
Labels: FrontEnd, clean console

#1464 Fix/1443/color pattern
  src/images/colors/black.jpg
  src/images/colors/blue.jpg
  src/images/colors/brown.jpg
  src/images/colors/coffee.jpg
  src/images/colors/gray.jpg
  src/images/colors/gray_2.jpg
  src/images/colors/green.jpg
  src/images/colors/pink.jpg
  src/images/colors/red.jpg
  src/images/colors/yellow.jpg
  src/images/colors/yellow_2.jpg
  src/pages/product-details/operations/product-details.queries.js
  src/pages/product-details/product-info/colors.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-info/product-info.styles.js
  src/pages/product-details/product-info/tests/product-info.test.js
Labels: FrontEnd

#1472 fixed error text and margin in comments and reply form
  src/pages/product-details/comments/comments-item/reply-form/reply-form.js
  src/pages/product-details/comments/comments-item/reply-form/reply-form.styles.js
  src/pages/product-details/comments/comments.js
  src/pages/product-details/comments/comments.styles.js
Labels: bug, FrontEnd

#1474 Refactor/1461/sorting on product list
  src/pages/product-list-page/product-sort/product-sort.js
  src/pages/product-list-page/product-sort/product-sort.styles.js
  src/pages/product-list-page/tests/product-list-page.spec.js
  src/pages/product-list-page/tests/product-sort.spec.js
Labels: refactoring, FrontEnd

#1478 Add plug to falling history page
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/containers/orders/order-history/order-history-item/order-history-item.js
  src/tests/unit/components/order-history-item/order-history-item.spec.js
  src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js
  src/tests/unit/components/order-history-list-item/order-history-item-product.variables.js
Labels: refactoring, FrontEnd

#1480 fix corousel design
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/pages/home/categories-list/category-item/category-item.js
  src/pages/home/categories-list/category-item/category-item.style.js
  src/pages/home/categories-list/category-item/tests/category-item.spec.js
Labels: bug, refactoring, FrontEnd

#1479 Fixed product images
  src/pages/product-details/product-images/product-images.js
Labels: bug, FrontEnd

#1486 Fixed materials console warnings
  src/pages/materials/materials.js
Labels: FrontEnd, clean console

#1488 Fix bug with wishlist and cart headers margin
  src/containers/cart-header/cart-header.styles.js
  src/containers/header-right-bar/header-right-bar.styles.js
  src/containers/wishlist-header/wishlist-header.styles.js
Labels: bug, FrontEnd

#1487 (SP: 0.5) refactor/14518/make_open_sans_main_font_family
  src/components/modal/modal.styles.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/currency/currency.styles.js
  src/containers/language/language.styles.js
  src/containers/orders/cart/cart-item/cart-item.styles.js
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/containers/orders/cart/path-back/path-back.styles.js
  src/containers/orders/order/empty-order/empty-order.styles.js
  src/containers/orders/order/order-table/order-table.styles.js
  src/containers/search-bar/search-bar.styles.js
  src/pages/home/categories-list/categories-list.style.js
  src/pages/home/categories-list/category-item/category-item.style.js
  src/pages/home/contructor-preview/constructor-preview.style.js
  src/pages/home/slider/slider-home-page.style.js
  src/pages/login/login.styles.js
  src/pages/news/news-detail/news-detail.style.js
  src/pages/news/news-item/news-item.style.js
  src/pages/product-details/comments/comments.styles.js
  src/pages/product-list-page/product-list-page.styles.js
  src/pages/profile-page/profile-page.styles.js
  src/pages/register/register-from/register-form.styles.js
  src/pages/thanks-page/thanks-card/thanks-card.styles.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.styles.js
  src/pages/wishlist/wishlist-item/wishlist-item.styles.js
Labels: refactoring, FrontEnd

#1489 Redesign/1343/questions/answers
  src/components/accordion/accordions.js
  src/components/accordion/accordions.style.js
  src/configs/routes.js
  src/containers/social-links/const.js
  src/locales/en/common.json
  src/locales/en/footer.json
  src/locales/ua/common.json
  src/locales/ua/footer.json
  src/pages/answers-questions-page/answers-questions-page.js
  src/pages/answers-questions-page/answers-questions-page.style.js
  src/pages/answers-questions-page/index.js
  src/pages/answers-questions-page/operations/answers-questions.queries.js
  src/pages/answers-questions-page/tests/answers-questions-page.test.js
  src/pages/answers-questions-page/tests/answers-questions.variables.js
  src/pages/business-page/business-page.js
  src/pages/images-constructor/images-constructor.js
  src/routes/routes.js
Labels: FrontEnd

#1467 Redesign/1449/sidebar redesign
  src/components/dropdown/dropdown.js
  src/components/dropdown/dropdown.styles.js
  src/containers/cart-header/cart-header.styles.js
  src/containers/currency/currency.styles.js
  src/containers/language/language.styles.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/containers/sidebar/sidebar-item/sidebar-items.style.js
  src/containers/sidebar/sidebar.js
  src/containers/sidebar/sidebar.styles.js
  src/containers/sidebar/tests/__snapshots__/sidebar.test.js.snap
  src/containers/sidemenu-right-bar/sidemenu-right-bar.js
  src/containers/sidemenu-right-bar/sidemenu-right-bar.styles.js
  src/containers/social-links/social-links.js
  src/containers/social-links/social-links.styles.js
  src/tests/unit/components/sidebar/sidebar.spec.js
  src/tests/unit/components/sidemenu-right-bar/sidemenu-right-bar.spec.js
Labels: FrontEnd, redesign

#1491 bugfix/1138/fix error message
  src/containers/search-bar-list/search-bar-list.js
  src/containers/search-bar-list/search-bar-list.styles.js
Labels: bug, FrontEnd

#1490 bugfix/1254/contacts and catalogs url
  src/containers/footer-lists/footer-lists.js
Labels: bug, FrontEnd

#1495 bugfix/1493/fixed phone and mail
  src/pages/contacts/contacts.js
  src/pages/contacts/contacts.styles.js
Labels: bug, FrontEnd

#1499 Fix models translation in filters
  src/locales/en/common.json
  src/locales/ua/common.json
Labels: bug, FrontEnd

#1501 Fix title highlight in Catalog
  src/pages/product-list-page/product-list-page.styles.js
Labels: bug, FrontEnd

#1473 Feature/1387/facebookauth
  package-lock.json
  package.json
  src/components/facebook-log-in-btn/facebook-button.js
  src/components/facebook-log-in-btn/index.js
  src/components/google-log-in-btn/google-button.js
  src/components/google-log-in-btn/google-button.styles.js
  src/configs/index.js
  src/images/facebook.png
  src/images/google.png
  src/pages/login/login.js
  src/redux/user/tests/user.actions.spec.js
  src/redux/user/tests/user.sagas.spec.js
  src/redux/user/user.actions.js
  src/redux/user/user.operations.js
  src/redux/user/user.sagas.js
  src/redux/user/user.types.js
  src/tests/unit/pages/login/login.spec.js
Labels: FrontEnd, dependencies, Log in, feature

#1510 Bugfix/1504/shopping cart fix
  src/configs/index.js
  src/redux/user/user.sagas.js
Labels: bug, FrontEnd

#1497 (SP:0.5)fix links for catalog on main page
  src/components/model-item/model-item.js
  src/pages/home/models-list/models-list.js
Labels: FrontEnd

#1509 bugfix/1136/fixed seach bar in catalog
  sonar-project.properties
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/containers/search-bar/search-bar.js
  src/containers/search-bar/search-bar.styles.js
Labels: bug, FrontEnd

#1484 1483/React update
  package-lock.json
  package.json
  src/containers/checkout/checkout-form/delivery-type/tests/__snapshots__/delivery-type.test.js.snap
  src/containers/checkout/checkout-form/delivery-type/tests/delivery-type.test.js
  src/pages/new-password/tests/new-password.test.js
  src/pages/product-details/product-images/tests/product-images.spec.js
  src/setupTests.js
Labels: FrontEnd, dependencies

#1513 Create pagination for news page
  src/containers/orders/order-history/order-history-pagination/order-history-pagination.style.js
  src/index.css
  src/pages/news/news-page/constants.js
  src/pages/news/news-page/news-page.js
  src/pages/news/news-page/test/news-page.spec.js
  src/pages/news/operations/news-queries.js
Labels: FrontEnd

#1494 (SP: 1) Rework models element on main Page.
  src/components/model-item/model-item.js
  src/components/model-item/model-item.style.js
  src/locales/en/home.json
  src/locales/ua/home.json
  src/pages/home/models-list/models-list.js
  src/pages/home/models-list/models-list.style.js
Labels: FrontEnd

#1514 (SP:0.5)Fix responsive design of "News" page #838
  src/pages/news/news-item/news-item.style.js
  src/pages/news/news-page/news-page.style.js
Labels: FrontEnd, redesign

#1481 Add functionality to price text boxes
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/tests/price-filter.spec.js
Labels: bug, FrontEnd, Functional

#1508 Fix console warning
  src/containers/header-profile/header-profile.js
Labels: FrontEnd, clean console

#1518 Hotfix/fix clear local storage
  src/hooks/use-cart.js
Labels: bug, FrontEnd

#1520 Bugfix/708/price filter
  src/pages/product-list-page/product-list-item/product-list-item.js
Labels: bug, Functional

#1505 Redesign/1476/edit products element on main page
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/pages/home/categories-list/categories-carousel.css
  src/pages/home/categories-list/categories-list.js
  src/pages/home/categories-list/categories-list.style.js
  src/pages/home/categories-list/category-item/category-item.js
  src/pages/home/categories-list/category-item/category-item.style.js
Labels: FrontEnd, redesign

#1517 Refactor/1515/refactor_checkout
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/utils/checkout.js
  src/utils/checkout.spec.js
Labels: refactoring, FrontEnd

#1521 fix/788/ChatNameField
  src/containers/chat/active-messenger/active-messenger.js
  src/utils/handle-active-massenger.js
Labels: FrontEnd

#1465 redesign product page
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/images/profile-icons.js
  src/locales/en/product.json
  src/locales/ua/product.json
  src/pages/product-details/comments/comments.js
  src/pages/product-details/constants.js
  src/pages/product-details/operations/product-details.queries.js
  src/pages/product-details/product-description/index.js
  src/pages/product-details/product-description/product-description.js
  src/pages/product-details/product-description/product-description.styles.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-details.styles.js
  src/pages/product-details/product-images/product-images.js
  src/pages/product-details/product-images/product-images.styles.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-info/product-info.styles.js
  src/pages/product-details/product-info/tests/product-info.test.js
  src/pages/product-details/product-info/tests/product-info.variables.js
  src/pages/product-details/product-path/product-path.js
  src/pages/product-details/product-path/product-path.styles.js
  src/pages/product-details/product-path/product-path.test.js
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-details/product-sizes/product-sizes.styles.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/product-submit/product-submit.styles.js
  src/pages/product-details/product-submit/tests/product-submit.test.js
  src/tests/unit/pages/product-details/product-description/product-description.spec.js
  src/tests/unit/pages/product-details/product-description/product-description.variables.js
Labels: FrontEnd, redesign

#1524 (SP:0.5) Fix 2nd slider on main page
  src/pages/home/contructor-preview/constructor-preview.style.js
Labels: FrontEnd

#1526 Redesign/1441/redesign form and modal in comments
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/images/loadMoreCommentsIcon.js
  src/locales/en/common.json
  src/locales/en/product.json
  src/locales/ua/common.json
  src/locales/ua/product.json
  src/pages/product-details/comments/comments-item/comment-dialog/comment-dialog.js
  src/pages/product-details/comments/comments-item/comment-dialog/comment-dialog.styles.js
  src/pages/product-details/comments/comments-item/comments-item.js
  src/pages/product-details/comments/comments-item/comments-item.styles.js
  src/pages/product-details/comments/comments-item/comments-title/comments-title.js
  src/pages/product-details/comments/comments-item/reply-comments-item/reply-comments-item.styles.js
  src/pages/product-details/comments/comments-item/reply-form/reply-form.js
  src/pages/product-details/comments/comments-item/reply-form/reply-form.styles.js
  src/pages/product-details/comments/comments.js
  src/pages/product-details/comments/comments.styles.js
  src/pages/product-details/constants.js
  src/pages/product-details/product-info/product-info.js
  src/tests/unit/pages/product-details/comments-title.spec.js
  src/tests/unit/pages/product-details/comments.spec.js
  src/utils/handle-comments.js
Labels: FrontEnd, redesign

#1530 fixed coundPerPage in routes in sidebar footer and categories
  src/containers/footer-lists/footer-lists.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/pages/home/categories-list/categories-list.js
Labels: bug, FrontEnd

#1528 Redesign/1448/constructor
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/cart-item/tests/cart-item.spec.js
  src/containers/orders/cart/cart-item/tests/cart-item.variables.js
  src/containers/orders/operations/getConstructorById.queries.js
  src/containers/orders/order/your-order/order-item/order-item.js
  src/hooks/use-cart.js
  src/locales/en/common.json
  src/locales/ua/common.json
  src/pages/images-constructor/constructor-sumbit/constructor-submit.js
  src/pages/images-constructor/constructor-sumbit/constructor-submit.styles.js
  src/pages/images-constructor/constructor-sumbit/tests/constructor-submit.spec.js
  src/pages/images-constructor/constructor-sumbit/tests/constructor.variables.js
  src/pages/images-constructor/images-constructor.js
  src/pages/images-constructor/images-constructor.style.js
  src/pages/images-constructor/operations/getConstructorByModel.queries.js
  src/pages/images-constructor/tests/images-constructor.spec.js
  src/pages/images-constructor/tests/images-constructor.variables.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/product-submit/tests/product-submit.test.js
  src/redux/cart/cart.sagas.js
  src/tests/unit/components/your-order/your-order.spec.js
  src/utils/checkout.js
  src/utils/productDetails.js
Labels: FrontEnd

#1542 Redesign/1529/cart component
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/components/number-input/number-input.styles.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/cart-item/cart-item.styles.js
  src/containers/orders/cart/cart-item/tests/cart-item.spec.js
  src/containers/orders/cart/cart-item/tests/cart-item.variables.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/containers/orders/cart/path-back/path-back.styles.js
  src/containers/orders/order/order-table/order-table.styles.js
  src/pages/product-details/similar-products/similar-products.js
  src/utils/currency.js
Labels: refactoring, FrontEnd, redesign

#1553 Bugfix/1536/fix styles on page and profile
  package-lock.json
  src/components/model-item/model-item.style.js
  src/components/model-item/tests/model-item.spec.js
  src/configs/routes.js
  src/containers/header-profile/header-profile.styles.js
  src/containers/social-links/social-links.styles.js
  src/locales/en/common.json
  src/locales/ua/common.json
  src/locales/ua/not-found-page.json
  src/locales/ua/profilePage.json
  src/pages/home/slider/slider-data.js
  src/pages/not-found-page/not-found-page.styles.js
  src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
  src/pages/profile-page/profile-page.styles.js
Labels: bug, good first issue, FrontEnd

#1547 Bugfix/1533/refactoring styles
  src/components/accordion/accordions.style.js
  src/index.css
  src/locales/en/common.json
  src/pages/news/news-item/news-item.js
  src/pages/news/news-item/news-item.style.js
Labels: FrontEnd

#1562 bug/1534/verified purchase icon
  src/images/verifiedPurchaseIcon.js
  src/pages/product-details/comments/comments-item/comments-item.js
  src/pages/product-details/comments/comments-item/comments-item.styles.js
  src/pages/product-details/comments/comments-item/comments-title/comments-title.js
  src/pages/product-details/comments/comments.js
  src/tests/unit/pages/product-details/comment-item.spec.js
  src/tests/unit/pages/product-details/comments-title.spec.js
  src/tests/unit/pages/product-details/comments.variables.js
Labels: bug, FrontEnd

#1565 fix checkout problem
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/cart-item/tests/cart-item.spec.js
  src/pages/cart/cart.js
  src/pages/images-constructor/constructor-sumbit/constructor-submit.js
Labels: FrontEnd

#1539 remove redux | product details
  src/pages/product-details/product-description/product-description.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-info/tests/product-info.test.js
  src/pages/product-details/product-info/tests/product-info.variables.js
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-details/product-sizes/tests/product-sizes.test.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
  src/pages/product-details/tests/product-details.spec.js
  src/tests/unit/pages/product-details/product-description/product-description.spec.js
  src/tests/unit/pages/product-details/product-description/product-description.variables.js
Labels: FrontEnd

#1572 Bugfix/1535/fix issues on product detail page
  package-lock.json
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/pages/product-details/detail/detail.styles.js
  src/pages/product-details/product-details.styles.js
  src/pages/product-details/product-images/product-images.styles.js
  src/pages/product-details/product-info/product-info.styles.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.styles.js
  src/pages/product-details/similar-products/similar-products-item/tests/similar-products-item.test.js
  src/pages/product-details/similar-products/similar-products.styles.js
Labels: FrontEnd

#1573 test for SearchBarListItem component
  src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.js
  src/containers/search-bar-list/search-bar-list-item/tests/search-bar-list-item.spec.js
  src/tests/unit/containers/search-bar-list-item/search-bar-list-item.spec.js
  src/tests/unit/containers/search-bar-list-item/search-bar-list-item.variables.js
Labels: FrontEnd, test

#1574 fix models height and responivness for mobile
  src/components/model-item/model-item.style.js
  src/pages/home/models-list/models-list.style.js
Labels: bug, FrontEnd

#1560 fix bugs with styles
  src/containers/products-filters-container/products-filters-container.styles.js
  src/pages/product-list-page/product-list-filter/hot-item-filter/hot-item-filter.js
  src/pages/product-list-page/product-list-filter/product-list-filter.styles.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/product-list-page/product-list-item/product-list-item.style.js
Labels: bug, FrontEnd
