Repository ita-social-projects/horondi_client_fe, pull requests merged in 2021-05, with the labels that each got.

#669 fixed link on home slides
  src/configs/index.js
  src/const/style-consts.js
  src/pages/home/slider/slider-home-page.js
  src/pages/news/news-detail/news-detail.js
  src/pages/news/news-item/news-item.js
  src/pages/news/news-page/news-page.js
  src/redux/news/news.operations.js
Labels: FrontEnd, bug

#673 hotfix. Response errors handling
  src/redux/user/user.sagas.js
  src/utils/client.js
Labels: FrontEnd

#671 Fix functionality with confirmation user email
  package-lock.json
  src/pages/error-page/error-page.js
  src/redux/user/user.operations.js
  src/redux/user/user.sagas.js
  src/translations/errorpage.translations.js
  src/translations/user.translations.js
  src/utils/handle-confirmation.js
Labels: FrontEnd, Task

#652 Feature/611
  .github/pull_request_template.md
  README.md
  src/components/dropdown/dropdown.js
  src/const/language.js
  src/containers/language/index.js
  src/containers/language/language-component.js
Labels: UI, bug
