Repository ita-social-projects/horondi_client_fe, pull requests merged in 2021-11, with the labels that each got.

#1165 Pattern images preload in Materials
  src/pages/materials/materials.js
  src/pages/materials/slider/slider.js
  src/pages/materials/tests/materials.spec.js
Labels: bug, FrontEnd

#1142 refactor nova post redux
  src/containers/checkout/checkout-form/delivery/nova-post/nova-post.js
  src/containers/checkout/checkout-form/delivery/nova-post/operations/nova-post.queries.js
  src/containers/checkout/checkout-form/delivery/nova-post/test/nova-post.spec.js
  src/redux/checkout/checkout.actions.js
  src/redux/checkout/checkout.operations.js
  src/redux/checkout/checkout.reducer.js
  src/redux/checkout/checkout.sagas.js
  src/redux/checkout/checkout.types.js
  src/redux/checkout/tests/checkout.actions.test.js
  src/redux/checkout/tests/checkout.reducer.test.js
  src/redux/checkout/tests/checkout.sagas.test.js
  src/redux/checkout/tests/checkout.variables.js
Labels: refactoring, FrontEnd

#1170 Refactor/1074/comments deleting actions
  src/pages/product-details/comments/comments-item/comment-dialog/comment-dialog.js
  src/pages/product-details/comments/comments-item/comment-dialog/tests/comment-dialog.test.js
  src/pages/product-details/comments/comments-item/comments-item.js
  src/pages/product-details/comments/comments-item/reply-comments-item/reply-comments-item.js
  src/pages/product-details/comments/comments-item/reply-comments-item/tests/reply-comments-item.test.js
  src/pages/product-details/comments/comments-item/reply-form/reply-form.js
  src/pages/product-details/comments/comments.js
  src/pages/product-details/comments/operations/comments.queries.js
  src/pages/product-details/product-submit/product-submit.js
Labels: FrontEnd

#1163 Fix/1124/label in comments
  src/configs/index.js
  src/locales/en/common.json
  src/locales/ua/common.json
  src/pages/product-details/comments/comments-item/reply-comments-item/reply-comments-item.js
  src/pages/product-details/comments/comments-item/reply-comments-item/tests/reply-comments-item.test.js
Labels: FrontEnd

#1158 refactoring/1157/ Refactored contacts page tests
  src/pages/contacts/contacts.js
  src/pages/contacts/operations/contacts.queries.js
  src/pages/contacts/tests/contacts-page.test.js
  src/tests/unit/pages/contacts/contacts.spec.js
  src/tests/unit/pages/contacts/contacts.variables.js
Labels: refactoring, FrontEnd

#1172 Fix tests failing
  src/pages/product-details/comments/comments-item/reply-comments-item/tests/reply-comments-item.test.js
Labels: FrontEnd

#1174 bug fix in checkout
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/const.js
  src/locales/en/checkout.json
  src/locales/ua/checkout.json
  src/utils/checkout.js
Labels: FrontEnd

#1169 refactor/1148/pattern
  src/pages/materials/materials.js
  src/pages/materials/operations/getAllPatterns.queries.js
Labels: refactoring, FrontEnd

#1177 fix error img
  src/pages/not-found-page/not-found-page.js
  src/pages/not-found-page/tests/__snapshots__/not-found-page.test.js.snap
Labels: bug, FrontEnd

#1178 Refactor/990/redux snackbar
  src/components/app/app.js
  src/containers/snackbar/snackbar.js
  src/context/snackbar-context.js
  src/pages/product-details/comments/comments-item/comment-dialog/comment-dialog.js
  src/pages/product-details/comments/comments-item/comments-item.js
  src/pages/product-details/comments/comments-item/reply-form/reply-form.js
  src/pages/product-details/comments/comments.js
  src/pages/product-details/comments/operations/comments.queries.js
  src/pages/product-details/comments/tests/comments.test.js
Labels: FrontEnd

#1159 refactoring redux ukrpost
  src/containers/checkout/checkout-form/delivery/ukrpost/operations/get-ukrpost-data.queries.js
  src/containers/checkout/checkout-form/delivery/ukrpost/tests/ukrpost.spec.js
  src/containers/checkout/checkout-form/delivery/ukrpost/ukrpost.js
  src/redux/checkout/checkout.actions.js
  src/redux/checkout/checkout.operations.js
  src/redux/checkout/checkout.reducer.js
  src/redux/checkout/checkout.sagas.js
  src/redux/checkout/checkout.types.js
  src/redux/checkout/tests/checkout.actions.test.js
  src/redux/checkout/tests/checkout.reducer.test.js
  src/redux/checkout/tests/checkout.sagas.test.js
  src/redux/checkout/tests/checkout.variables.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
Labels: refactoring, FrontEnd

#1181 hot fix currency
  src/locales/ua/checkout.json
Labels: bug, FrontEnd

#1185 fixed toast saga
  src/redux/toast/toast.sagas.js
Labels: bug, FrontEnd

#1184 fixed volume and weight disappearing from product details when size c…
  src/pages/order-history/order-history.js
  src/pages/product-details/product-details.js
Labels: bug, FrontEnd

#1171 Check and delete if unnecessary header-links and navbar-left. #1055
  src/containers/navbar-left/index.js
  src/containers/navbar-left/navbar-left.js
  src/containers/navbar-left/navbar-left.styles.js
  src/redux/header-links/header-links.actions.js
  src/redux/header-links/header-links.operations.js
  src/redux/header-links/header-links.reducer.js
  src/redux/header-links/header-links.sagas.js
  src/redux/header-links/header-links.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
Labels: FrontEnd

#1180 add translation to back-end part of data
  src/pages/business-page/business-page.js
  src/pages/business-page/operations/business-page.queries.js
  src/tests/unit/pages/business-page/business-page.spec.js
  src/tests/unit/pages/business-page/business-page.variables.js
Labels: refactoring, FrontEnd

#1190 1160/Login test refactor
  src/pages/login/login.js
  src/pages/login/tests/login-page.spec.js
  src/tests/unit/pages/login/login.spec.js
Labels: refactoring, FrontEnd, test

#1192 Bugfix/1154/fix clickable area of a leave comment button
  src/locales/en/product.json
  src/pages/product-details/comments/comments.js
  src/pages/product-details/comments/comments.styles.js
Labels: bug, FrontEnd

#1201 bugfix/1200/fixed console-errors in given components
  src/containers/orders/order-history/order-history-order/order-history-order.js
  src/containers/snackbar/snackbar.js
  src/pages/order-history/operations/order-history.queries.js
Labels: bug, FrontEnd, clean console

#1197 Login translation bug
  src/pages/login/login.js
  src/validators/login.js
Labels: bug

#1182 added translations from BE for categorie
  src/containers/footer-lists/footer-lists.js
  src/containers/sidebar/operations/burger-menu.queries.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/containers/sidebar/sidebar.js
  src/context/categories/constants.js
  src/pages/home/categories-list/categories-list.js
Labels: refactoring, FrontEnd

#1210 Fixed translations key for bussiness pages
  src/pages/business-page/business-page.js
  src/pages/business-page/operations/business-page.queries.js
  src/tests/unit/pages/business-page/business-page.variables.js
Labels: refactoring, FrontEnd

#1206 1195/Header and homepage-slider translation refactor
  src/pages/home/operations/slider/slider.queries.js
  src/pages/home/slider/slider-home-page.js
Labels: refactoring, FrontEnd

#1211 Fix translations
  src/hooks/use-translations-load.js
Labels: FrontEnd

#1207 added fields for courier
  src/containers/checkout/checkout-form/delivery/courier/courier.js
  src/containers/checkout/checkout-form/delivery/courier/courier.styles.js
  src/locales/ua/checkout.json
  src/utils/checkout.js
  src/validators/chekout.js
Labels: FrontEnd

#1139 Redux hooks on chat/active-messenger with tests
  jest.config.js
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/chat/active-messenger/tests/active-messenger.spec.js
  src/containers/chat/chat.js
  src/containers/chat/mail-form/mail-form.js
  src/containers/chat/operations/chat.mutations.js
  src/containers/chat/tests/chat.spec.js
  src/redux/chat/chat.actions.js
  src/redux/chat/chat.operations.js
  src/redux/chat/chat.reducer.js
  src/redux/chat/chat.sagas.js
  src/redux/chat/chat.types.js
  src/redux/chat/tests/chat.action.test.js
  src/redux/chat/tests/chat.reducer.test.js
  src/redux/chat/tests/chat.sagas.test.js
  src/redux/chat/tests/chat.variables.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
Labels: refactoring, FrontEnd

#1205 Refactor/1204/fix optimze comments
  src/pages/product-details/comments/comments-item/comment-dialog/comment-dialog.js
  src/pages/product-details/comments/comments-item/comments-item.js
  src/pages/product-details/comments/comments-item/reply-comments-item/reply-comments-item.js
  src/pages/product-details/comments/comments-item/tests/comments-item.test.js
  src/pages/product-details/comments/comments-item/tests/comments-item.variables.js
  src/pages/product-details/comments/comments.js
  src/redux/comments/comments.actions.js
  src/redux/comments/comments.operations.js
  src/redux/comments/comments.reducer.js
  src/redux/comments/comments.sagas.js
  src/redux/comments/comments.types.js
  src/redux/comments/tests/comments.actions.test.js
  src/redux/comments/tests/comments.reducer.test.js
  src/redux/comments/tests/comments.sagas.test.js
  src/redux/comments/tests/comments.variables.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/user/tests/user.sagas.spec.js
  src/redux/user/user.sagas.js
Labels: FrontEnd

#1203 Refactor/1196/news
  src/locales/en/common.json
  src/locales/ua/common.json
  src/pages/news/news-item/news-item.js
  src/pages/news/news-page/news-page.js
  src/pages/news/news-page/test/news-page.spec.js
  src/pages/news/operations/news-queries.js
Labels: refactoring, FrontEnd

#1222 Bugfix/1220/comment error message
  src/pages/product-details/comments/comments.styles.js
Labels: bug, FrontEnd

#1216 Remove redux pattern
  src/redux/pattern/pattern.actions.js
  src/redux/pattern/pattern.operations.js
  src/redux/pattern/pattern.reducer.js
  src/redux/pattern/pattern.sagas.js
  src/redux/pattern/pattern.types.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
Labels: refactoring, FrontEnd

#1202 refactor/1146/refactor model in fe
  src/components/model-item/model-item.js
  src/containers/sidebar/operations/burger-menu.queries.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
Labels: refactoring, FrontEnd

#1229 Refactor/1196/news2
  src/pages/news/news-detail/news-detail.js
  src/pages/news/operations/news-queries.js
Labels: refactoring, FrontEnd

#1183 Refactor/1127/materials
  src/containers/orders/cart/cart-item/cart-item.js
  src/pages/materials/materials.js
  src/pages/product-details/detail/detail.js
  src/pages/product-details/operations/product-details.queries.js
  src/pages/product-details/product-info/product-info.js
  src/pages/wishlist/operations/wishlist.queries.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/redux/cart/cart.operations.js
Labels: refactoring, FrontEnd

#1230 Fixed translation-key
  src/pages/materials/materials.js
  src/pages/materials/operations/getAllPatterns.queries.js
Labels: bug, FrontEnd

#1232 Added translationsKey to gql
  src/pages/home/models-list/operations/getAllModels.queries.js
Labels: bug, FrontEnd

#1236 fix checkout form translation (closes #1228)
  src/containers/checkout/checkout-form/checkout-form.js
  src/validators/checkout.js
  src/validators/chekout.js
Labels: bug, FrontEnd

#1240 fixed checkout ukrposhta delivery address translate
  src/containers/checkout/checkout-form/delivery/ukrpost/ukrpost.js
Labels: bug, FrontEnd

#1238 fix checkout translation order comment (closes #1227)
  src/containers/checkout/checkout-form/checkout-form.js
Labels: bug, FrontEnd

#1241 Fixed error translations in checkout-info
  src/containers/checkout/checkout-form/checkout-form.js
Labels: bug, FrontEnd

#1239 Bugfix/1224/checkout nova post
  src/containers/checkout/checkout-form/delivery/nova-post/nova-post.js
  src/validators/checkout.js
Labels: bug

#1251 Bugfix/1242/text color on checkout form in dark theme
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/checkout/checkout-form/delivery/courier/courier.js
  src/containers/checkout/checkout-form/delivery/courier/courier.styles.js
  src/containers/checkout/checkout-form/delivery/delivery.js
  src/containers/checkout/checkout-form/delivery/nova-post/nova-post.styles.js
  src/containers/checkout/checkout-form/delivery/self-pickup/self-pickup.js
  src/containers/checkout/checkout-form/delivery/self-pickup/self-pickup.styles.js
  src/containers/checkout/checkout-form/delivery/ukrpost/ukrpost.js
  src/containers/checkout/checkout-form/delivery/ukrpost/ukrpost.styles.js
  src/containers/checkout/delivery-type/delivery-type.styles.js
Labels: bug, FrontEnd

#1247 Bugfix/1234/self pickup is not working
  src/containers/checkout/checkout-form/checkout-form.js
Labels: bug, FrontEnd

#1244 Bugfix/1219/comment-language-change
  src/locales/en/error.json
  src/locales/ua/error.json
  src/pages/product-details/comments/comments-item/reply-form/reply-form.js
  src/pages/product-details/comments/comments.js
Labels: bug, FrontEnd

#1252 fix/1217/RegisterValidation
  src/pages/register/register-from/register-form.js
  src/pages/register/register.js
  src/validators/register.js
Labels: FrontEnd

#1264 Fixed social networks icons style in dark theme
  src/containers/sidebar/sidebar.styles.js
Labels: bug, FrontEnd

#1260 eslint/1250/rule for error with unused vars
  .eslintrc
  src/components/scroll-bar/scroll-bar.js
  src/containers/orders/order/empty-order/tests/empty-order.test.js
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/hooks/useIsLoadingOrError.js
  src/redux/cart/tests/cart.actions.test.js
  src/tests/unit/pages/login/login.spec.js
Labels: FrontEnd, eslint

#1280 Refactor/1279/error page theme
  src/pages/error-page/error-page.js
  src/pages/error-page/tests/error-page.spec.js
Labels: refactoring, FrontEnd

#1263 Removed ThemeContext from the Chat component
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/chat/chat.js
  src/containers/chat/chat.style.js
  src/containers/chat/mail-form/mail-form.js
Labels: refactoring, FrontEnd

#1276 Refactor/1275/search bar list theme
  src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.js
  src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.styles.js
  src/containers/search-bar-list/search-bar-list-item/tests/search-bar-list-item.spec.js
Labels: refactoring, FrontEnd

#1271 Removed ThemeContext from checkout
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout.js
Labels: refactoring, FrontEnd

#1274 Removed ThemeContext from Cart
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/cart-item/cart-item.styles.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/containers/orders/cart/path-back/path-back.js
  src/containers/orders/cart/path-back/path-back.styles.js
  src/containers/orders/order/order-table/order-table.js
  src/containers/orders/order/order-table/order-table.styles.js
Labels: refactoring, FrontEnd

#1286 Redesign/1254/footer new desighn
  src/components/app-footer/app-footer.js
  src/components/app-footer/app-footer.styles.js
  src/containers/footer-links/footer-links.js
  src/containers/footer-links/footer-links.styles.js
  src/containers/footer-lists/footer-lists.js
  src/containers/footer-lists/footer-lists.styles.js
  src/images/footer-icons/email.svg
  src/images/footer-icons/facebook.svg
  src/images/footer-icons/instagram.svg
  src/images/footer-icons/location.svg
  src/images/footer-icons/phone.svg
Labels: FrontEnd, redesign

#1209 Feature/1150/your order component
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/checkout/checkout-form/tests/__snapshots__/checkout-form.spec.js.snap
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/containers/orders/order/your-order/index.js
  src/containers/orders/order/your-order/your-order.js
  src/locales/en/checkout.json
  src/locales/ua/checkout.json
  src/tests/unit/components/your-order.spec.js
  src/tests/unit/components/your-order.variables.js
Labels: FrontEnd

#1292 console warnings cart checkout
  src/containers/checkout/checkout-form/delivery/self-pickup/self-pickup.js
  src/containers/checkout/checkout-form/delivery/self-pickup/self-pickup.styles.js
  src/containers/checkout/checkout-form/delivery/self-pickup/tests/self-pickup.spec.js
  src/containers/checkout/checkout-form/tests/__snapshots__/checkout-form.spec.js.snap
  src/containers/orders/order/order-table/order-table.js
  src/containers/orders/order/order-table/tests/__snapshots__/order-table.test.js.snap
Labels: bug, FrontEnd, clean console

#1284 Fixed errors on profile page
  src/configs/index.js
  src/locales/en/error.json
  src/locales/ua/profilePage.json
  src/pages/profile-page/profile-page.js
  src/redux/user/user.operations.js
Labels: bug, FrontEnd

#1309 Fix error
  src/pages/profile-page/profile-page.js
Labels: bug, FrontEnd

#1248 Fixed white underline that appears with dark theme
  src/containers/currency/currency.styles.js
  src/containers/language/language.styles.js
Labels: bug, FrontEnd

#1272 Redesigned 404 page
  src/components/app/app-theme/theme.js
Labels: FrontEnd, redesign

#1308 Removed ThemeContext from thanks page
  src/containers/checkout/checkout-form/tests/__snapshots__/checkout-form.spec.js.snap
  src/pages/thanks-page/order-data/order-data.js
  src/pages/thanks-page/order-data/order-data.styles.js
  src/pages/thanks-page/thanks-page.js
  src/pages/thanks-page/thanks-page.styles.js
Labels: refactoring, FrontEnd

#1293 Test/1173/comments page
  src/pages/product-details/comments/comments-item/comment-dialog/comment-dialog.js
  src/pages/product-details/comments/comments-item/comment-dialog/tests/comment-dialog.test.js
  src/pages/product-details/comments/comments-item/comment-dialog/tests/comment-dialog.variable.js
  src/pages/product-details/comments/comments-item/comments-item.js
  src/pages/product-details/comments/comments-item/reply-form/reply-form.js
  src/pages/product-details/comments/comments.js
  src/pages/product-details/comments/tests/comments.test.js
  src/tests/unit/pages/product-details/comment-dialog.spec.js
  src/tests/unit/pages/product-details/comment-item.spec.js
  src/tests/unit/pages/product-details/comments.spec.js
  src/tests/unit/pages/product-details/comments.variables.js
  src/tests/unit/pages/product-details/reply-comment-item.spec.js
Labels: FrontEnd, test

#1313 Fix bugs in product list
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/locales/en/product.json
  src/locales/ua/product.json
  src/pages/product-details/product-details.js
  src/pages/product-details/product-details.styles.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
  src/pages/product-details/similar-products/similar-products.js
  src/pages/product-details/tests/product-details.spec.js
  src/pages/product-list-page/product-list-item/product-list-item.js
Labels: bug, FrontEnd

#1268 Fixed all translations use i18next
  src/components/app/app.js
  src/components/scroll-bar/scroll-bar.js
  src/containers/orders/order-history/order-history-order/order-history-order.js
  src/containers/orders/order-history/order-history-table/order-history-table.js
  src/containers/orders/order/order-table/order-table.js
  src/containers/orders/order/order-table/tests/__snapshots__/order-table.test.js.snap
  src/containers/toast/toast.js
  src/hooks/use-comment-validation.js
  src/pages/confirmation/confirmation.js
  src/pages/images-constructor/hooks.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/profile-page/profile-page.js
  src/pages/recovery/recovery.js
  src/pages/register/register.js
  src/pages/thanks-page/thanks-page.js
  src/utils/multiple.selectors.js
Labels: bug, FrontEnd

#1315 codsmels in serviceWorker and active messenger tests
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/chat/active-messenger/tests/active-messenger.spec.js
  src/serviceWorker.js
Labels: FrontEnd

#1314 Feature/1208/Select opportunity for courier delivery
  src/configs/index.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/delivery/courier/courier.js
  src/containers/checkout/checkout-form/delivery/courier/index.js
  src/containers/checkout/checkout-form/delivery/courier/tests/courier.spec.js
  src/containers/checkout/checkout-form/delivery/delivery.js
  src/containers/checkout/checkout-form/delivery/tests/__snapshots__/delivery.test.js.snap
  src/containers/checkout/checkout-form/delivery/tests/delivery.test.js
  src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/index.js
  src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/operations/get-ukrPost-address-data.queries.js
  src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/tests/ukrpost-and-courier.spec.js
  src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/ukrpost-and-courier.js
  src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/ukrpost-and-courier.styles.js
  src/containers/checkout/checkout-form/delivery/ukrpost/index.js
  src/containers/checkout/checkout-form/delivery/ukrpost/ukrpost.js
  src/containers/checkout/checkout-form/delivery/ukrpost/ukrpost.styles.js
  src/containers/checkout/checkout-form/tests/__snapshots__/checkout-form.spec.js.snap
  src/containers/checkout/delivery-type/delivery-type.js
  src/containers/checkout/delivery-type/delivery-type.styles.js
  src/containers/checkout/delivery-type/tests/__snapshots__/delivery-type.test.js.snap
  src/containers/checkout/delivery-type/tests/delivery-type.test.js
  src/locales/en/checkout.json
  src/locales/en/delivery.json
  src/locales/ua/checkout.json
  src/locales/ua/delivery.json
  src/utils/checkout.js
  src/validators/checkout.js
Labels: FrontEnd

#1287 Bugfix/1187/fix price change in cart
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/filled-cart/tests/__snapshots__/filled-cart.spec.js.snap
  src/redux/cart/cart.sagas.js
  src/utils/priceCalculating.js
Labels: bug, FrontEnd

#1318 1317/clean console your order
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/checkout/checkout-form/delivery/tests/__snapshots__/delivery.test.js.snap
  src/containers/checkout/delivery-type/tests/__snapshots__/delivery-type.test.js.snap
  src/containers/orders/order/order-table/tests/__snapshots__/order-table.test.js.snap
  src/containers/orders/order/your-order/your-order.js
  src/pages/product-details/similar-products/similar-products-item/tests/__snapshots__/similar-products-item.test.js.snap
  src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
Labels: FrontEnd, clean console

#1269 refactor configs/index 1235
  src/components/scroll-bar/scroll-bar.js
  src/configs/index.js
  src/containers/snackbar/snackbar.js
  src/hooks/tests/use-comment-validation.spec.js
  src/hooks/use-comment-validation.js
  src/locales/en/common.json
  src/locales/en/modal.json
  src/locales/en/product.json
  src/locales/ua/common.json
  src/locales/ua/product.json
  src/pages/product-details/comments/comments-item/comment-dialog/comment-dialog.js
  src/pages/product-details/comments/comments-item/reply-form/reply-form.js
  src/pages/product-details/comments/comments-item/reply-form/tests/reply-form.test.js
  src/pages/product-details/comments/comments.js
  src/pages/product-list-page/product-sort/product-sort.js
Labels: refactoring, FrontEnd

#1325 change size ADD button
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
Labels: redesign

#1316 fixed codesmells on FE
  src/components/number-input/number-input.js
  src/configs/index.js
  src/configs/regexp.js
Labels: refactoring, FrontEnd

#1326 Redesigned contacts page according to the new design on FE
  src/images/contacts-icons/clock.svg
  src/images/map.jpg
  src/pages/contacts/contacts.js
  src/pages/contacts/contacts.styles.js
Labels: FrontEnd, redesign

#1340 Fixed contacts page redesign
  src/images/map.jpg
  src/pages/contacts/contacts.js
  src/pages/contacts/contacts.styles.js
Labels: FrontEnd, redesign

#1327 refactored recovery form
  src/images/9.jpg
  src/pages/recovery/recovery.styles.js
Labels: refactoring, FrontEnd, redesign

#1348 1331/Clear translations folder
  src/configs/index.js
  src/pages/images-constructor/hooks.js
  src/pages/images-constructor/images-constructor.js
  src/pages/product-list-page/product-list-filter/product-list-filter.js
  src/translations/constructor.translations.js
  src/translations/contacts.translations.js
  src/translations/header-profile.translations.js
  src/translations/not-found-page.translations.js
  src/translations/pattern.translations.js
  src/translations/product-details.translations.js
  src/translations/product-list.translations.js
  src/translations/thanks-page.translations.js
  src/translations/toast.translations.js
  src/translations/wishlist.translations.js
Labels: FrontEnd

#1341 Refactor/1301/product theme
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/chat/active-messenger/tests/active-messenger.spec.js
  src/containers/chat/chat.style.js
  src/containers/footer-links/footer-links.styles.js
  src/containers/footer-lists/footer-lists.styles.js
  src/containers/header-profile/header-profile.styles.js
  src/containers/orders/cart/cart-item/cart-item.styles.js
  src/containers/orders/cart/cart-item/tests/cart-item.spec.js
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/containers/orders/cart/path-back/path-back.styles.js
  src/containers/orders/order/order-table/order-table.styles.js
  src/pages/not-found-page/tests/__snapshots__/not-found-page.test.js.snap
  src/pages/product-details/product-details.js
  src/pages/product-details/product-images/product-images.js
  src/pages/product-details/product-images/tests/product-images.spec.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
  src/pages/product-details/similar-products/similar-products-item/tests/similar-products-item.test.js
  src/pages/product-details/similar-products/similar-products.js
  src/pages/product-details/similar-products/similar-products.styles.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/product-list-page/product-list-item/product-list-item.style.js
  src/pages/product-list-page/tests/product-list-item.spec.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.styles.js
Labels: refactoring, FrontEnd

#1352 Rewrote tests for Pages/Cart in React Testing Library
  src/pages/cart/tests/__snapshots__/cart-page.test.js.snap
  src/pages/cart/tests/cart-page.test.js
  src/tests/unit/pages/cart/cart.spec.js
Labels: FrontEnd, test

#1345 Redesign/1312/payment shipping page
  src/locales/en/footer.json
  src/pages/business-page/business-page.js
  src/pages/business-page/business-page.style.js
Labels: FrontEnd, redesign

#1353 1349/use product filters translations
  src/hooks/use-product-filters/tests/use-product-filters.spec.js
  src/hooks/use-product-filters/use-product-filters.js
  src/translations/product-list.translations.js
Labels: refactoring, FrontEnd

#1360 Cleaned console warning in sidebar
  src/containers/sidebar/sidebar-item/sidebar-item.js
Labels: FrontEnd, clean console

#1346 Removing delivery type from redux
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/delivery-type/delivery-type.js
  src/containers/checkout/checkout-form/delivery-type/delivery-type.styles.js
  src/containers/checkout/checkout-form/delivery-type/index.js
  src/containers/checkout/checkout-form/delivery-type/tests/__snapshots__/delivery-type.test.js.snap
  src/containers/checkout/checkout-form/delivery-type/tests/delivery-type.test.js
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/containers/checkout/checkout.js
  src/redux/cart/cart.actions.js
  src/redux/cart/cart.reducer.js
  src/redux/cart/cart.sagas.js
  src/redux/cart/cart.types.js
Labels: FrontEnd

#1363 Fixed translations
  src/i18n.js
Labels: bug, FrontEnd

#1362 fixed propTypes
  src/pages/news/news-item/news-item.js
Labels: FrontEnd, clean console

#1367 Fix transaltions
  src/i18n.js
Labels: bug, FrontEnd

#1366 clean console errors
  src/components/dropdown/dropdown.js
  src/containers/sidebar/sidebar.js
Labels: clean console

#1328 wishlist redesign
  src/components/modal/modal.js
  src/components/modal/modal.styles.js
  src/components/modal/tests/modal.spec.js
  src/containers/orders/order/empty-order/empty-order.styles.js
  src/images/modal-icon/modalCloseIcon.svg
  src/index.css
  src/locales/en/common.json
  src/locales/en/modal.json
  src/locales/ua/common.json
  src/locales/ua/modal.json
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.styles.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/pages/wishlist/wishlist-item/wishlist-item.styles.js
Labels: FrontEnd, test, redesign

#1374 Clean console warnings in login and filter
  src/containers/products-filters-container/products-filters-container.js
  src/pages/login/login.js
Labels: FrontEnd, clean console

#1382 Cleaned console warning about 'integrity'
  public/index.html
Labels: FrontEnd, clean console

#1376 sonar/1368/exclude variables for tests
  sonar-project.properties
Labels: FrontEnd, sonar

#1397 Fixed routes in login
  src/redux/user/tests/user.sagas.spec.js
  src/redux/user/user.sagas.js
Labels: bug, FrontEnd

#1371 Redesign/1333/chat
  package-lock.json
  package.json
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/chat/active-messenger/tests/active-messenger.spec.js
  src/containers/chat/chat.style.js
  src/containers/chat/mail-form/mail-form.js
  src/containers/chat/mail-form/tests/mail-form.spec.js
Labels: FrontEnd, redesign

#1398 Tests for self-pickup using react testing library
  src/containers/checkout/checkout-form/delivery/self-pickup/tests/self-pickup.spec.js
  src/tests/unit/containers/self-pickup/self-pickup.spec.js
Labels: FrontEnd, test

#1389 Fixed translations
  src/components/app/app.js
  src/hooks/use-translations-load.js
  src/hooks/use-translations-load.spec.js
Labels: bug, FrontEnd

#1390 Refactor/1355/clean console
  src/components/modal/modal.js
  src/components/modal/modal.styles.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
Labels: bug, FrontEnd

#1386 Redesign/1332/redesign thanks page
  src/components/loader/loader.js
  src/images/thanks.png
  src/locales/en/thanksPage.json
  src/locales/ua/thanksPage.json
  src/pages/thanks-page/order-data/index.js
  src/pages/thanks-page/order-data/order-data.js
  src/pages/thanks-page/order-data/order-data.styles.js
  src/pages/thanks-page/order-data/order-item-card/index.js
  src/pages/thanks-page/order-data/order-item-card/order-item-card.js
  src/pages/thanks-page/order-data/order-item-card/order-item-card.styles.js
  src/pages/thanks-page/tests/thanks-page.spec.js
  src/pages/thanks-page/thanks-card/index.js
  src/pages/thanks-page/thanks-card/thanks-card.js
  src/pages/thanks-page/thanks-card/thanks-card.styles.js
  src/pages/thanks-page/thanks-page.js
  src/pages/thanks-page/thanks-page.styles.js
  src/redux/order/order.operations.js
  src/tests/unit/components/thanks-card/thanks-card.spec.js
  src/tests/unit/pages/thanks-page/thanks-page.spec.js
  src/tests/unit/pages/thanks-page/thanks-page.variables.js
Labels: FrontEnd, redesign

#1381 Redesigned about us page
  src/pages/business-page/business-page.style.js
Labels: FrontEnd, redesign

#1369 Hotfix/1320/footer
  src/components/app-footer/app-footer.js
  src/components/icons/facebook-icon/facebook-icon.styles.js
  src/components/icons/facebook-icon/index.js
  src/components/icons/index.js
  src/components/icons/instagram-icon/index.js
  src/components/icons/instagram-icon/instagram-icon.styles.js
  src/containers/footer-links/index.js
  src/containers/footer-links/tests/footer-links.test.js
  src/containers/footer-lists/footer-lists.js
  src/containers/sidebar/sidebar.js
  src/containers/sidebar/tests/__snapshots__/sidebar.test.js.snap
  src/containers/sidebar/tests/sidebar.test.js
  src/containers/social-links/const.js
  src/containers/social-links/index.js
  src/containers/social-links/social-links.js
  src/containers/social-links/social-links.styles.js
  src/containers/social-links/tests/social-links.test.js
  src/images/footer-icons/facebook.svg
  src/images/footer-icons/instagram.svg
  src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
  src/pages/product-details/tests/product-details.spec.js
Labels: bug, FrontEnd

#1350 Redesign/1295/order history page
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/containers/chat/mail-form/tests/mail-form.spec.js
  src/containers/orders/order-history/order-history-item-product/index.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.styles.js
  src/containers/orders/order-history/order-history-item/index.js
  src/containers/orders/order-history/order-history-item/order-history-item.js
  src/containers/orders/order-history/order-history-item/order-history-item.styles.js
  src/containers/orders/order-history/order-history-order-item/index.js
  src/containers/orders/order-history/order-history-order-item/order-history-order-item.js
  src/containers/orders/order-history/order-history-order-item/order-history-order-item.styles.js
  src/containers/orders/order-history/order-history-order-item/tests/order-history-order-item.spec.js
  src/containers/orders/order-history/order-history-order/index.js
  src/containers/orders/order-history/order-history-order/order-history-order.js
  src/containers/orders/order-history/order-history-table/order-history-table.js
  src/containers/orders/order-history/order-history-table/order-history-table.style.js
  src/containers/orders/order-history/order-history-table/tests/order-history-table.spec.js
  src/locales/en/common.json
  src/locales/en/order-history.json
  src/locales/ua/common.json
  src/locales/ua/order-history.json
  src/pages/not-found-page/tests/__snapshots__/not-found-page.test.js.snap
  src/pages/order-history/operations/order-history.queries.js
  src/pages/order-history/order-history.js
  src/tests/unit/components/order-history-item/order-history-item.spec.js
  src/tests/unit/components/order-history-item/order-history-item.variables.js
  src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js
  src/tests/unit/components/order-history-list-item/order-history-item-product.variables.js
  src/tests/unit/components/order-history-table/order-history-table.spec.js
  src/tests/unit/components/your-order/your-order.spec.js
  src/tests/unit/components/your-order/your-order.variables.js
  src/tests/unit/pages/order-history/order-history.spec.js
Labels: refactoring, redesign

#1401 Tests for delivery using React Testing Library
  src/containers/checkout/checkout-form/delivery/tests/__snapshots__/delivery.test.js.snap
  src/containers/checkout/checkout-form/delivery/tests/delivery.test.js
  src/tests/unit/containers/delivery/delivery.spec.js
  src/tests/unit/containers/delivery/delivery.variables.js
Labels: test

#1400 Redesign/1322/profile page
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/configs/index.js
  src/images/profile-icons.js
  src/locales/en/profilePage.json
  src/locales/ua/error.json
  src/locales/ua/profilePage.json
  src/pages/not-found-page/tests/__snapshots__/not-found-page.test.js.snap
  src/pages/profile-page/profile-page.js
  src/pages/profile-page/profile-page.styles.js
  src/pages/profile-page/tests/profile-page.test.js
  src/tests/unit/pages/profile-page/profile-page.spec.js
  src/tests/unit/pages/profile-page/profile-page.variables.js
  src/utils/handle-profile-page.js
  src/validators/profile-page.js
Labels: FrontEnd, redesign

#1339 Redesign/1255/hompage
  src/components/app/app.js
  src/configs/routes.js
  src/containers/cart-header/cart-header.js
  src/containers/language/language-component.js
  src/containers/sidebar/sidebar.styles.js
  src/images/Arrow 5.svg
  src/images/Arrow 6.svg
  src/images/bg1.jpg
  src/images/bg3.jpg
  src/index.css
  src/locales/en/home.json
  src/locales/ua/home.json
  src/pages/home/categories-list/categories-list.js
  src/pages/home/categories-list/categories-list.style.js
  src/pages/home/categories-list/category-item/category-item.js
  src/pages/home/categories-list/category-item/category-item.style.js
  src/pages/home/contructor-preview/constructor-preview.js
  src/pages/home/contructor-preview/constructor-preview.style.js
  src/pages/home/home.js
  src/pages/home/slider/slider-data.js
  src/pages/home/slider/slider-home-page.js
  src/pages/home/slider/slider-home-page.style.js
  src/pages/home/slider/tests/__snapshots__/slider-home-page.test.js.snap
  src/pages/home/slider/tests/slider-home-page.test.js
  src/pages/images-constructor/hooks.js
  src/pages/product-list-page/product-list-filter/hot-item-filter/hot-item-filter.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/tests/unit/pages/home/slider/slider-home-page.spec.js
  src/utils/imageLoad.js
Labels: FrontEnd, redesign

#1383 Feature/1342/redesign registration
  src/components/google-log-in-btn/google-button.styles.js
  src/configs/index.js
  src/locales/en/error.json
  src/locales/en/register.json
  src/locales/ua/error.json
  src/locales/ua/register.json
  src/pages/register/register-from/register-form.js
  src/pages/register/register-from/register-form.styles.js
  src/pages/register/register.js
  src/pages/register/register.styles.js
  src/translations/user.translations.js
  src/validators/register.js
Labels: FrontEnd, redesign

#1413 Hotfix/1409/console warnings in useIsLoadingOrError hook
  src/hooks/useIsLoadingOrError.js
Labels: FrontEnd, clean console

#1404 Fix position of arrows and button in slider on Homepage
  src/pages/home/slider/slider-home-page.js
  src/pages/home/slider/slider-home-page.style.js
Labels: FrontEnd

#1417 Bugfix/1412/clean console sidebar
  src/containers/sidebar/sidebar.js
  src/pages/not-found-page/tests/__snapshots__/not-found-page.test.js.snap
Labels: FrontEnd, clean console

#1414 Fix console warnings #1407
  src/containers/orders/cart/cart-item/cart-item.js
  src/pages/login/login.js
Labels: FrontEnd, clean console

#1418 clean console/1405/errors with missing dependencies in useEffect
  src/containers/checkout/checkout-form/delivery/nova-post/nova-post.js
  src/pages/thanks-page/thanks-page.js
Labels: clean console

#1415 console/1410/deliveryType_productSubmit
  src/containers/checkout/checkout-form/delivery-type/delivery-type.js
  src/pages/product-details/product-submit/product-submit.js
Labels: bug, FrontEnd, clean console

#1419 Hotfix/1408/product list
  src/pages/product-list-page/product-list-page.js
Labels: clean console

#1380 redesign login page
  src/components/app/app-theme/app.pallete.js
  src/locales/en/login.json
  src/locales/ua/login.json
  src/pages/login/login.js
  src/pages/login/login.styles.js
Labels: FrontEnd, redesign

#1422 Hotfix/field color registration
  src/pages/not-found-page/tests/__snapshots__/not-found-page.test.js.snap
  src/pages/not-found-page/tests/not-found-page.test.js
  src/pages/register/register-from/register-form.styles.js
Labels: bug

#1424 1283/catalog page redesign
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/components/dropdown/dropdown.styles.js
  src/components/scroll-bar/scroll-bar.js
  src/configs/index.js
  src/containers/header-right-bar/header-right-bar.js
  src/containers/products-filters-container/products-filters-container.js
  src/containers/products-filters-container/products-filters-container.styles.js
  src/containers/search-bar/search-bar.js
  src/containers/search-bar/search-bar.styles.js
  src/containers/sidebar/sidebar.styles.js
  src/hooks/use-product-filters/use-product-filters.js
  src/locales/en/common.json
  src/locales/en/product-list-page.json
  src/locales/ua/common.json
  src/locales/ua/product-list-page.json
  src/pages/product-details/product-images/product-images.styles.js
  src/pages/product-list-page/count-per-page/count-per-page.js
  src/pages/product-list-page/count-per-page/count-per-page.styles.js
  src/pages/product-list-page/product-list-filter/hot-item-filter/hot-item-filter.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-filter/product-list-filter.js
  src/pages/product-list-page/product-list-filter/product-list-filter.styles.js
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-list-page.styles.js
  src/pages/product-list-page/product-sort/product-sort.js
  src/pages/product-list-page/product-sort/product-sort.styles.js
  src/pages/product-list-page/tests/count-per-page.spec.js
  src/pages/product-list-page/tests/hot-items-filter.spec.js
  src/pages/product-list-page/tests/price-filter.spec.js
  src/pages/product-list-page/tests/product-list-filter.spec.js
  src/pages/product-list-page/tests/product-list-page.spec.js
  src/redux/toast/tests/toasts.reducer.test.js
Labels: FrontEnd, redesign

#1372 Refactor cart from redux
  src/configs/index.js
  src/containers/cart-header/cart-header.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/cart-item/tests/cart-item.spec.js
  src/containers/orders/cart/cart-item/tests/cart-item.variables.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/cart/filled-cart/tests/__snapshots__/filled-cart.spec.js.snap
  src/containers/orders/cart/filled-cart/tests/filled-cart.spec.js
  src/containers/orders/operations/order.queries.js
  src/containers/orders/order/order-table/order-table.js
  src/containers/orders/order/order-table/tests/__snapshots__/order-table.test.js.snap
  src/containers/orders/order/order-table/tests/order-table.test.js
  src/containers/orders/order/your-order/order-item/index.js
  src/containers/orders/order/your-order/order-item/order-item.js
  src/containers/orders/order/your-order/your-order.js
  src/hooks/use-cart.js
  src/pages/cart/cart.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/product-submit/tests/product-details.variables.js
  src/pages/product-details/product-submit/tests/product-submit.test.js
  src/redux/newCart/cart.actions.js
  src/redux/newCart/cart.reducer.js
  src/redux/newCart/cart.types.js
  src/redux/root.reducer.js
  src/services/local-storage.service.js
  src/tests/unit/components/your-order/your-order.spec.js
  src/tests/unit/components/your-order/your-order.variables.js
  src/tests/unit/pages/cart/cart.spec.js
  src/utils/checkout.js
  src/utils/priceCalculating.js
Labels: refactoring, FrontEnd

#1426 console/878/scrollBar_comments_checkoutForm
  src/components/scroll-bar/scroll-bar.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/pages/product-details/comments/comments.js
Labels: FrontEnd, clean console

#1421 Redesigned news details page
  src/locales/en/common.json
  src/locales/en/newsDetail.json
  src/locales/ua/common.json
  src/locales/ua/newsDetail.json
  src/pages/news/news-detail/news-detail.js
  src/pages/news/news-detail/news-detail.style.js
  src/pages/news/news-detail/test/news-detail.spec.js
Labels: FrontEnd, redesign

#1432 Fixed integrity error
  public/index.html
Labels: FrontEnd, clean console

#1433 1283/Popular bar was fixed
  src/pages/product-list-page/product-list-filter/hot-item-filter/hot-item-filter.js
Labels: bug, FrontEnd

#1434 Fix adaptive slider
  src/pages/home/slider/slider-home-page.style.js
Labels: FrontEnd

#1384 Feature/994/constructor
  src/locales/en/common.json
  src/locales/ua/common.json
  src/pages/images-constructor/hooks.js
  src/pages/images-constructor/images-constructor.js
  src/pages/images-constructor/operations/getAllConstructors.queries.js
  src/pages/images-constructor/operations/getConstructorByModel.queries.js
  src/pages/images-constructor/tests/images-constructor.spec.js
  src/pages/images-constructor/tests/images-constructor.variables.js
  src/pages/images-constructor/use-constructor-loader.js
  src/utils/constructor.js
Labels: refactoring, FrontEnd

#1438 Refactor translations back, basics, bottoms, pocket, strap and position in front-end
  src/pages/images-constructor/images-constructor.js
  src/pages/images-constructor/tests/images-constructor.spec.js
Labels: FrontEnd
