Repository ita-social-projects/horondi_client_fe, pull requests merged in 2022-06, with the labels that each got.

#1980 fix breadcrumbs visibillity
  src/pages/news/news-detail/news-detail.style.js
Labels: FrontEnd part, design

#1977 Hotfix/1960/incorrect position of snackbar
  src/containers/toast/toast.js
  src/containers/toast/toast.styles.js
Labels: FrontEnd part, redesign

#1974 fix drawer sidebar at smaller screen sizes
  src/containers/sidebar/sidebar.styles.js
Labels: FrontEnd part, design

#1975 fix wishlist column margin
  src/pages/wishlist/wishlist-item/wishlist-item.styles.js
Labels: FrontEnd part, design

#1973 Redesign/1954/some of icons have incorrect color
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/containers/sidebar/sidebar-item/sidebar-items.styles.js
  src/containers/sidebar/sidebar-item/tests/sidebar-item.spec.js
  src/containers/sidebar/sidebar.js
  src/containers/sidebar/sidebar.styles.js
  src/containers/social-links/social-links.styles.js
Labels: FrontEnd part, redesign

#1978 fixed chat
  src/containers/chat/chat.style.js
Labels: FrontEnd part

#1987 In "My certificates" write responsive page
  src/containers/my-certificates/certificate-table/certificate-table.styles.js
  src/containers/my-certificates/cetrificate-item/certificate-item.styles.js
  src/containers/my-certificates/filled-certificates/filled-certificates.styles.js
Labels: FrontEnd part

#1993 cart image offset fix
  src/containers/orders/cart/cart-item/cart-item.styles.js
  src/containers/orders/order/order-table/order-table.styles.js
Labels: FrontEnd part, design

#1995 Buttons on home page redesigned according to figma layout
  src/pages/home/contructor-preview/constructor-preview.style.js
  src/pages/home/models-list/models-list.js
  src/pages/home/models-list/models-list.style.js
  src/pages/home/slider/slider-home-page.style.js
Labels: FrontEnd part, redesign

#1997 facebook icon z-index
  src/containers/chat/chat.js
  src/containers/chat/chat.style.js
Labels: FrontEnd part, design

#2000 Fixed incorrect vertical alignment of currency icon
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/orders/order/your-order/your-order.js
  src/images/profile-icons.js
Labels: bug, FrontEnd part

#2005 added basePrice to constructor
  src/components/constructor-canvas/constructor-canvas.js
  src/locales/ua/common.json
  src/pages/images-constructor/constants.js
  src/pages/images-constructor/images-constructor.js
  src/pages/images-constructor/operations/getConstructorByModel.queries.js
  src/pages/images-constructor/use-constructor-loader.js
Labels: refactoring, FrontEnd part, constructor, feature

#2006 fixed bugs and created adaptive design for order history page
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.styles.js
  src/containers/orders/order-history/order-history-item/order-history-item.styles.js
  src/containers/orders/order-history/order-history-table/order-history-table.js
  src/containers/orders/order-history/order-history-table/order-history-table.style.js
  src/pages/order-history/operations/order-history.queries.js
  src/pages/order-history/order-history.styles.js
Labels: bug, UI, FrontEnd part, design

#2007 preview pattern in product detail
  src/containers/chat/chat.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-info/product-info.styles.js
  src/pages/product-details/product-sizes/product-sizes.styles.js
Labels: FrontEnd part, Functional

#2011 Fix SonarCloud code-smells Front-end on repository.
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/checkout/checkout-form/delivery/nova-post/nova-post.js
  src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/ukrpost-and-courier.js
  src/containers/snackbar/snackbar.js
  src/pages/answers-questions-page/answers-questions-page.js
  src/pages/news/news-item/news-item.js
  src/pages/news/news-item/news-item.style.js
  src/pages/product-details/comments/comments.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-page.js
  src/routes/routes.js
  src/utils/eyeToggle.js
Labels: FrontEnd part

#2021 materials photo disappear bug fixed
  src/pages/materials/slider/slider.styles.js
Labels: bug

#2031 Add a favicon for client
  public/favicon.ico
  public/favicon.svg
  public/index.html
Labels: good first issue, FrontEnd part, feature

#2033 create clear icon at home search
  src/containers/search-bar/search-bar.js
  src/containers/search-bar/search-bar.styles.js
  src/containers/search-bar/tests/search-bar.spec.js
Labels: FrontEnd part, Functional
