Repository ita-social-projects/horondi_client_fe, pull requests merged in 2022-11, with the labels that each got.

#2199 Fixed styles in footer
  src/containers/social-links/social-links.styles.js
Labels: bug, FrontEnd part

#2198 Fixed image background in carousel
  src/pages/home/categories-list/category-item/category-item.style.js
Labels: bug, FrontEnd part

#2200 Fixed spaces between sections
  src/pages/home/categories-list/categories-list.style.js
  src/pages/home/models-list/models-list.style.js
Labels: bug, FrontEnd part

#2203 Fix styles in confirm email page
  src/pages/register/register.styles.js
Labels: FrontEnd part

#2216 fixed spaces beetwen acordion and border
  src/components/accordion/accordions.style.js
  src/pages/answers-questions-page/answers-questions-page.js
  src/pages/answers-questions-page/answers-questions-page.style.js
Labels: bug, FrontEnd part

#2226 refactored constructor
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/operations/getConstructorByModel.query.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/containers/sidebar/sidebar.js
  src/locales/en/common.json
  src/locales/ua/common.json
  src/pages/images-constructor/images-constructor.js
  src/pages/images-constructor/operations/getAllConstructors.queries.js
  src/pages/images-constructor/operations/getConstructorByModel.queries.js
  src/pages/images-constructor/tests/images-constructor.spec.js
  src/pages/images-constructor/tests/images-constructor.variables.js
  src/pages/images-constructor/use-constructor-loader.js
  src/tests/unit/components/sidebar/sidebar.spec.js
  src/utils/constructor.js
Labels: FrontEnd part, constructor

#2218 change width
  src/containers/header-profile/header-profile.styles.js
Labels: bug, FrontEnd part

#2233 Changed border color of text field
  src/pages/gift-certificate/gift-certificate.js
  src/pages/gift-certificate/gift-certificate.styles.js
Labels: bug, FrontEnd part

#2221 Changed size of plugs, color of text and box-shadow color
  src/pages/product-details/product-images/product-images.styles.js
Labels: bug, FrontEnd part

#2223 redirect to choosen category
  src/pages/product-details/product-path/product-path.js
Labels: bug, FrontEnd part

#2237 Highlighted units name
  src/pages/business-page/business-page.style.js
Labels: bug, FrontEnd part

#2243 Fixed pagination button style
  src/pages/product-list-page/product-list-page.styles.js
Labels: bug, FrontEnd part

#2240 Fixed style in footer
  src/containers/social-links/social-links.styles.js
Labels: bug, FrontEnd part

#2241 Changed price and size showing in orders
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/containers/orders/order-history/order-history-item/order-history-item.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
Labels: bug, FrontEnd part

#2236 fix back button
  src/pages/product-details/product-details.js
  src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
Labels: bug, FrontEnd part

#2232 Fix console warnings and errors
  src/components/constructor-canvas/constructor-canvas.js
  src/containers/checkout/checkout-form/delivery/worldwide/worldwide.js
  src/containers/header-profile/header-profile.js
  src/containers/language/language-component.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/search-bar/search-bar.js
  src/containers/sidebar/sidebar.js
  src/hooks/tests/use-currency.spec.js
  src/hooks/use-cart.js
  src/hooks/use-currency.js
  src/pages/images-constructor/images-constructor.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-page.js
  src/pages/thanks-page/thanks-page.js
  src/tests/unit/pages/product-list-page/product-list-page.spec.js
Labels: FrontEnd part

#2265 Bugfix/2157/set default value of product
  src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
  src/pages/product-list-page/count-per-page/count-per-page.js
Labels: bug, FrontEnd part

#2253 fix products quantity in cart
  src/components/number-input/number-input.js
  src/containers/orders/cart/cart-item/cart-item.js
Labels: FrontEnd part

#2276 Deleted useRef
  src/containers/language/language-component.js
Labels: bug, FrontEnd part

#2264 Fixed styles in reset password page
  src/components/auth-form/auth-form-heading/auth-form-heading.styles.js
  src/pages/recovery/recovery.js
  src/pages/recovery/recovery.styles.js
Labels: bug, FrontEnd part

#2275 Bug/2163/product-sort console warning
  src/pages/product-list-page/product-sort/product-sort.js
Labels: bug, FrontEnd part

#2272 Bug/2266/fix about us page styles on mobile
  src/pages/about-us/about-us.styles.js
Labels: bug, UI, FrontEnd part

#2263 Add snack bars to saving user profile
  src/components/auth-form/auth-form-button/auth-form-button.js
  src/components/auth-form/auth-form-button/auth-form-button.styles.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/locales/en/profilePage.json
  src/locales/ua/profilePage.json
  src/pages/profile-page/avatar/avatar.js
  src/pages/profile-page/profile-page.js
  src/pages/profile-page/profile-page.styles.js
  src/tests/unit/pages/profile-page/profile-page.spec.js
  src/validators/checkout.js
  src/validators/profile-page.js
Labels: bug, FrontEnd part

#2279 Changed styles in cart for mobile
  src/components/number-input/number-input.styles.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/cart-item/cart-item.styles.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/containers/orders/order/order-table/order-table.styles.js
  src/locales/en/cart.json
Labels: bug, FrontEnd part

#2278 Bugfix/2269/currency language theme does not exist on mobile
  src/components/scroll-bar/tests/scroll-bar.spec.js
  src/containers/cart-header/cart-header.styles.js
  src/containers/sidebar/sidebar.js
  src/containers/sidemenu-right-bar/sidemenu-right-bar.js
  src/containers/sidemenu-right-bar/sidemenu-right-bar.styles.js
  src/containers/social-links/social-links.styles.js
  src/containers/wishlist-header/wishlist-header.js
  src/containers/wishlist-header/wishlist-header.styles.js
Labels: bug, FrontEnd part

#2293 Changed padding of page titles
  src/pages/answers-questions-page/answers-questions-page.style.js
  src/pages/business-page/business-page.style.js
  src/pages/gift-certificate/gift-certificate.styles.js
  src/pages/materials/materials.style.js
  src/pages/news/news-page/news-page.style.js
Labels: bug, UI, FrontEnd part

#2286 Changed styles for button size in dark thema
  src/pages/product-details/product-sizes/product-sizes.styles.js
Labels: bug, FrontEnd part

#2296 [Checkout page] Price of Backpack from constructor in checkout page is NaN
  src/containers/orders/order/your-order/order-item/order-item.js
  src/containers/orders/order/your-order/your-order.js
Labels: bug, FrontEnd part

#2294 bugFix/2282/add-disable-button-profile-page
  src/components/auth-form/auth-form-button/auth-form-button.styles.js
  src/pages/profile-page/profile-page.js
  src/pages/profile-page/profile-page.styles.js
  src/tests/unit/pages/profile-page/profile-page.spec.js
  src/tests/unit/pages/profile-page/profile-page.variables.js
  src/utils/handle-profile-page.js
Labels: refactoring

#2292 [Catalog] Re-render of the catalog
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-page.js
Labels: bug, FrontEnd part

#2288 [Checkout page] Price is lower if certificate was used in previous order
  src/components/number-input/number-input.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/hooks/use-cart.js
  src/pages/cart/cart.js
  src/pages/gift-certificate/certificate-checkbox/certificate-checkbox.js
Labels: bug, FrontEnd part

#2295 now tooltip for feedback icon works correctly
  src/pages/product-details/comments/comments-item/comments-item.js
  src/pages/product-details/comments/comments-item/comments-item.styles.js
Labels: bug, FrontEnd part

#2298 Changed position and distance between news blocks
  src/pages/news/news-item/news-item.style.js
Labels: bug, FrontEnd part
