Repository ita-social-projects/horondi_client_fe, pull requests merged in 2022-03, with the labels that each got.

#1824 Bugfix/1823/fix routing for my certificates
  src/routes/routes.js
Labels: bug, FrontEnd part

#1762 impletent custom hook for wishlist
  src/containers/wishlist-header/tests/wishlist-header.spec.js
  src/containers/wishlist-header/wishlist-header.js
  src/hooks/tests/use-wishlist.spec.js
  src/hooks/tests/use-wishlist.variables.js
  src/hooks/use-add-product-to-wishlist-handler.js
  src/hooks/use-wishlist.js
  src/pages/images-constructor/constructor-sumbit/constructor-submit.js
  src/pages/product-details/product-details.js
  src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
  src/pages/product-details/tests/product-details.spec.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
  src/pages/wishlist/filled-wishlist/tests/filled-wishlist.spec.js
  src/pages/wishlist/operations/wishlist.queries.js
  src/pages/wishlist/tests/wishlist.spec.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/pages/wishlist/wishlist.js
  src/redux/common-store/common.actions.js
  src/redux/common-store/common.reducer.js
  src/redux/common-store/common.types.js
  src/redux/user/tests/user.mocks.js
  src/redux/user/tests/user.sagas.spec.js
  src/redux/user/user.operations.js
  src/redux/user/user.sagas.js
  src/services/local-storage.service.js
Labels: FrontEnd part, feature

#1829 Fix improper error messages
  src/configs/regexp.js
  src/locales/en/error.json
  src/locales/ua/error.json
  src/validators/checkout.js
  src/validators/profile-page.js
Labels: bug, FrontEnd part

#1831 Fixed line overflow in comments
  src/pages/product-details/comments/comments-item/comments-item.styles.js
  src/pages/product-details/comments/comments-item/reply-comments-item/reply-comments-item.styles.js
Labels: bug, good first issue, UI, FrontEnd part

#1828 Fixed view of products
  src/components/model-item/model-item.js
  src/components/model-item/model-item.style.js
  src/pages/home/models-list/models-list.style.js
Labels: good first issue, UI, FrontEnd part

#1833 BugFix/1827/apply-promoCode-to-product-from-wishList
  src/pages/product-details/operations/product-details.queries.js
Labels: bug

#1820 Feature/1801/save user configs
  src/configs/index.js
  src/containers/header-profile/header-profile.js
  src/containers/header-profile/profile.queries.js
  src/containers/header-profile/tests/header-profile.spec.js
  src/containers/language/constants.js
  src/containers/language/language-component.js
  src/locales/en/error.json
  src/locales/ua/error.json
  src/redux/language/language.reducer.js
  src/redux/language/test/__snapshots__/language.reducer.test.js.snap
  src/redux/language/test/language.reducer.test.js
  src/redux/user/tests/user.mocks.js
  src/redux/user/tests/user.sagas.spec.js
  src/redux/user/user.operations.js
  src/redux/user/user.sagas.js
Labels: FrontEnd part

#1852 Redesign/1848/Column code does not meet the mockup
  src/containers/my-certificates/cetrificate-item/certificate-item.styles.js
Labels: UI, FrontEnd part

#1847 ActiveMessenger component tests
  package-lock.json
  package.json
  src/containers/chat/active-messenger/tests/active-messenger.spec.js
Labels: FrontEnd part, test

#1835 Fixed verified purchase icon in reply
  src/pages/product-details/comments/comments-item/reply-comments-item/reply-comments-item.js
  src/pages/product-details/comments/comments-item/reply-comments-item/reply-comments-item.styles.js
Labels: good first issue, UI, FrontEnd part, priority: low

#1846 Redesign/1797/current language and currency should be highlighted
  src/containers/currency/currency-component.js
  src/containers/currency/currency.styles.js
  src/containers/language/language-component.js
  src/containers/language/language.styles.js
Labels: UI, FrontEnd part, redesign

#1863 fixed incorrect view of products on mobiles
  src/pages/home/models-list/models-list.js
  src/pages/home/models-list/models-list.style.js
Labels: FrontEnd part, redesign

#1861 Refactor/1836/refactor test for PathBack component
  src/containers/orders/cart/path-back/tests/__snapshots__/path-back.test.js.snap
  src/containers/orders/cart/path-back/tests/path-back.test.js
  src/tests/unit/containers/orders/cart/path-back/path-back.test.js
Labels: refactoring, FrontEnd part, test

#1864 Test/1842/tests for currency component component
  src/containers/currency/tests/currency-component.spec.js
  src/tests/unit/containers/currency/currency-component.spec.js
Labels: FrontEnd part, test

#1857 refactor test for ProductFilterContainer component
  src/containers/products-filters-container/tests/product-filter-container.spec.js
  src/tests/unit/containers/products-filters-container/products-filters-container.spec.js
Labels: FrontEnd part, test
