Repository ita-social-projects/horondi_client_fe, pull requests merged in 2022-12, with the labels that each got.

#2303 [Cart] Button 'go to checkout' change width when price change
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
Labels: FrontEnd part

#2307 Bug/2306/Fix styles in reply form
  src/pages/product-details/comments/comments-item/reply-form/reply-form.styles.js
Labels: bug, UI, FrontEnd part

#2274 Bug/2163/fix console warning in use-product-filters hook
  src/configs/index.js
  src/hooks/use-product-filters/use-product-filters.js
Labels: bug, FrontEnd part

#2311 fix button and account page
  src/pages/profile-page/profile-page.js
  src/utils/handle-profile-page.js
Labels: bug, FrontEnd part

#2331 now price filter removes from url when you set it by input field
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-filter/product-list-filter.js
  src/pages/product-list-page/product-list-page.js
Labels: bug, FrontEnd part

#2317 fixed current page color in dark theme
  src/pages/product-list-page/product-list-page.styles.js
Labels: bug, FrontEnd part

#2326 Сhanged styles across whole login flow
  src/components/app-text-field/app-text-field.js
  src/components/app-text-field/app-text-field.styles.js
  src/components/app-text-field/index.js
  src/components/auth-form/auth-form-heading/auth-form-heading.styles.js
  src/components/auth-form/auth-form-wrapper/auth-form-wrapper.js
  src/components/auth-form/auth-form-wrapper/auth-form-wrapper.styles.js
  src/locales/en/register.json
  src/locales/ua/error.json
  src/locales/ua/new-password.json
  src/pages/login/login.js
  src/pages/login/login.styles.js
  src/pages/new-password/new-password.js
  src/pages/new-password/new-password.styles.js
  src/pages/recovery/recovery.js
  src/pages/recovery/recovery.styles.js
  src/pages/register/register-from/register-form.js
  src/pages/register/register-from/register-form.styles.js
  src/pages/register/register.js
  src/pages/register/register.styles.js
  src/pages/register/tests/register.test.js
  src/tests/unit/components/auth-form/auth-form-wrapper/auth-form-wrapper.spec.js
  src/tests/unit/pages/register/register-form.spec.js
  src/utils/handle-new-password.js
  src/validators/new-password.js
Labels: FrontEnd part

#2336 fix spaces between products
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/orders/order/your-order/order-item/order-item.js
Labels: bug, FrontEnd part

#2337 Fix "My certificate" page adaptivity
  src/components/app/app-theme/app.typography.js
  src/components/table/TableBodyRow/TableBodyRow.js
  src/components/table/table.styles.js
  src/containers/my-certificates/certificate-table/certificate-table.js
  src/containers/my-certificates/certificate-table/certificate-table.styles.js
  src/containers/my-certificates/filled-certificates/filled-certificates.js
  src/containers/my-certificates/filled-certificates/filled-certificates.styles.js
  src/containers/my-certificates/notification-certificate-ends/notification-certificate-ends.styles.js
  src/containers/orders/order-history/order-history-pagination/order-history-pagination.style.js
  src/pages/order-history/constants.js
  src/tests/unit/containers/my-certificates/certificate-table/certificate-table.spec.js
  src/tests/unit/containers/my-certificates/filled-certificates/filled-certificates.spec.js
  src/tests/unit/pages/my-certificates/my-certificates.spec.js
Labels: bug, FrontEnd part

#2343 fixed images adaptivity on horondi style section
  src/pages/home/our-looks/our-looks.style.js
Labels: bug, FrontEnd part

#2334 changed styles in certificate thanks page
  src/pages/certificate-thanks-page/certificate-thanks-card/certificate-thanks-card.styles.js
  src/pages/certificate-thanks-page/certificate-thanks-page.js
  src/pages/certificate-thanks-page/certificate-thanks-page.styles.js
Labels: bug, FrontEnd part

#2344 Fixed titles on all pages. to similar design
  src/components/page-title/index.js
  src/components/page-title/page-title.js
  src/components/page-title/page-title.styles.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/checkout/checkout.styles.js
  src/containers/my-certificates/certificate-table/certificate-table.js
  src/containers/my-certificates/certificate-table/certificate-table.styles.js
  src/containers/my-certificates/filled-certificates/filled-certificates.styles.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/containers/orders/cart/path-back/path-back.js
  src/containers/orders/cart/path-back/path-back.styles.js
  src/containers/orders/order-history/order-history-item/order-history-item.styles.js
  src/containers/orders/order-history/order-history-pagination/order-history-pagination.style.js
  src/containers/orders/order/order-table/order-table.js
  src/containers/orders/order/order-table/order-table.styles.js
  src/containers/search-bar/tests/search-bar.spec.js
  src/pages/about-us/about-us.js
  src/pages/about-us/about-us.styles.js
  src/pages/about-us/tests/about-us.spec.js
  src/pages/answers-questions-page/answers-questions-page.js
  src/pages/answers-questions-page/answers-questions-page.style.js
  src/pages/answers-questions-page/tests/answers-questions-page.test.js
  src/pages/business-page/business-page.js
  src/pages/business-page/business-page.style.js
  src/pages/contacts/contacts.js
  src/pages/contacts/contacts.styles.js
  src/pages/gift-certificate/gift-certificate.js
  src/pages/gift-certificate/gift-certificate.styles.js
  src/pages/images-constructor/images-constructor.js
  src/pages/images-constructor/images-constructor.style.js
  src/pages/images-constructor/tests/images-constructor.spec.js
  src/pages/materials/materials.js
  src/pages/materials/materials.style.js
  src/pages/news/news-page/news-page.js
  src/pages/news/news-page/news-page.style.js
  src/pages/order-history/order-history.js
  src/pages/order-history/order-history.styles.js
  src/pages/product-details/product-path/product-path.js
  src/pages/product-details/product-path/product-path.styles.js
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-list-page.styles.js
  src/pages/profile-page/profile-page.js
  src/pages/profile-page/profile-page.styles.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.styles.js
  src/tests/unit/pages/business-page/business-page.spec.js
  src/tests/unit/pages/contacts/contacts.spec.js
  src/tests/unit/pages/gift-certificate/gift-certificate.spec.js
Labels: bug, FrontEnd part

#2345 Fixed content position, when using slider
  src/components/scroll-bar/scroll-bar.js
  src/components/scroll-bar/scroll-bar.styles.js
  src/components/scroll-bar/tests/scroll-bar.spec.js
  src/components/scroll-bar/tests/scroll-bar.variables.js
Labels: bug, FrontEnd part

#2348 Changed styles for order history
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.styles.js
Labels: bug, FrontEnd part

#2349 Fix adaptivity in catalog
  src/components/page-title/page-title.js
  src/components/page-title/page-title.styles.js
  src/containers/header-right-bar/header-right-bar.styles.js
  src/containers/orders/order/order-table/order-table.js
  src/containers/products-filters-container/products-filters-container.styles.js
  src/containers/search-bar/search-bar.styles.js
  src/pages/product-list-page/count-per-page/count-per-page.styles.js
  src/pages/product-list-page/product-list-filter/product-list-filter.styles.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/product-list-page/product-list-item/product-list-item.style.js
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-list-page.styles.js
  src/pages/product-list-page/product-sort/product-sort.js
  src/pages/product-list-page/product-sort/product-sort.styles.js
  src/pages/product-list-page/tests/product-sort.spec.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
Labels: bug, FrontEnd part

#2351 Added get option selected for autocomplete
  src/containers/checkout/checkout-form/delivery/nova-post/nova-post.js
  src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/ukrpost-and-courier.js
  src/containers/checkout/checkout-form/delivery/worldwide/tests/worldwide.spec.js
  src/containers/checkout/checkout-form/delivery/worldwide/worldwide.js
  src/utils/handle-delivery.js
Labels: bug, FrontEnd part

#2347 bugFix/2299/constructor-sizes-in-cart
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/operations/getConstructorByModel.query.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.styles.js
  src/hooks/tests/use-cart.spec.js
  src/hooks/tests/use-cart.variables.js
  src/hooks/use-cart.js
  src/pages/images-constructor/constructor-sumbit/constructor-submit.js
  src/pages/images-constructor/constructor-sumbit/tests/constructor-submit.spec.js
  src/pages/images-constructor/constructor-sumbit/tests/constructor.variables.js
  src/pages/images-constructor/images-constructor.js
  src/pages/images-constructor/tests/images-constructor.spec.js
  src/pages/images-constructor/use-constructor-loader.js
  src/pages/order-history/operations/order-history.queries.js
  src/pages/order-history/order-history.js
  src/utils/checkout.js
Labels: bug, FrontEnd part

#2352 fix border in cancel button
  src/pages/product-details/comments/comments.styles.js
Labels: bug, FrontEnd part

#2355 Should have gap in news section between pagination and footer
  src/pages/news/news-item/news-item.style.js
  src/pages/news/news-page/news-page.js
  src/pages/news/news-page/news-page.style.js
  src/pages/order-history/order-history.styles.js
Labels: bug, FrontEnd part

#2356 Bugfix/fix adaptivity
  src/components/app-footer/app-footer.styles.js
  src/components/app-header/app-header.js
  src/components/app-header/app-header.styles.js
  src/components/app/app-theme/app.typography.js
  src/components/auth-form/auth-form-button/auth-form-button.js
  src/components/auth-form/auth-form-heading/auth-form-heading.styles.js
  src/components/confirm-dialog/confirm-dialog.styles.js
  src/components/header-notification-bar/header-notification-bar.styles.js
  src/containers/chat/chat.style.js
  src/containers/footer-lists/footer-lists.js
  src/containers/footer-lists/footer-lists.styles.js
  src/containers/my-certificates/notification-certificate-ends/notification-certificate-ends.styles.js
  src/containers/orders/cart/cart-item/cart-item.styles.js
  src/containers/orders/order/empty-order/empty-order.styles.js
  src/containers/orders/order/order-table/order-table.styles.js
  src/containers/social-links/social-links.styles.js
  src/locales/en/wishlist.json
  src/locales/ua/wishlist.json
  src/pages/home/slider/slider-home-page.style.js
  src/pages/product-details/constants.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.styles.js
  src/pages/product-details/similar-products/similar-products.js
  src/pages/product-details/similar-products/similar-products.styles.js
  src/pages/profile-page/profile-page.js
  src/pages/wishlist/empty-wishlist/empty-wishlist.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.styles.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/pages/wishlist/wishlist-item/wishlist-item.styles.js
  src/routes/routes.style.js
  src/tests/unit/pages/profile-page/profile-page.spec.js
Labels: bug, FrontEnd part

#2358 removed sending email from thanks page
  src/containers/checkout/checkout-form/checkout-form.js
  src/pages/thanks-page/thanks-page.js
  src/redux/order/order.actions.js
  src/redux/order/order.operations.js
  src/redux/order/order.sagas.js
  src/redux/order/order.types.js
  src/redux/order/tests/order.actions.test.js
  src/redux/order/tests/order.sagas.test.js
  src/redux/order/tests/order.variables.js
  src/tests/unit/pages/thanks-page/thanks-page.spec.js
Labels: bug, FrontEnd part

#2360 Changed styles in product, added adaptivity
  src/components/app-footer/app-footer.styles.js
  src/containers/orders/order/empty-order/empty-order.js
  src/containers/orders/order/empty-order/empty-order.styles.js
  src/containers/orders/order/order-table/order-table.styles.js
  src/pages/product-details/comments/comments.styles.js
  src/pages/product-details/constants.js
  src/pages/product-details/product-description/product-description.styles.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-details.styles.js
  src/pages/product-details/product-images/product-images.js
  src/pages/product-details/product-images/product-images.styles.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-info/product-info.styles.js
  src/pages/product-details/product-info/tests/product-info.test.js
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-details/product-sizes/product-sizes.styles.js
  src/pages/product-details/product-submit/product-submit.styles.js
  src/pages/product-details/similar-products/similar-products.styles.js
  src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
  src/pages/product-details/tests/product-details.spec.js
  src/pages/product-details/tests/product-images.spec.js
  src/pages/product-list-page/product-list-item/product-list-item.style.js
  src/utils/productDetails.js
Labels: FrontEnd part

#2362 The selected pagination element has a correct border on the catalog page and order history.
  src/containers/orders/order-history/order-history-pagination/order-history-pagination.style.js
  src/pages/product-list-page/product-list-page.styles.js
Labels: bug, FrontEnd part

#2364 disable button when user don`t choose certificate
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/pages/gift-certificate/gift-certificate.js
  src/pages/gift-certificate/gift-certificate.styles.js
Labels: bug, FrontEnd part

#2373 Change style of rating stars
  src/components/model-item/model-item.js
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/chat/chat.style.js
  src/containers/footer-lists/footer-lists.js
  src/containers/my-certificates/empty-certificates/empty-certificates.js
  src/containers/my-certificates/empty-certificates/empty-certificates.styles.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/locales/en/certificate.json
  src/locales/en/product.json
  src/locales/ua/product.json
  src/pages/home/categories-list/categories-list.js
  src/pages/home/categories-list/category-item/category-item.js
  src/pages/home/models-list/models-list.js
  src/pages/product-details/product-description/product-description.js
  src/pages/product-details/product-description/product-description.styles.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-details.styles.js
  src/pages/product-details/product-images/product-images.styles.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-info/product-info.styles.js
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-details/product-sizes/product-sizes.styles.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.styles.js
  src/pages/product-details/similar-products/similar-products.js
  src/pages/product-details/similar-products/similar-products.styles.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/product-list-page/product-list-item/product-list-item.style.js
  src/tests/unit/pages/home/categories-list/categories-list.spec.js
  src/tests/unit/pages/product-details/similar-products/similar-products-item/similiar-products-item.spec.js
  src/utils/productDetails.js
Labels: FrontEnd part

#2374 Fixed bugs with comments
  src/locales/en/product.json
  src/locales/ua/product.json
  src/pages/product-details/comments/comments.js
  src/pages/product-details/comments/comments.styles.js
  src/tests/unit/pages/product-details/comments.spec.js
  src/utils/handle-comments.js
Labels: bug, FrontEnd part

#2377 add certificate rule
  src/locales/en/certificate.json
  src/locales/ua/certificate.json
Labels: FrontEnd part

#2376 Change style of some text on Home page
  src/components/model-item/model-item.style.js
  src/pages/home/categories-list/category-item/category-item.style.js
Labels: bug, FrontEnd part

#2378 Added favorite icon to product in catalog
  src/components/add-to-wishlist-icon/add-to-wishlist-icon.js
  src/components/add-to-wishlist-icon/add-to-wishlist-icon.styles.js
  src/components/add-to-wishlist-icon/index.js
  src/components/auth-form/auth-form-button/auth-form-button.js
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/chat/active-messenger/tests/active-messenger.spec.js
  src/containers/chat/chat.js
  src/containers/chat/chat.style.js
  src/containers/chat/mail-form/tests/mail-form.spec.js
  src/containers/chat/tests/chatLoader.spec.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-info/product-info.styles.js
  src/pages/product-list-page/operations/product-list.queries.js
  src/pages/product-list-page/product-list-filter/product-list-filter.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/product-list-page/product-list-item/product-list-item.style.js
  src/pages/profile-page/avatar/avatar.styles.js
  src/pages/profile-page/profile-page.js
  src/pages/profile-page/profile-page.styles.js
  src/tests/unit/pages/product-list-page/product-list-page.spec.js
  src/tests/unit/pages/product-list-page/product-list-page.variables.js
Labels: FrontEnd part

#2381 Changed styles in header search
  src/components/star-rating/star-rating.js
  src/containers/chat/chat.js
  src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.js
  src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.styles.js
  src/locales/en/product.json
  src/locales/ua/product.json
  src/pages/product-details/product-details.styles.js
  src/pages/product-details/product-sizes/product-sizes.styles.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.styles.js
  src/tests/unit/containers/search-bar-list-item/search-bar-list-item.spec.js
  src/tests/unit/containers/search-bar-list-item/search-bar-list-item.variables.js
  src/tests/unit/pages/product-details/similar-products/similar-products-item/similiar-products-item.spec.js
Labels: FrontEnd part

#2389 Values delete when change delivery type
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/delivery-type/delivery-type.js
  src/containers/checkout/checkout-form/delivery/delivery.js
  src/utils/checkout.js
Labels: bug, FrontEnd part

#2390 add back button to business pages
  src/components/back-button/back-button.js
  src/components/back-button/back-button.styles.js
  src/components/back-button/index.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/social-links/const.js
  src/locales/en/footer.json
  src/locales/ua/footer.json
  src/pages/about-us/about-us.js
  src/pages/answers-questions-page/answers-questions-page.js
  src/pages/business-page/business-page.js
  src/pages/business-page/business-page.style.js
  src/tests/unit/containers/footer-lists/footer-lists.spec.js
Labels: FrontEnd part

#2392 fix code smells on client
  src/containers/sidebar/sidebar-item/sidebar-item.js
  src/pages/product-list-page/product-list-page.js
  src/pages/register/register-from/register-form.js
Labels: FrontEnd part
