Repository ita-social-projects/horondi_client_fe, pull requests merged in 2022-05, with the labels that each got.

#1911 Fixed facebook messenger bugs
  package.json
  src/containers/chat/chat.js
  src/containers/chat/chat.style.js
  src/containers/chat/tests/chat.spec.js
  src/index.css
Labels: bug, UI, FrontEnd part

#1919 was_fixed-slider_doesnt_move_to_our_model_section
  src/pages/home/models-list/models-list.style.js
Labels: bug, FrontEnd part, redesign

#1929 [Cart] New product added to the Cart is located at the bottom of the list
  src/hooks/use-cart.js
Labels: FrontEnd part

#1918 Feature/1568/worldwide delivery autocomplete
  src/components/tab-panel/index.js
  src/components/tab-panel/tab-panel.js
  src/configs/index.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/checkout/checkout-form/delivery-type/delivery-type.js
  src/containers/checkout/checkout-form/delivery-type/delivery-type.styles.js
  src/containers/checkout/checkout-form/delivery-type/tests/delivery-type.test.js
  src/containers/checkout/checkout-form/delivery/delivery.js
  src/containers/checkout/checkout-form/delivery/nova-post/nova-post.styles.js
  src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/ukrpost-and-courier.styles.js
  src/containers/checkout/checkout-form/delivery/worldwide/const.js
  src/containers/checkout/checkout-form/delivery/worldwide/index.js
  src/containers/checkout/checkout-form/delivery/worldwide/tests/worldwide.spec.js
  src/containers/checkout/checkout-form/delivery/worldwide/tests/worldwide.variables.js
  src/containers/checkout/checkout-form/delivery/worldwide/worldwide.js
  src/containers/checkout/checkout-form/delivery/worldwide/worldwide.styles.js
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/locales/en/checkout.json
  src/locales/ua/checkout.json
  src/services/tests/worldwide-delivery.service.spec.js
  src/services/tests/worldwide-delivery.service.variables.js
  src/services/worldwide-delivery.service.js
  src/tests/unit/containers/delivery/delivery.spec.js
  src/tests/unit/containers/delivery/delivery.variables.js
  src/utils/checkout.js
  src/validators/checkout.js
Labels: FrontEnd part

#1932 The 'E-mail' field allows more that 60 characters to enter
  src/configs/regexp.js
Labels: FrontEnd part

#1934 Bugfix/1890/inexpedient pagination after searching througth search field
  src/containers/header-right-bar/header-right-bar.js
  src/containers/search-bar-list/search-bar-list.js
  src/containers/search-bar-list/search-bar-list.styles.js
  src/containers/search-bar/SearchIcon.js
  src/containers/search-bar/search-bar.js
  src/containers/search-bar/tests/search-bar.spec.js
  src/containers/search-bar/tests/search-bar.variables.js
  src/hooks/tests/use-debounce.spec.js
  src/hooks/use-debounce.js
  src/hooks/use-product-filters/tests/use-product-filters.spec.js
  src/hooks/use-product-filters/tests/use-product-filters.variables.js
  src/hooks/use-product-filters/use-product-filters.js
  src/pages/product-list-page/product-list-filter/hot-item-filter/hot-item-filter.js
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-sort/product-sort.js
  src/tests/unit/pages/product-list-page/product-list-page.spec.js
  src/tests/unit/pages/product-list-page/product-list-page.variables.js
Labels: bug, refactoring, FrontEnd part, test

#1939 ukrainian language on load
  src/containers/language/language-component.js
Labels: bug, FrontEnd part

#1938 Feature/1906/materials page
  src/locales/en/index.js
  src/locales/en/materialsPage.json
  src/locales/ua/index.js
  src/locales/ua/materialsPage.json
  src/pages/materials/constants.js
  src/pages/materials/materials-bottom/constants.js
  src/pages/materials/materials-bottom/index.js
  src/pages/materials/materials-bottom/materials-bottom.js
  src/pages/materials/materials-bottom/materials-bottom.style.js
  src/pages/materials/materials-textile/index.js
  src/pages/materials/materials-textile/materials-textile.js
  src/pages/materials/materials-textile/materials-textile.style.js
  src/pages/materials/materials.js
  src/pages/materials/materials.style.js
  src/pages/materials/operations/getAllPatterns.queries.js
  src/pages/materials/slider/constants.js
  src/pages/materials/slider/slider.js
  src/pages/materials/slider/slider.styles.js
  src/pages/materials/tests/materials.spec.js
  src/tests/unit/pages/materials/materials-bottom/materials-bottom.spec.js
  src/tests/unit/pages/materials/materials-textile/materials-textile.spec.js
  src/tests/unit/pages/materials/materials.spec.js
  src/tests/unit/pages/materials/slider/slider.spec.js
  src/tests/unit/pages/materials/slider/slider.variables.js
Labels: FrontEnd part, feature

#1946 Bug fix/1935/regisatration page/user can register with an invalid email
  src/validators/register.js
Labels: bug, FrontEnd part

#1947 Style of search results does not match the overall style of the web-site
  src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.styles.js
  src/containers/search-bar/search-bar.js
Labels: bug, FrontEnd part

#1944 Absence of 'Shop now' button
  src/locales/en/home.json
  src/locales/ua/home.json
  src/pages/home/slider/slider-home-page.js
Labels: bug, FrontEnd part

#1945 fix logout
  src/redux/user/user.sagas.js
Labels: bug, FrontEnd part

#1965 Hotfix/fix wishlist and order history
  src/containers/orders/order-history/order-history-item/order-history-item.js
  src/pages/order-history/operations/order-history.queries.js
  src/pages/wishlist/operations/wishlist.mutations.js
  src/pages/wishlist/operations/wishlist.queries.js
  src/redux/user/user.operations.js
  src/tests/unit/components/order-history-item/order-history-item.variables.js
Labels: bug
