Repository ita-social-projects/horondi_client_fe, pull requests merged in 2022-02, with the labels that each got.

#1671 Feature/1578/create page my certificates
  src/components/modal/modal.js
  src/components/modal/modal.styles.js
  src/configs/index.js
  src/containers/my-certificates/certificate-table/certificate-table.js
  src/containers/my-certificates/cetrificate-item/certificate-item.js
  src/containers/my-certificates/cetrificate-item/certificate-item.styles.js
  src/containers/my-certificates/cetrificate-item/images.js
  src/containers/my-certificates/empty-certificates/empty-certificates.js
  src/containers/my-certificates/empty-certificates/empty-certificates.styles.js
  src/containers/my-certificates/empty-certificates/index.js
  src/containers/my-certificates/filled-certificates/filled-certificates.js
  src/containers/my-certificates/filled-certificates/filled-certificates.styles.js
  src/images/certificates/CertificateImages.js
  src/images/certificates/certificate-1000.png
  src/images/certificates/certificate-1500.png
  src/images/certificates/certificate-500.png
  src/images/certificates/certificateCodeCopy.js
  src/images/certificates/emptyCertificateDark.js
  src/images/certificates/emptyCertificateLight.js
  src/locales/en/certificate.json
  src/locales/en/common.json
  src/locales/ua/certificate.json
  src/locales/ua/common.json
  src/pages/my-certificates/certificates.js
  src/pages/my-certificates/index.js
  src/pages/my-certificates/my-certificates.js
  src/pages/my-certificates/my-certificates.styles.js
  src/pages/my-certificates/operations/my-certificates.queries.js
  src/tests/unit/containers/my-certificates/certificate-item/certificate-item.spec.js
  src/tests/unit/containers/my-certificates/certificate-item/certificate-item.variable.js
  src/tests/unit/containers/my-certificates/certificate-table/certificate-table.spec.js
  src/tests/unit/containers/my-certificates/certificate-table/certificate-table.variables.js
  src/tests/unit/containers/my-certificates/empty-certificates/empty-certificates.spec.js
  src/tests/unit/containers/my-certificates/filled-certificates/filled-certificates.spec.js
  src/tests/unit/containers/my-certificates/filled-certificates/filled-certificates.variables.js
  src/tests/unit/pages/my-certificates/my-certificates.spec.js
Labels: FrontEnd part, Functional, feature

#1653 error fild to city, street, building and apartment was added
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/configs/regexp.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/checkout/checkout-form/delivery-type/delivery-type.js
  src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/ukrpost-and-courier.js
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/containers/checkout/checkout-form/tests/checkout-form.variables.js
  src/containers/orders/order/your-order/your-order.js
  src/locales/en/error.json
  src/locales/ua/error.json
  src/pages/profile-page/profile-page.js
  src/utils/checkout.js
  src/validators/checkout.js
Labels: bug, FrontEnd part

#1707 Fix custom support chat
  src/configs/regexp.js
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/chat/chat.style.js
  src/containers/chat/constants.js
  src/locales/en/checkout.json
  src/locales/en/error.json
Labels: bug, FrontEnd part, Functional

#1716 fixed image sizes
  src/pages/product-details/operations/product-details.queries.js
  src/pages/product-details/product-images/product-images.js
  src/pages/product-details/product-info/product-info.js
Labels: bug, FrontEnd part

#1722 fixed small bugs
  src/locales/en/certificate.json
  src/locales/en/certificates.json
  src/locales/en/home.json
  src/locales/en/index.js
  src/locales/en/product-list-page.json
  src/locales/en/productList.json
  src/locales/ua/certificate.json
  src/locales/ua/certificates.json
  src/locales/ua/home.json
  src/locales/ua/index.js
  src/locales/ua/product-list-page.json
  src/locales/ua/productList.json
  src/pages/gift-certificate/certificate-checkbox/certificate-checkbox.js
  src/pages/gift-certificate/gift-certificate.js
  src/pages/home/contructor-preview/constructor-preview.js
  src/pages/product-details/comments/comments.js
  src/pages/product-details/comments/comments.styles.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
Labels: bug, FrontEnd part

#1720 Feature/1580/pagination-myCertificates
  src/containers/my-certificates/certificate-table/certificate-table.js
  src/containers/my-certificates/cetrificate-item/certificate-item.js
  src/containers/my-certificates/filled-certificates/filled-certificates.js
  src/containers/my-certificates/filled-certificates/filled-certificates.styles.js
  src/pages/my-certificates/my-certificates.js
  src/pages/my-certificates/operations/my-certificates.queries.js
  src/tests/unit/containers/my-certificates/certificate-item/certificate-item.variable.js
  src/tests/unit/pages/my-certificates/my-certificates.spec.js
  src/tests/unit/pages/my-certificates/my-certificates.variables.js
Labels: FrontEnd part

#1684 test/1556/orderTable
  src/containers/orders/order/order-table/tests/__snapshots__/order-table.test.js.snap
  src/containers/orders/order/order-table/tests/order-table.test.js
  src/containers/orders/order/order-table/tests/order-table.variables.js
Labels: FrontEnd part

#1725 hotfix/1591/burgerMenu_scroll
  src/containers/social-links/social-links.styles.js
Labels: bug, UI

#1726 hotfix-of-bugfix/1591/burgerMenuHeight
  src/containers/sidebar/sidebar.styles.js
Labels: bug, UI

#1730 Bugfix/1729/empty certificate page doesnt open
  src/pages/my-certificates/my-certificates.js
Labels: bug

#1738 BugFix/1096/fix-image-cover
  src/pages/product-list-page/product-list-item/product-list-item.style.js
Labels: bug

#1735 bugfix/1591/footerSocial
  src/containers/social-links/social-links.js
  src/containers/social-links/social-links.styles.js
Labels: bug, UI

#1706 Add validation to filds house and flat in checkout
  src/locales/en/error.json
  src/validators/checkout.js
Labels: bug, FrontEnd part

#1717 bugfix1081fix-search-bar
  src/configs/index.js
  src/configs/regexp.js
  src/containers/orders/order/empty-order/empty-order.js
  src/containers/orders/order/empty-order/empty-order.styles.js
  src/containers/orders/order/empty-order/tests/__snapshots__/empty-order.test.js.snap
  src/images/backpack-icon.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-list-page.styles.js
  src/pages/wishlist/empty-wishlist/empty-wishlist.js
  src/tests/unit/pages/product-list-page/product-list-page.spec.js
  src/tests/unit/pages/product-list-page/product-list-page.variables.js
Labels: bug, FrontEnd part

#1737 bugfix 1736 loader on product-list
  src/tests/unit/pages/product-list-page/product-list-page.spec.js
Labels: FrontEnd part

#1703 Feature/1666/connect promoCode to cart
  package-lock.json
  package.json
  src/components/number-input/number-input.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/containers/checkout/checkout-form/tests/checkout-form.variables.js
  src/containers/checkout/checkout.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/cart-item/cart-item.styles.js
  src/containers/orders/cart/cart-item/tests/cart-item.spec.js
  src/containers/orders/cart/cart-item/tests/cart-item.variables.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/containers/orders/cart/filled-cart/tests/filled-cart.spec.js
  src/containers/orders/cart/filled-cart/tests/filled-cart.variables.js
  src/containers/orders/operations/getPromoCodeByCode.queries.js
  src/containers/orders/operations/order.queries.js
  src/containers/orders/order/order-table/order-table.js
  src/containers/orders/order/order-table/tests/order-table.variables.js
  src/containers/orders/order/your-order/order-item/order-item.js
  src/containers/orders/order/your-order/your-order.js
  src/hooks/tests/use-cart.spec.js
  src/hooks/tests/use-cart.variables.js
  src/hooks/use-cart.js
  src/locales/en/cart.json
  src/locales/ua/cart.json
  src/pages/product-details/comments/comments-item/reply-form/reply-form.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/product-submit/tests/product-details.variables.js
  src/pages/wishlist/wishlist-item/tests/wishlist-item.spec.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/redux/order/order.sagas.js
  src/tests/unit/components/your-order/your-order.spec.js
  src/tests/unit/components/your-order/your-order.variables.js
Labels: FrontEnd part

#1731 bugfix/1095/theme-color-changes-from-black-to-white-after-logout
  src/containers/header-profile/header-profile.js
Labels: bug

#1742 bugfix/1100/phoneValidation
  src/configs/regexp.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/locales/en/error.json
  src/locales/ua/error.json
  src/pages/profile-page/profile-page.js
  src/pages/thanks-page/thanks-card/thanks-card.js
  src/utils/checkout.js
  src/validators/checkout.js
Labels: bug, refactoring, Functional, validation

#1749 added main container
  src/components/app-footer/app-footer.js
  src/components/app-footer/app-footer.styles.js
  src/components/app-header/app-header.js
  src/components/app-header/tests/app-header.spec.js
  src/components/app/app.js
  src/components/app/app.styles.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/checkout/checkout-form/delivery-type/delivery-type.js
  src/containers/checkout/checkout-form/delivery-type/delivery-type.styles.js
  src/containers/checkout/checkout-form/delivery/nova-post/nova-post.styles.js
  src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/ukrpost-and-courier.js
  src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/ukrpost-and-courier.styles.js
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/containers/my-certificates/certificate-table/certificate-table.js
  src/containers/my-certificates/filled-certificates/filled-certificates.styles.js
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/containers/orders/order-history/order-history-item/order-history-item.styles.js
  src/pages/answers-questions-page/answers-questions-page.js
  src/pages/answers-questions-page/answers-questions-page.style.js
  src/pages/business-page/business-page.js
  src/pages/business-page/business-page.style.js
  src/pages/cart/cart.js
  src/pages/cart/cart.styles.js
  src/pages/contacts/contacts.js
  src/pages/gift-certificate/gift-certificate.js
  src/pages/gift-certificate/gift-certificate.styles.js
  src/pages/home/models-list/models-list.js
  src/pages/home/models-list/models-list.style.js
  src/pages/home/slider/slider-home-page.js
  src/pages/home/slider/slider-home-page.style.js
  src/pages/images-constructor/images-constructor.js
  src/pages/images-constructor/images-constructor.style.js
  src/pages/materials/materials.js
  src/pages/materials/materials.style.js
  src/pages/my-certificates/my-certificates.js
  src/pages/my-certificates/my-certificates.styles.js
  src/pages/news/news-detail/news-detail.js
  src/pages/news/news-detail/news-detail.style.js
  src/pages/news/news-page/news-page.js
  src/pages/news/news-page/news-page.style.js
  src/pages/order-history/order-history.js
  src/pages/order-history/order-history.styles.js
  src/pages/product-details/comments/comments.styles.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-details.styles.js
  src/pages/product-details/product-path/product-path.styles.js
  src/pages/product-details/similar-products/similar-products.styles.js
  src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
  src/pages/product-details/tests/product-details.spec.js
  src/pages/profile-page/profile-page.js
  src/pages/profile-page/profile-page.styles.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.styles.js
  src/pages/wishlist/tests/wishlist.spec.js
  src/pages/wishlist/wishlist.js
  src/pages/wishlist/wishlist.styles.js
  src/tests/unit/pages/my-certificates/my-certificates.spec.js
Labels: FrontEnd part, design

#1763 adaptive design for constructor page
  src/pages/images-constructor/images-constructor.style.js
Labels: FrontEnd part, design

#1766 adaptive design for wishlist & footer
  src/components/app-footer/app-footer.styles.js
  src/containers/footer-lists/footer-lists.styles.js
  src/containers/social-links/social-links.styles.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.styles.js
  src/pages/wishlist/wishlist-item/wishlist-item.styles.js
Labels: FrontEnd part, design

#1772 Design/adaptive for Business pages
  src/pages/business-page/business-page.style.js
  src/pages/materials/materials.style.js
Labels: FrontEnd part, design

#1774 Refactor/1760/make adaptive design for certificates page
  src/components/number-input/number-input.styles.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/cart-item/cart-item.styles.js
  src/containers/orders/cart/filled-cart/filled-cart.styles.js
  src/pages/gift-certificate/gift-certificate.styles.js
Labels: refactoring, FrontEnd part, priority: medium

#1775 Feature/1750/update images in slider on main page
  src/images/bg3.jpg
Labels: FrontEnd part

#1771 Refactor/1758/make adaptive design for cart page
  src/containers/orders/order/order-table/order-table.styles.js
Labels: refactoring, FrontEnd part, priority: medium

#1778 change styles of product details page, change size button
  src/pages/product-details/product-details.styles.js
  src/pages/product-details/product-images/product-images.styles.js
  src/pages/product-details/product-info/product-info.styles.js
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-details/product-sizes/product-sizes.styles.js
Labels: UI, FrontEnd part

#1768 Bugfix/1710/mobile header account
  src/components/app-header/app-header.js
  src/components/app-header/app-header.styles.js
  src/containers/header-right-bar/header-right-bar.styles.js
  src/containers/search-bar-list/search-bar-list.styles.js
  src/containers/search-bar/search-bar.styles.js
Labels: bug, UI, design

#1776 Redesign/1541/similar-products
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.styles.js
  src/pages/product-details/similar-products/similar-products.js
  src/pages/product-details/similar-products/similar-products.styles.js
  src/tests/unit/pages/product-details/similar-products/similar-products-item/similiar-products-item.spec.js
Labels: FrontEnd part, design

#1781 hotfix/1780/fix button color
  src/pages/product-list-page/product-list-page.styles.js
Labels: bug, UI, FrontEnd part

#1785 Feature/1779/Create certificate thanks page
  src/configs/routes.js
  src/locales/en/thanksPage.json
  src/locales/ua/thanksPage.json
  src/pages/certificate-thanks-page/certificate-thanks-card/certificate-thanks-card.js
  src/pages/certificate-thanks-page/certificate-thanks-card/certificate-thanks-card.styles.js
  src/pages/certificate-thanks-page/certificate-thanks-card/index.js
  src/pages/certificate-thanks-page/certificate-thanks-page.js
  src/pages/certificate-thanks-page/certificate-thanks-page.styles.js
  src/pages/certificate-thanks-page/index.js
  src/pages/certificate-thanks-page/operations/certificate-thanks-page.queries.js
  src/routes/routes.js
  src/tests/unit/components/certificate-thanks-card/certificate-thanks-card.spec.js
  src/tests/unit/pages/certificate-thanks-page/certificate-thanks-page.spec.js
  src/tests/unit/pages/certificate-thanks-page/certificate-thanks-page.variables.js
Labels: FrontEnd part, feature

#1584 Redesign toast component and fixed toast bugs
  src/containers/toast/toast.js
  src/containers/toast/toast.styles.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-submit/product-submit.js
Labels: FrontEnd part, redesign

#1783 HotFix/style-price-filter
  src/components/app-header/app-header.styles.js
  src/containers/header-right-bar/header-right-bar.styles.js
  src/pages/images-constructor/images-constructor.style.js
  src/pages/product-list-page/product-list-filter/product-list-filter.styles.js
  src/pages/product-list-page/product-sort/product-sort.styles.js
Labels: design

#1782 Bug/1005/unavailable
  src/locales/en/product.json
  src/locales/ua/product.json
  src/pages/product-details/product-description/product-description.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-list-page/operations/product-list.queries.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/product-list-page/product-list-item/product-list-item.style.js
  src/tests/unit/pages/product-list-page/product-list-page.variables.js
Labels: bug, FrontEnd part, redesign

#1806 Bugfix/1080/1695/upload image restrictions
  src/locales/en/error.json
  src/locales/ua/error.json
  src/pages/profile-page/avatar/avatar.js
  src/pages/profile-page/avatar/avatar.styles.js
  src/pages/profile-page/profile-page.js
  src/pages/profile-page/profile-page.styles.js
  src/tests/unit/pages/profile-page/avatar/avatar.spec.js
  src/tests/unit/pages/profile-page/profile-page.spec.js
  src/validators/profile-page.js
Labels: bug, FrontEnd part

#1812 Redesign/1757/make adaptive product detail page
  src/pages/product-details/product-details.styles.js
  src/pages/product-details/product-images/product-images.styles.js
  src/pages/product-details/product-info/product-info.js
  src/pages/product-details/product-submit/product-submit.styles.js
  src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
Labels: redesign, responsive

#1811 Bugfix/1089/not allow negative numbers in price filter
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
Labels: bug

#1808 Bugfix/1107/add appartment validation
  src/configs/regexp.js
  src/locales/en/error.json
  src/locales/ua/error.json
  src/validators/checkout.js
  src/validators/profile-page.js
Labels: bug, FrontEnd part

#1807 Feature/1800/adaptive-catalog
  src/pages/product-list-page/count-per-page/count-per-page.js
  src/pages/product-list-page/count-per-page/count-per-page.styles.js
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-list-page.styles.js
  src/pages/product-list-page/product-sort/product-sort.styles.js
Labels: FrontEnd part, design, responsive
