Repository ita-social-projects/horondi_client_fe, pull requests merged in 2022-07, with the labels that each got.

#2037 Bugfix/1958/chat form vertical scroll appears
  src/containers/chat/active-messenger/active-messenger.js
  src/containers/chat/chat.style.js
  src/containers/chat/mail-form/mail-form.js
  src/containers/chat/mail-form/tests/mail-form.spec.js
Labels: UI, FrontEnd part

#2048 Displayed price without discount within promo code was used
  src/containers/checkout/checkout-form/checkout-form.js
  src/redux/order/order.operations.js
  src/utils/checkout.js
Labels: FrontEnd part

#2052 Improvement/2023/certificates number input
  src/components/number-input/number-input.js
Labels: good first issue, FrontEnd part, Functional

#2054 Fix the video overflow and content visibility in the CREATE BY YOURSELF section
  src/pages/home/contructor-preview/constructor-preview.js
  src/pages/home/contructor-preview/constructor-preview.style.js
Labels: bug, FrontEnd part

#2066 Bugfix/2038/names get on image in catalog
  src/components/model-item/model-item.style.js
  src/pages/home/models-list/models-list.style.js
Labels: bug, FrontEnd part

#2059 After entering via google customer has to be confirmed
  src/redux/user/tests/user.sagas.spec.js
  src/redux/user/user.sagas.js
Labels: UI, FrontEnd part, Log in

#2069 fixed vertical scroll when dropdown toggle
  src/containers/header-profile/header-profile.js
  src/containers/header-profile/header-profile.styles.js
Labels: bug, FrontEnd part

#2070 Fix width change when scrolling is locked
  src/components/app-footer/app-footer.js
  src/components/app-header/app-header.js
  src/components/app-header/app-header.styles.js
  src/containers/chat/chat.style.js
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/containers/checkout/checkout-form/tests/checkout-form.variables.js
  src/containers/orders/cart/cart-item/tests/cart-item.variables.js
  src/containers/orders/operations/order.queries.js
  src/routes/routes.js
Labels: FrontEnd part

#2076 Add possibility to change theme on mobile
  src/components/app-header/app-header.js
  src/components/app-header/app-header.styles.js
  src/components/app-header/tests/app-header.spec.js
  src/containers/sidebar/sidebar.styles.js
  src/containers/sidemenu-right-bar/sidemenu-right-bar.js
  src/containers/sidemenu-right-bar/sidemenu-right-bar.styles.js
  src/containers/social-links/social-links.styles.js
  src/containers/theme/index.js
  src/containers/theme/tests/theme-component.spec.js
  src/containers/theme/theme-component.js
  src/containers/theme/theme.styles.js
  src/locales/en/header.json
  src/tests/unit/components/sidemenu-right-bar/sidemenu-right-bar.spec.js
Labels: UI, FrontEnd part, feature

#2079 change currency size
  src/containers/currency/currency.styles.js
Labels: UI, FrontEnd part
