Repository ita-social-projects/horondi_client_fe, pull requests merged in 2022-01, with the labels that each got.

#1585 test was rewrited
  src/tests/unit/pages/order-history/order-history.spec.js
  src/tests/unit/pages/order-history/order-history.variables.js
Labels: FrontEnd, test

#1583 rewrite test
  src/containers/cart-header/tests/cart-header.spec.js
Labels: FrontEnd, test

#1548 Add styles to Catalog page
  src/containers/products-filters-container/products-filters-container.js
  src/containers/products-filters-container/products-filters-container.styles.js
  src/pages/product-list-page/product-list-filter/hot-item-filter/hot-item-filter.js
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
  src/pages/product-list-page/product-list-filter/product-list-filter.styles.js
  src/pages/product-list-page/product-list-page.styles.js
  src/pages/product-list-page/product-sort/product-sort.js
  src/pages/product-list-page/product-sort/product-sort.styles.js
  src/pages/product-list-page/tests/hot-items-filter.spec.js
  src/tests/unit/pages/product-list-page/hot-items-filter.spec.js
Labels: FrontEnd, redesign

#1592 Test/1557/rewrite test ourlooks
  src/pages/home/our-looks/our-looks.js
  src/pages/home/our-looks/tests/__snapshots__/our-looks.spec.js.snap
  src/pages/home/our-looks/tests/our-looks.spec.js
  src/tests/unit/pages/home/our-looks/our-looks.spec.js
  src/tests/unit/pages/home/our-looks/our-looks.variables.js
Labels: FrontEnd, test

#1590 test/1558/rewrited to RTL
  src/pages/product-details/similar-products/similar-products-item/tests/__snapshots__/similar-products-item.test.js.snap
  src/pages/product-details/similar-products/similar-products-item/tests/similar-products-item.test.js
  src/pages/product-details/similar-products/tests/__snapshots__/similar-products.spec.js.snap
  src/pages/product-details/similar-products/tests/similar-products.spec.js
  src/pages/product-details/similar-products/tests/similar-products.variables.js
  src/tests/unit/pages/product-details/similar-products/similar-products-item/similar-products-item.variable.js
  src/tests/unit/pages/product-details/similar-products/similar-products-item/similiar-products-item.spec.js
Labels: Task, test, team4

#1527 Add Validation to Search Bar on Home Page
  src/configs/regexp.js
  src/containers/header-right-bar/header-right-bar.js
  src/containers/search-bar-list/search-bar-list.js
  src/containers/search-bar-list/search-bar-list.styles.js
  src/containers/search-bar-list/tests/search-bar-list.spec.js
  src/containers/search-bar/search-bar.js
  src/containers/search-bar/search-bar.styles.js
  src/containers/search-bar/tests/search-bar.spec.js
Labels: FrontEnd

#1587 link to By gift certificate and route to the page was created
  src/configs/routes.js
  src/containers/sidebar/CertificateIcon.js
  src/containers/sidebar/sidebar.js
  src/containers/sidebar/sidebar.styles.js
  src/locales/en/sidebar.json
  src/locales/ua/sidebar.json
  src/routes/routes.js
  src/tests/unit/components/sidebar/sidebar.spec.js
Labels: FrontEnd

#1600 console errors was fixed
  src/containers/currency/currency-component.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.styles.js
  src/containers/orders/order-history/order-history-item/order-history-item.js
  src/containers/orders/order-history/order-history-item/order-history-item.styles.js
  src/containers/orders/order/your-order/order-item/order-item.js
  src/containers/orders/order/your-order/your-order.js
  src/images/profile-icons.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/pages/wishlist/wishlist-item/wishlist-item.styles.js
Labels: bug, FrontEnd

#1601 Fix console error in CategoryItem
  src/pages/home/categories-list/category-item/category-item.js
Labels: bug, clean console

#1612 Feature/1578/create page my certificates
  src/components/app/app-theme/app.pallete.js
  src/configs/routes.js
  src/containers/my-certificates/certificate-table/certificate-table.js
  src/containers/my-certificates/certificate-table/certificate-table.styles.js
  src/containers/my-certificates/certificate-table/index.js
  src/containers/my-certificates/cetrificate-item/certificate-item.js
  src/containers/my-certificates/cetrificate-item/certificate-item.styles.js
  src/containers/my-certificates/cetrificate-item/images.js
  src/containers/my-certificates/cetrificate-item/index.js
  src/containers/my-certificates/filled-certificates/filled-certificates.js
  src/containers/my-certificates/filled-certificates/filled-certificates.styles.js
  src/containers/my-certificates/filled-certificates/index.js
  src/containers/orders/cart/empty-cart/empty-cart.js
  src/containers/orders/order/empty-order/empty-order.styles.js
  src/images/certificateCodeCopy.js
  src/images/certificates/sertificate-1000.png
  src/images/certificates/sertificate-1500.png
  src/images/certificates/sertificate-500.png
  src/locales/en/cart.json
  src/locales/en/certificate.json
  src/locales/en/index.js
  src/locales/ua/cart.json
  src/locales/ua/certificate.json
  src/locales/ua/index.js
  src/pages/my-certificates/certificates.js
  src/pages/my-certificates/certificates.styles.js
  src/pages/my-certificates/index.js
  src/routes/routes.js
Labels: UI, FrontEnd

#1613 Feature/1577/add link my certificates
  src/containers/header-profile/header-profile.js
  src/containers/header-profile/tests/header-profile.spec.js
  src/containers/orders/cart/empty-cart/tests/__snapshots__/empty-cart.test.js.snap
  src/images/gift-certificates-icon.js
  src/locales/en/header-profile.json
  src/locales/ua/header-profile.json
Labels: UI, FrontEnd

#1594 Added address auto-completion on checkout
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/delivery/nova-post/nova-post.js
  src/containers/checkout/checkout-form/delivery/ukrpost-and-courier/ukrpost-and-courier.js
  src/locales/en/profilePage.json
  src/locales/ua/profilePage.json
  src/pages/profile-page/constants.js
  src/redux/user/user.operations.js
  src/utils/checkout.js
  src/utils/checkout.spec.js
  src/utils/handle-profile-page.js
Labels: refactoring, FrontEnd

#1615 errorFix/1602/clear-console
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
Labels: FrontEnd, clean console

#1627 fix 'call us' component and currency icon in catalog
  src/components/app-header/app-header.styles.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/orders/order/your-order/order-item/order-item.js
  src/containers/orders/order/your-order/your-order.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.js
  src/pages/product-details/similar-products/similar-products-item/similar-products-item.styles.js
  src/pages/product-details/similar-products/similar-products.js
  src/pages/product-details/similar-products/similar-products.styles.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/product-list-page/product-list-item/product-list-item.style.js
Labels: FrontEnd, redesign

#1630 fix console error OrderHistory
  src/containers/orders/order-history/order-history-item/order-history-item.js
Labels: bug, clean console

#1635 fix console warning
  src/pages/login/login.js
Labels: bug, FrontEnd

#1636 fix console warning in sidebar
  src/containers/sidebar/sidebar.js
Labels: FrontEnd, clean console

#1603 search field fixed
  src/configs/index.js
  src/containers/search-bar/search-bar.js
  src/pages/product-list-page/product-list-page.js
  src/pages/product-list-page/product-sort/product-sort.js
  src/pages/product-list-page/tests/product-list-page.spec.js
  src/tests/unit/pages/product-list-page/product-list-page.spec.js
Labels: bug, FrontEnd

#1564 Align messengers icons and fixed facebook dialog position
  src/containers/chat/chat.style.js
  src/index.css
Labels: bug, FrontEnd

#1648 email fail message was added
  src/locales/en/error.json
  src/pages/register/register-from/register-form.styles.js
  src/validators/register.js
Labels: bug, FrontEnd

#1629 refactor/1628/remove redux from product & cart
  src/containers/cart-header/cart-header.js
  src/containers/cart-header/tests/cart-header.spec.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/containers/checkout/checkout.js
  src/containers/checkout/tests/checkout.spec.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/order/order-table/order-table.js
  src/containers/orders/order/your-order/order-item/order-item.js
  src/containers/orders/order/your-order/your-order.js
  src/hooks/use-cart.js
  src/pages/images-constructor/constructor-sumbit/constructor-submit.js
  src/pages/product-details/comments/comments-item/comments-item.js
  src/pages/product-details/comments/comments-item/reply-form/reply-form.js
  src/pages/product-details/constants.js
  src/pages/product-details/product-details.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/product-details/product-submit/tests/product-details.variables.js
  src/pages/product-details/product-submit/tests/product-submit.test.js
  src/pages/product-details/similar-products/similar-products.js
  src/pages/thanks-page/thanks-page.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
  src/pages/wishlist/wishlist-item/tests/wishlist-item.spec.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/redux/cart/cart.actions.js
  src/redux/cart/cart.operations.js
  src/redux/cart/cart.reducer.js
  src/redux/cart/cart.sagas.js
  src/redux/cart/cart.types.js
  src/redux/cart/tests/cart.actions.test.js
  src/redux/cart/tests/cart.reducer.test.js
  src/redux/cart/tests/cart.sagas.test.js
  src/redux/common-store/common.actions.js
  src/redux/common-store/common.reducer.js
  src/redux/common-store/common.types.js
  src/redux/common-store/test/common.action.spec.js
  src/redux/common-store/test/common.reducer.spec.js
  src/redux/newCart/cart.actions.js
  src/redux/newCart/cart.reducer.js
  src/redux/newCart/cart.types.js
  src/redux/products/products.reducer.js
  src/redux/root.reducer.js
  src/redux/root.saga.js
  src/redux/user/tests/user.actions.spec.js
  src/redux/user/tests/user.mocks.js
  src/redux/user/tests/user.sagas.spec.js
  src/redux/user/user.actions.js
  src/redux/user/user.operations.js
  src/redux/user/user.sagas.js
  src/redux/user/user.types.js
  src/tests/unit/components/your-order/your-order.spec.js
  src/tests/unit/components/your-order/your-order.variables.js
  src/tests/unit/pages/product-details/similar-products/similar-products-item/similiar-products-item.spec.js
  src/tests/unit/pages/product-details/similar-products/similar-products.spec.js
  src/tests/unit/pages/product-details/similar-products/similar-products.variables.js
  src/utils/checkout.js
  src/utils/multiple.selectors.js
  src/utils/productDetails.js
  src/utils/productDetails.spec.js
Labels: refactoring, FrontEnd

#1646 bugfix/1641/1640/fix dropdown shifting
  src/components/app-header/app-header.styles.js
Labels: bug, FrontEnd

#1645 fixWishListQueries
  src/pages/wishlist/operations/wishlist.mutations.js
Labels: FrontEnd

#1650 fix tooltip position on comment form buttons
  src/pages/product-details/comments/comments.js
Labels: bug, FrontEnd

#1662 bugfix/1661/fix console warning
  src/images/verifiedPurchaseIcon.js
  src/pages/product-details/comments/comments-item/comments-item.js
Labels: FrontEnd, clean console

#1658 Hotfix/fix sidebar
  src/containers/sidebar/sidebar.js
Labels: bug, FrontEnd

#1664 error fild to email was added
  src/validators/checkout.js
Labels: bug, FrontEnd

#1656 bugfix/1609/fix reply for deleted user
  src/pages/product-details/comments/comments-item/reply-form/reply-form.js
Labels: bug, FrontEnd

#1660 fixButtonStyles
  src/pages/wishlist/empty-wishlist/empty-wishlist.js
Labels: FrontEnd

#1672 Bugfix/1163/fix dublicates sizes names
  src/pages/product-details/product-sizes/product-sizes.js
  src/pages/product-details/product-sizes/tests/product-sizes.test.js
  src/pages/product-details/product-sizes/tests/product-sizes.variables.js
  src/pages/product-details/tests/__snapshots__/product-details.spec.js.snap
Labels: bug, FrontEnd

#1655 fixSearchBar
  src/containers/search-bar/search-bar.js
Labels: FrontEnd

#1674 fix translations button to catalog in the cart
  src/locales/en/cart.json
Labels: bug, FrontEnd

#1665 Create page 'Buy certificate'
  src/configs/index.js
  src/images/sertificate.svg
  src/locales/en/certificates.json
  src/locales/en/index.js
  src/locales/ua/certificates.json
  src/locales/ua/index.js
  src/pages/gift-certificate/certificate-checkbox/certificate-checkbox.js
  src/pages/gift-certificate/certificate-checkbox/certificate-checkbox.styles.js
  src/pages/gift-certificate/certificate-checkbox/index.js
  src/pages/gift-certificate/gift-certificate.js
  src/pages/gift-certificate/gift-certificate.styles.js
  src/pages/gift-certificate/index.js
  src/routes/routes.js
  src/validators/email.js
Labels: UI, FrontEnd

#1679 bugfix/1003/phone number validation fix
  src/configs/regexp.js
Labels: bug, FrontEnd part

#1691 Bugfix/1681/fix query checkout
  src/containers/orders/order/your-order/order-item/order-item.js
  src/tests/unit/components/your-order/your-order.spec.js
Labels: bug, FrontEnd part

#1683 added password confirmation field
  src/locales/en/error.json
  src/locales/en/register.json
  src/locales/ua/error.json
  src/locales/ua/register.json
  src/pages/register/constants.js
  src/pages/register/register-from/register-form.js
  src/pages/register/register.js
  src/utils/eyeToggle.js
  src/validators/register.js
Labels: bug, FrontEnd part

#1690 Error messages not displayed
  src/containers/chat/active-messenger/active-messenger.js
  src/locales/ua/error.json
Labels: bug, FrontEnd part

#1692 When you click on the wishlist in the burger menu, it closes.
  src/containers/sidemenu-right-bar/sidemenu-right-bar.js
Labels: bug, FrontEnd part

#1694 fix/1083/checkoutPage
  src/validators/checkout.js
Labels: FrontEnd part
