Repository ita-social-projects/horondi_client_fe, pull requests merged in 2022-08, with the labels that each got.

#2097 Added correct initial state for cart and wishlist
  src/components/app/app.js
  src/configs/index.js
  src/containers/cart-header/cart-header.js
  src/containers/cart-header/tests/cart-header.spec.js
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/containers/checkout/checkout.js
  src/containers/checkout/tests/checkout.spec.js
  src/containers/wishlist-header/tests/wishlist-header.spec.js
  src/containers/wishlist-header/wishlist-header.js
  src/context/cart-context.js
  src/context/wishlist-context.js
  src/hooks/tests/use-cart.spec.js
  src/hooks/tests/use-wishlist.spec.js
  src/hooks/use-cart.js
  src/hooks/use-wishlist.js
  src/pages/cart/cart.js
  src/pages/images-constructor/constructor-sumbit/constructor-submit.js
  src/pages/images-constructor/constructor-sumbit/tests/constructor-submit.spec.js
  src/pages/images-constructor/images-constructor.js
  src/pages/product-details/product-submit/product-submit.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
  src/pages/wishlist/filled-wishlist/tests/filled-wishlist.spec.js
  src/pages/wishlist/tests/wishlist.spec.js
  src/redux/common-store/common.actions.js
  src/redux/common-store/common.reducer.js
  src/redux/user/tests/user.sagas.spec.js
  src/redux/user/user.sagas.js
  src/services/local-storage.service.js
Labels: bug, FrontEnd part

#2100 fixed thank you page styles.
  src/pages/thanks-page/thanks-card/thanks-card.styles.js
  src/pages/thanks-page/thanks-page.styles.js
Labels: bug, UI, FrontEnd part

#2085 add possibility to use certificate in the cart
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/cart/filled-cart/tests/filled-cart.spec.js
  src/containers/orders/cart/filled-cart/tests/filled-cart.variables.js
  src/containers/orders/operations/getCertificateByParams.queries.js
  src/containers/orders/order/order-table/order-table.js
  src/hooks/tests/use-cart.spec.js
  src/hooks/tests/use-cart.variables.js
  src/hooks/use-cart.js
  src/locales/en/cart.json
  src/locales/ua/cart.json
Labels: FrontEnd part, feature

#2103 Price at fondy display without a discount
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/delivery/worldwide/worldwide.js
Labels: bug, FrontEnd part

#2110 Bugfix/2104/certain category promo crosses out other
  src/components/scroll-bar/tests/scroll-bar.spec.js
  src/components/scroll-bar/tests/scroll-bar.variables.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/search-bar/search-bar.js
  src/containers/search-bar/search-bar.styles.js
  src/pages/profile-page/avatar/avatar.js
Labels: bug, FrontEnd part

#2120 fixed bug with certificate value
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/cart/filled-cart/tests/filled-cart.spec.js
  src/hooks/tests/use-cart.spec.js
  src/hooks/tests/use-currency.spec.js
  src/hooks/use-cart.js
  src/hooks/use-currency.js
Labels: bug, FrontEnd part, Functional

#2125 Feature/2115/Certificates sorting
  src/containers/my-certificates/certificate-table/certificate-table.js
Labels: FrontEnd part, feature

#2124 add gift icon and actions block
  src/configs/index.js
  src/containers/my-certificates/certificate-table/certificate-table.styles.js
  src/containers/my-certificates/cetrificate-item/certificate-item.js
  src/containers/my-certificates/cetrificate-item/certificate-item.styles.js
  src/images/certificates/certificateCodeCopy.js
  src/images/certificates/certificateCodeGift.js
  src/locales/en/certificate.json
  src/locales/ua/certificate.json
  src/tests/unit/containers/my-certificates/certificate-table/certificate-table.spec.js
  src/tests/unit/containers/my-certificates/filled-certificates/filled-certificates.spec.js
  src/tests/unit/pages/my-certificates/my-certificates.spec.js
Labels: FrontEnd part, feature
