Repository ita-social-projects/horondi_client_fe, pull requests merged in 2022-09, with the labels that each got.

#2126 User can login without confirmed email
  src/locales/en/error.json
  src/locales/ua/error.json
  src/pages/login/constants.js
  src/pages/login/login.js
  src/pages/new-password/new-password.js
  src/pages/recovery/recovery.js
  src/pages/register/register.js
  src/redux/user/tests/user.sagas.spec.js
  src/redux/user/user.sagas.js
  src/tests/unit/pages/login/login.spec.js
  src/translations/user.translations.js
  src/utils/handle-confirmation.js
Labels: bug, FrontEnd part

#2128 Feature/2112/price with discount after adding certificate
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/order/your-order/your-order.js
  src/redux/order/order.operations.js
  src/tests/unit/components/your-order/your-order.spec.js
  src/tests/unit/components/your-order/your-order.variables.js
  src/utils/checkout.js
Labels: FrontEnd part, feature

#2127 Redirect to thanks page after payment
  src/configs/routes.js
  src/containers/checkout/checkout-form/checkout-form.js
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/containers/checkout/checkout.js
  src/locales/ua/thanksPage.json
  src/pages/thanks-page/thanks-card/thanks-card.js
  src/pages/thanks-page/thanks-card/thanks-card.styles.js
  src/pages/thanks-page/thanks-page.js
  src/pages/thanks-page/thanks-page.styles.js
  src/redux/order/order.operations.js
  src/redux/order/order.sagas.js
  src/routes/routes.js
  src/tests/unit/components/thanks-card/thanks-card.spec.js
  src/tests/unit/pages/thanks-page/thanks-page.spec.js
  src/tests/unit/pages/thanks-page/thanks-page.variables.js
Labels: FrontEnd part

#2134 Created pop up after clicking on gift certificate icon
  src/components/confirm-dialog/confirm-dialog.js
  src/components/confirm-dialog/confirm-dialog.styles.js
  src/components/confirm-dialog/index.js
  src/components/modal/modal.js
  src/components/modal/modal.styles.js
  src/components/modal/tests/modal.spec.js
  src/containers/modal-gift-certificate/index.js
  src/containers/modal-gift-certificate/modal-gift-certificate.js
  src/containers/modal-gift-certificate/modal-gift-certificate.styles.js
  src/containers/modal-gift-certificate/tests/mocal-gift-certificate.variables.js
  src/containers/modal-gift-certificate/tests/modal-gift-certificate.spec.js
  src/containers/my-certificates/certificate-table/certificate-table.js
  src/containers/my-certificates/cetrificate-item/certificate-item.js
  src/containers/my-certificates/filled-certificates/filled-certificates.js
  src/containers/orders/order/order-table/order-table.js
  src/containers/orders/order/order-table/tests/order-table.test.js
  src/containers/orders/order/order-table/tests/order-table.variables.js
  src/locales/en/modal.json
  src/locales/ua/modal.json
  src/pages/gift-certificate/operations/gift-certificate.mutations.js
  src/pages/images-constructor/images-constructor.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
  src/validators/email.js
Labels: FrontEnd part, feature

#2137 Certificate thanks page is not displayed after payment
  src/locales/en/thanksPage.json
  src/locales/ua/thanksPage.json
  src/pages/certificate-thanks-page/certificate-thanks-card/certificate-thanks-card.js
  src/pages/certificate-thanks-page/certificate-thanks-card/certificate-thanks-card.styles.js
  src/pages/certificate-thanks-page/certificate-thanks-page.js
  src/pages/gift-certificate/gift-certificate.js
  src/tests/unit/components/certificate-thanks-card/certificate-thanks-card.spec.js
  src/tests/unit/pages/certificate-thanks-page/certificate-thanks-page.spec.js
Labels: FrontEnd part

#2141 scroll to top after navigate another page
  src/components/scroll-to-top/scroll-to-top.js
  src/components/scroll-to-top/tests/scroll-to-top.spec.js
  src/routes/routes.js
Labels: bug, FrontEnd part

#2142 added successfully gifted certificate modal
  src/containers/modal-gift-certificate/modal-gift-certificate.js
  src/containers/modal-gift-certificate/modal-gift-certificate.styles.js
  src/containers/modal-gift-certificate/tests/mocal-gift-certificate.variables.js
  src/containers/modal-gift-certificate/tests/modal-gift-certificate.spec.js
  src/containers/modal-successful-gift/modal-successful-gift.js
  src/containers/my-certificates/filled-certificates/filled-certificates.js
  src/locales/en/modal.json
  src/locales/ua/modal.json
Labels: FrontEnd part, feature
