Repository ita-social-projects/horondi_client_fe, pull requests merged in 2022-04, with the labels that each got.

#1874 Bugfix/1870/fix bug with validation in profile form
  src/locales/ua/error.json
Labels: bug, FrontEnd part

#1860 Refactor/1839/refactor test for category item component1
  src/pages/home/categories-list/category-item/category-item.js
  src/pages/home/categories-list/category-item/tests/category-item.spec.js
  src/tests/unit/pages/home/categories-list/category-item/category-item.spec.js
Labels: refactoring, FrontEnd part, test

#1862 refactor test for EmptyOrder component
  src/containers/orders/order/empty-order/empty-order.js
  src/containers/orders/order/empty-order/tests/__snapshots__/empty-order.test.js.snap
  src/containers/orders/order/empty-order/tests/empty-order.test.js
  src/tests/unit/containers/orders/order/empty_order/empty-order.spec.js
Labels: refactoring, FrontEnd part, test

#1872 refactor CategoriesList tests
  src/pages/home/categories-list/tests/categories-list.spec.js
  src/tests/unit/pages/home/categories-list/categories-list.spec.js
  src/tests/unit/pages/home/categories-list/categories-list.variables.js
Labels: refactoring, FrontEnd part, test

#1875 BugFix/1014/clear price filter on currency change
  src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
Labels: bug, FrontEnd part

#1877 Feature/1854/skipped tests
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/containers/orders/cart/cart-item/tests/cart-item.spec.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/cart/filled-cart/tests/filled-cart.spec.js
  src/containers/orders/cart/filled-cart/tests/filled-cart.variables.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/pages/images-constructor/constructor-sumbit/tests/constructor-submit.spec.js
  src/pages/images-constructor/constructor-sumbit/tests/constructor.variables.js
  src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js
Labels: FrontEnd part, test

#1883 Fixed incorrect color of chat button in dark mode
  src/components/app/app-theme/theme.js
Labels: bug, UI, priority: low

#1879 After user info on the user page crashes when clicking on the button Save
  src/redux/user/user.operations.js
Labels: bug, FrontEnd part

#1882 fixed bug with overlaping icons
  src/containers/sidemenu-right-bar/sidemenu-right-bar.styles.js
Labels: bug, FrontEnd part

#1885 Fixed images-constructor test
  src/pages/images-constructor/tests/images-constructor.spec.js
Labels: FrontEnd part, test

#1887 Changed buttons color and hover effect according to figma layout
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/components/auth-form/auth-form-button/auth-form-button.styles.js
  src/components/modal/modal.styles.js
  src/containers/checkout/checkout-form/checkout-form.styles.js
  src/containers/my-certificates/filled-certificates/filled-certificates.styles.js
  src/pages/home/contructor-preview/constructor-preview.js
  src/pages/home/contructor-preview/constructor-preview.style.js
  src/pages/home/models-list/models-list.style.js
  src/pages/home/models-list/tests/models-list.spec.js
  src/pages/home/slider/slider-home-page.style.js
  src/pages/images-constructor/constructor-sumbit/constructor-submit.styles.js
  src/pages/news/news-detail/news-detail.style.js
  src/pages/product-details/comments/comments.styles.js
  src/pages/thanks-page/thanks-card/thanks-card.styles.js
  src/pages/wishlist/wishlist-item/wishlist-item.styles.js
  src/tests/unit/components/thanks-card/thanks-card.spec.js
  src/tests/unit/pages/thanks-page/thanks-page.spec.js
Labels: UI, FrontEnd part

#1894 [Customer Support Chat] Button 'Send' goes outside Customer Support Chat window
  src/containers/chat/chat.style.js
Labels: bug, UI, FrontEnd part

#1880 query slider data from backend
  src/images/ArrowLeft.svg
  src/images/ArrowRight.svg
  src/pages/home/operations/slider/slider.queries.js
  src/pages/home/slider/slider-data.js
  src/pages/home/slider/slider-home-page.js
  src/pages/home/slider/slider-home-page.style.js
  src/tests/unit/pages/home/slider/slider-home-page.spec.js
  src/tests/unit/pages/home/slider/slider-home-page.variables.js
Labels: FrontEnd part

#1901 fix bug with list order
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
Labels: bug, FrontEnd part, Functional

#1903 Fix logination bug
  src/redux/user/tests/user.sagas.spec.js
  src/redux/user/user.operations.js
  src/redux/user/user.sagas.js
  src/utils/client.js
Labels: bug, FrontEnd part

#1899 Add canvas image to orderItem from constructor on order-history and checkout pages
  src/components/constructor-canvas/constructor-canvas.js
  src/containers/orders/operations/getConstructorByModel.query.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.styles.js
  src/containers/orders/order/your-order/order-item/order-item.js
  src/pages/order-history/operations/order-history.queries.js
  src/tests/unit/components/order-history-item/order-history-item.spec.js
  src/tests/unit/components/order-history-item/order-history-item.variables.js
  src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js
  src/tests/unit/components/order-history-list-item/order-history-item-product.variables.js
Labels: bug, FrontEnd part
