Repository ita-social-projects/horondi_client_fe, pull requests merged in 2022-10, with the labels that each got.

#2139 Certificates attached to email
  src/containers/modal-gift-certificate/modal-gift-certificate.js
  src/containers/modal-gift-certificate/tests/modal-gift-certificate.spec.js
  src/containers/my-certificates/filled-certificates/filled-certificates.js
  src/pages/my-certificates/my-certificates.js
  src/tests/unit/pages/my-certificates/my-certificates.spec.js
  src/tests/unit/pages/my-certificates/my-certificates.variables.js
Labels: FrontEnd part, feature

#2151 Added password recovery error
  src/components/auth-form/auth-form-wrapper/auth-form-wrapper.styles.js
  src/pages/recovery/recovery.js
  src/pages/recovery/recovery.styles.js
  src/redux/user/tests/user.sagas.spec.js
  src/redux/user/user.sagas.js
  src/utils/handle-recovery-page.js
Labels: FrontEnd part, feature

#2149 Notify the user certificate expires
  src/components/app-header/app-header.js
  src/components/app-header/app-header.styles.js
  src/components/app-header/tests/app-header.spec.js
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/components/header-notification-bar/header-notification-bar.js
  src/components/header-notification-bar/header-notification-bar.styles.js
  src/components/header-notification-bar/index.js
  src/containers/header-profile/header-profile.styles.js
  src/containers/modal-gift-certificate/modal-gift-certificate.js
  src/containers/modal-gift-certificate/tests/modal-gift-certificate.spec.js
  src/containers/modal-successful-gift/modal-successful-gift.js
  src/containers/my-certificates/filled-certificates/filled-certificates.js
  src/containers/my-certificates/notification-certificate-ends/index.js
  src/containers/my-certificates/notification-certificate-ends/notification-certificate-ends.js
  src/containers/my-certificates/notification-certificate-ends/notification-certificate-ends.styles.js
  src/locales/en/certificate.json
  src/locales/en/modal.json
  src/locales/ua/certificate.json
  src/locales/ua/modal.json
  src/redux/user/user.operations.js
  src/routes/routes.js
  src/routes/routes.style.js
Labels: FrontEnd part, feature

#2154 added snackbar to copy icon
  src/containers/my-certificates/cetrificate-item/certificate-item.js
  src/locales/en/certificate.json
  src/locales/ua/certificate.json
  src/tests/unit/containers/my-certificates/certificate-item/certificate-item.spec.js
Labels: FrontEnd part

#2167 Orders history prices without discount
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.styles.js
  src/containers/orders/order-history/order-history-item/order-history-item.js
  src/containers/orders/order-history/order-history-item/order-history-item.styles.js
  src/containers/orders/order-history/order-history-table/order-history-table.js
  src/containers/orders/order-history/order-history-table/order-history-table.style.js
  src/hooks/use-currency.js
  src/pages/order-history/operations/order-history.queries.js
  src/pages/order-history/order-history.styles.js
  src/tests/unit/components/order-history-item/order-history-item.spec.js
  src/tests/unit/components/order-history-item/order-history-item.variables.js
  src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js
  src/tests/unit/pages/order-history/order-history.variables.js
Labels: bug, FrontEnd part

#2135 Feature/2113/certificate status should change
  src/components/app/app-theme/app.pallete.js
  src/components/app/app-theme/theme.js
  src/components/table/TableBodyRow/TableBodyRow.js
  src/components/table/TableBodyRow/index.js
  src/components/table/index.js
  src/components/table/table.js
  src/components/table/table.styles.js
  src/configs/index.js
  src/containers/my-certificates/certificate-table/certificate-table.js
  src/containers/my-certificates/certificate-table/certificate-table.styles.js
  src/containers/my-certificates/cetrificate-item/certificate-item.js
  src/containers/my-certificates/cetrificate-item/certificate-item.styles.js
  src/containers/my-certificates/cetrificate-item/index.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/operations/getCertificateByParams.queries.js
  src/containers/orders/order/order-table/order-table.js
  src/locales/en/certificate.json
  src/locales/ua/certificate.json
  src/pages/my-certificates/operations/my-certificates.queries.js
  src/tests/unit/containers/my-certificates/certificate-item/certificate-item.spec.js
  src/tests/unit/containers/my-certificates/certificate-item/certificate-item.variable.js
  src/tests/unit/containers/my-certificates/certificate-table/certificate-table.spec.js
  src/tests/unit/containers/my-certificates/certificate-table/certificate-table.variables.js
  src/tests/unit/containers/my-certificates/filled-certificates/filled-certificates.spec.js
  src/tests/unit/pages/my-certificates/my-certificates.spec.js
  src/tests/unit/pages/my-certificates/my-certificates.variables.js
Labels: FrontEnd part, feature

#2173 Feature/2169/fix loader in login page
  src/components/auth-form/auth-form-button/auth-form-button.js
  src/pages/login/login.js
  src/pages/new-password/new-password.js
  src/pages/new-password/tests/new-password.test.js
  src/pages/recovery/recovery.js
  src/pages/recovery/tests/recovery.test.js
  src/pages/register/register-from/register-form.js
  src/tests/unit/components/auth-form/auth-form-button/auth-form-button.spec.js
  src/tests/unit/pages/login/login.spec.js
  src/tests/unit/pages/register/register-form.spec.js
  src/utils/handle-new-password.js
  src/utils/handle-recovery-page.js
  src/validators/new-password.js
Labels: refactoring, FrontEnd part, redesign

#2178 sending email after successful payment
  src/pages/thanks-page/thanks-page.js
  src/redux/order/order.actions.js
  src/redux/order/order.operations.js
  src/redux/order/order.sagas.js
  src/redux/order/order.types.js
  src/redux/order/tests/order.actions.test.js
  src/redux/order/tests/order.sagas.test.js
  src/redux/order/tests/order.variables.js
  src/tests/unit/pages/thanks-page/thanks-page.spec.js
  src/utils/checkout.js
Labels: bug, FrontEnd part

#2192 Change colour of lastImageText on product page
  src/pages/product-details/product-images/product-images.styles.js
Labels: bug, FrontEnd part

#2194 expanded useCart hook
  src/components/app-header/app-header.js
  src/components/app-header/tests/app-header.spec.js
  src/containers/cart-header/cart-header.js
  src/containers/cart-header/tests/cart-header.spec.js
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/containers/checkout/checkout.js
  src/containers/checkout/tests/checkout.spec.js
  src/containers/orders/cart/filled-cart/filled-cart.js
  src/containers/orders/order/your-order/your-order.js
  src/context/cart-context.js
  src/hooks/tests/use-cart.spec.js
  src/hooks/use-cart.js
  src/pages/cart/cart.js
  src/pages/images-constructor/constructor-sumbit/tests/constructor-submit.spec.js
  src/pages/product-details/product-submit/tests/product-submit.test.js
  src/pages/thanks-page/thanks-page.js
  src/redux/common-store/common.actions.js
  src/redux/common-store/test/common.action.spec.js
  src/redux/common-store/test/common.reducer.spec.js
  src/tests/unit/components/your-order/your-order.spec.js
  src/tests/unit/pages/thanks-page/thanks-page.spec.js
Labels: bug, FrontEnd part

#2190 Added useProductImage hook
  src/containers/checkout/checkout-form/tests/checkout-form.spec.js
  src/containers/orders/cart/cart-item/cart-item.js
  src/containers/orders/cart/cart-item/tests/cart-item.spec.js
  src/containers/orders/cart/filled-cart/tests/filled-cart.spec.js
  src/containers/orders/operations/order.queries.js
  src/containers/orders/order-history/order-history-item-product/order-history-item-product.js
  src/containers/orders/order/order-table/tests/order-table.test.js
  src/containers/orders/order/your-order/order-item/order-item.js
  src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.js
  src/containers/search-bar-list/search-bar-list-item/search-bar-list-item.styles.js
  src/containers/search-bar/tests/search-bar.spec.js
  src/hooks/use-debounce.js
  src/hooks/use-product-image.js
  src/pages/materials/materials.js
  src/pages/product-details/product-images/product-images.js
  src/pages/product-details/tests/product-images.spec.js
  src/pages/product-list-page/product-list-item/product-list-item.js
  src/pages/product-list-page/product-list-item/product-list-item.style.js
  src/pages/wishlist/filled-wishlist/filled-wishlist.js
  src/pages/wishlist/wishlist-item/tests/wishlist-item.spec.js
  src/pages/wishlist/wishlist-item/tests/wishlist-item.variables.js
  src/pages/wishlist/wishlist-item/wishlist-item.js
  src/pages/wishlist/wishlist-item/wishlist-item.styles.js
  src/tests/unit/components/order-history-item/order-history-item.spec.js
  src/tests/unit/components/order-history-list-item/order-history-item-product.spec.js
  src/tests/unit/components/your-order/your-order.spec.js
  src/tests/unit/pages/order-history/order-history.spec.js
Labels: FrontEnd part

#2193 Change image position/height on successful registration page
  src/pages/confirmation/confirmation.styles.js
  src/routes/routes.style.js
Labels: bug, FrontEnd part
